### ISSUE TITLE
App restart needed.  App = probation-staffing-model-dash-app

### ISSUE THREAD

**Issue by w-wood** [ministryofjustice/data-platform-support#101]
### What happened?

We've revised some of the data used by this app, so need it restarted to pick up the changes.

This app has **NOT** been migrated yet.

**Comment by jacobwoffenden** [comment]
application has been restarted, awaiting feedback from @w-wood via Slack

**Comment by w-wood** [comment]
All looks okay, so issue can be closed.  Thanks.
