### ISSUE TITLE
Can't sign in to app

### ISSUE THREAD

**Issue by lauratraceymoj** [ministryofjustice/data-platform-support#102]
### Which tool do you need help with?

Auth0

### What happened?

Customer can't sign in to the Safety Diagnostic Tool (https://safety-diagnostic-tool.apps.alpha.mojanalytics.xyz/) they keep getting redirected to this page when clicking the orange sign up with safety-diagnostic-tool button. They have tried clearing their cookies and doesn't make a difference. They have said they are using a 'laptop which is set up for probation only'.
![image](https://github.com/ministryofjustice/data-platform-support/assets/89846507/79e08ada-1a38-4727-80b6-920123b7cd00)

**Comment by lauratraceymoj** [comment]
User is trying to access with MS Edge and is using Dom1

**Comment by jacobwoffenden** [comment]
Thanks @lauratraceymoj, we're trying to recreate this issue.

Do you see the same behaviour when accessing this app?

**Comment by jacobwoffenden** [comment]
Same application as https://github.com/ministryofjustice/data-platform-support/issues/103

**Comment by lauratraceymoj** [comment]
Hi Jacob, I couldn't recreate but have gone back to clarify with the customer what is happening and they have now said they get stuck on this page **after** trying to sign in so it is a problem with their nomis account which they are sorting. This can probably be closed now
