### ISSUE TITLE
[Dashboard Apps]:  safety-diagnostic-tool - User couldn't get redirected into login after certain period time

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/data-platform-support#103]
### Which tool do you need help with?

Auth0

### What happened?

This bug came from an user’s support query ,  the original link is below 

https://asdslack.slack.com/archives/C4PF7QAJZ/p1665566997786169 - Connect your Slack account

1 - The original query below 

Hi, I've got a customer who is struggling to use one of our deployed apps (https://safety-diagnostic-tool.apps.alpha.mojanalytics.xyz/) They say they are able to log in fine and then get called away to this page and are unable to get back onto the app. Is anyone able to help with what might be causing this and how can we fix it?
![76927daf-5659-406f-97ac-04daa08791ad](https://github.com/ministryofjustice/data-platform-support/assets/26111671/8a7b0c72-3e7e-435e-8548-0786c524d761)
2 - extra information passed from the user raising this query 
how this happened?
```
It happens if we log onto SDT then leave the page, to look at another email etc. When we then go back on it, it flashes then comes up with this error.
They use Microsoft Edge V106.0.1370.42

The user also said she suggested this customer cleared the cookie up, then the page started to work again 
```
3 - Received other information from same app 

```
Hi Yikang, just looking to see if it's possible revisit the above as we've recently got some emails from customers about a similar issue preventing them being able to do their job. I don't think anyone has had the specific error message in the above thread in a while and I haven't been able to recreate but a similar (probably related) issue is that the app screen greys out and becomes unresponsive after a few minutes of logging into the app. Here's a screenshot of some of the errors when I inspect the page when this occurs if that helps, and my nomis username is TL004644
```
![Uploading 16e6eec2-079c-4f29-9d92-48840c0b43c7.png…]()
![29dd4593-306e-4f1b-b6f1-dddbcaaa9b32](https://github.com/ministryofjustice/data-platform-support/assets/26111671/05f3cb83-2fa6-453c-8317-be9227d9e2eb)

**Comment by ymao2** [comment]
@lauratraceymoj,   I raised this issue on your behalf,   and I give some updates for the process of the ticket:  I spent quite some times to think about what is potential cause and checked all those related tools and codes,  I come out a theory about this problem:  the errors may link to the action of keeping retrying to re-connect to the shiny app from browser through socketjs,  it will fire info call to initialise the conversation with rshiny-server (nodejs server), the call will hit auth-proxy first, it will try to redirect user to auth0 due to session timeout or invalid (not sure),  but it always failed due to CORS. 

My proposal is to try 2 solution
- Option 1:  remove the socketjs entirely as the browsers now should support raw (native) websocket, no need to use socketjs
- Option 2:  allow info call pass the auth-proxy as it is part of societjs protocol , no any information will be exposed, then it shouldn't have CORD issue 

I have developed both solutions ,  
- Option1: need more time to test as it has a relevant big impact compared with current version of rshiny-server 
- Option2: I have tested the version briefly on another app,  I am thinking to test it on your live app ,  what do you think?  if you concern about it,  as this app has been opted in tranche2 app-migration,  do you want to test it on CP dev environment which is safer choice,  let me know what is your thought?   this new version also offers easy-logout-method like typing <app_url>/logout on browser to reset user's session

**Comment by lauratraceymoj** [comment]
@ymao2 Thanks for your help on this! We'd like to wait and test option 2 in the dev environment after migration if possible

**Comment by ymao2** [comment]
@lauratraceymoj ,  no problem, agreed, let us test the option2 on safer environment (CP's dev env)

**Comment by ymao2** [comment]
we agree to do the testing this week
