### ISSUE TITLE
I need Athena and S3 access to be added to this role aws-quicksight-s3-consumers-role-v0

### ISSUE THREAD

**Issue by opmoj** [ministryofjustice/data-platform-support#105]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I am able to view tables and run queries in Athena. However, I do not have full Athena permissions to add a data source from Athena to Quicksight. 

Please note I have asked here previously and was referred to the ask-data-engineering channel. That channel has said they are unable to do this but that the creator of this role `aws-quicksight-s3-consumers-role-v0` should be able to. Could you please have a look again? Thanks

### Relevant log output

```bash
region:eu-west-1
timestamp:1685033783345
requestId:fed0500d-3786-4715-bdc5-9f052a4e8dd9
sourceErrorCode:INSUFFICIENT_PERMISSIONS
sourceErrorMessage:[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. User: arn:aws:sts::5932916xxx:assumed-role/aws-quicksight-s3-consumers-role-v0/QuickSight-RoleSession-1685033783031 is not authorized to perform: athena:ListDataCatalogs because no session policy allows the athena:ListDataCatalogs action [Execution ID not available]
```

**Comment by jacobwoffenden** [comment]
@opmoj I have added `athena:ListDataCatalogs` to `arn:aws:iam::593291632749:role/service-role/aws-quicksight-service-role-v0` via an inline policy `AWSQuickSightAthenaAdditional`, can you try the action again please

**Comment by opmoj** [comment]
Thanks @jacobwoffenden . Julia has tried several scenarios too so will continue working with her to try to get this resolved.
