### ISSUE TITLE
Streamlit Support on the AP

### ISSUE THREAD

**Issue by foufoulides** [ministryofjustice/data-platform-support#106]
### What happened?

Hello,

Several months ago, we had discussions with the AP Team to add [Streamlit](https://streamlit.io/) to the AP and there was enthusiasm for it from all sides, but with work getting in the way movement on it halted.

Last year, I did quite a bit of looking, learning, and playing around with the various Web App modules and Streamlit seems to be the best choice. Below I have a slide from a presentation I did at the Data Science Festival last year that compares the main Python Web App tools, and also shows the rabid popularity of Streamlit though GitHub data. 

We have had Dash available on the AP for a long time, but it is not being used because developing even simple Apps requires a lot of development. (I even took a long, comprehensive Udemy course on Dash and I wouldn't want to develop a Web App on it!). So, in practice we are left without any Python Web App functionality on the AP.  Who would be the best person to discuss on how much work etc. would be needed to make it available on the AP?

Thank you

![StreamlitSlide](https://github.com/ministryofjustice/data-platform-support/assets/88317797/10398972-3a36-4062-8e5b-c9a621114617)

**Comment by LouiseABowler** [comment]
As discussed on Slack, the AP team won't be looking at deploying new apps until the end of September (assuming app migration is complete), so let's check in about this then.
