### ISSUE TITLE
Can't turn off Quicksight auto-refresh

### ISSUE THREAD

**Issue by ThomasHepworth** [ministryofjustice/data-platform-support#112]
### Which tool do you need help with?

Amazon Web Services, User and Account

### What happened?

I've lost my admin access to quicksight (I imagine because my username was changed from `th368` -> `ThomasHepworth`) and now can't stop a series of data refreshes from occurring.

These refreshes are all for a dashboard pertaining to COVID data. The dashboard was decommissioned a while back, but it appears the refreshes are still ongoing.

Would someone be able to either:
1. Give me brief admin/creator access to quicksight so I can switch these data refreshes off
2. Turn off the refreshes for me. There are about 12 data refreshes occurring, so I won't detail them in here unless it's a necessity.

**Comment by julialawrence** [comment]
Will touch base with @ThomasHepworth to see if this is still needed, close if not.
