### ISSUE TITLE
can't install packages in RStudio

### ISSUE THREAD

**Issue by drapclark** [ministryofjustice/data-platform-support#113]
### Which tool do you need help with?

RStudio

### What happened?

I get the following error at the start of a new R session (see output).

### Relevant log output

```bash
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
```

**Comment by michaeljcollinsuk** [comment]
Hi @drapclark please see the guidance for this issue in the documentation [here](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/package-management.html#renv-tips-and-tricks). This is also discussed in an old support request in the slack channel [here](https://mojdt.slack.com/archives/C4PF7QAJZ/p1656927969065209) in case the docs are not clear.

Please also note that there is a [slack channel #R](https://mojdt.slack.com/archives/C1PUCG719) where you can get help for R specific issues. Thanks!
