### ISSUE TITLE
Please can I be given access to the AP?

### ISSUE THREAD

**Issue by ThomasClarke5** [ministryofjustice/data-platform-support#114]
### Which tool do you need help with?

User and Account

### What happened?

I raised on #ask-operations-engineering and was told to raise a ticket here for an account with username ThomasClarke5.

Do let me know if you need anything else

**Comment by bagg3rs** [comment]
Sorry about the bounce around and we have updated our docs just to make it clear that you just need to be invited to the Analytical Services GitHub Org which then gives you access to AP. 
✉️ Invite is on its way, please accept when you can.

**Comment by ThomasClarke5** [comment]
Accepted now thanks!

**Comment by bagg3rs** [comment]
Invite accepted!
