### ISSUE TITLE
cannot sign in to R via github not sure why

### ISSUE THREAD

**Issue by morotiolutimehin** [ministryofjustice/data-platform-support#116]
### Which tool do you need help with?

Control Panel

### What happened?

when i click on the 'sign in with github' it takes me to a page saying 'there is a problem with your session'

### Relevant log output

```bash
There is a problem with your session
It might have timed out in which case you can reset your session , and login again.

If resetting your session doesn't help, it's possible that

You may need to ensure you are in the MoJ Analytical Services team on GitHub.
You may have migrated to a newer version of the platform, so your account on this version is no longer available.
Alternatively, please refer to our guide for getting started on the Analytical Platform for more information.
```

**Comment by ymao2** [comment]
@morotiolutimehin, not sure about the error message you got,  but if you want to login Control panel, you need to be invited into github org `moj-analytical-services`.  If the username of your github account is `morotiolutimehin`, then I couldn't find you in this org, could you following the guide below to check which step you missed?  ( there is step `request-invitation-to-analytical-services-github-organisation` for explaining to how to join the github org)

https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html
