### ISSUE TITLE
Additional installation/different version of Rstudio to allow Quarto rendering of markdown files.

### ISSUE THREAD

**Issue by sheilz81** [ministryofjustice/data-platform-support#117]
### Which tool do you need help with?

RStudio

### What happened?

Can I check whether it would be possible to have additional installations/different versions of RStudio added to the platform please?
The reason I ask is because I've been working on a project which uses quarto markdown files, so to render these files I have downloaded Quarto on to my mac book. I am hoping to publish this work in Aug/Sep but need to make some changes, some colleagues who need to be involved with making these changes do not have a mac book. So I was hoping we could get a different version of RStudio added to the platform that would allow them to render these files. Could you please help in anyway?
https://www.r-bloggers.com/2022/07/how-to-set-up-quarto-with-docker-part-1-static-content/

**Comment by ymao2** [comment]
@sheilz81 it is possible to provide different version rstudio,  but we need to more information about what you actually need.

I had a quick look at the link, we normally don't use the docker image because of a specific tool unless something like IDE like jupyter or rstudio etc.  Do you use the Quato docker image on your local macbook? or you just installed the Quato CLI from https://quarto.org/docs/get-started/,  then use it via rstudio? 

if it is the case,  then we probably can update our existing rstudio docker image with the Quato CLI,  do you have requirement for rstudio version ?  right now the version is rstudio:4.1.2 on AP

**Comment by ymao2** [comment]
> Hiya yes so at the moment I have installed it on my macbook via that website and am accessing via Visual Studio. I have a need for a specific version of RStudio.

you mentioned you have a need for a specific version for rstudio,  which version of rstudio you need ?

**Comment by ymao2** [comment]
in that case, I will give a go sometime next week

**Comment by sheilz81** [comment]
ok great let me and @ThomasHepworth know how it goes.

**Comment by ThomasHepworth** [comment]
@ymao2 if you want any assistance with getting the docker image working, do give me a shout. I'm happy to invest a few hours into this if it would help.

**Comment by ymao2** [comment]
@ThomasHepworth ,  thank you, right now my simple plan is just to install the required package from that website 😄 ,   let us see whether it will work, definitely I will get in touch with you and @sheilz81 for testing

**Comment by ymao2** [comment]
@ThomasHepworth  and @sheilz81  I have built a docker image by following the example from Quaro 
https://github.com/analythium/quarto-docker-examples/blob/main/Dockerfile.base

my PR is below (not sure whether you can see it)
https://github.com/ministryofjustice/analytics-platform-rstudio/pull/126

I had a very simple test on my own namespace, looked ok.   
I was wondering whether you, both, are available today to check whether it meets  your requirement.   I have an appointment morning,  so my response will be slow,  should be ok after 2 pm.   what I will do is to change the docker image on your namespace manually, let you know, then you do the test, give me the update.

**Comment by sheilz81** [comment]
Hiya, happy to do the testing. I've got a meeting now but am free after 11.30 to do some testing.

**Comment by ymao2** [comment]
just realised there is easy way for testing 🤦‍♀️ , and you can choose the time which suits you,  I created a private tool release on the Control panel which is only visible to me, you both,  you just need to choose the `quarto` version from the dropdown list to deploy, then you can test 😄 
<img width="984" alt="Screenshot 2023-06-14 at 12 27 50" src="https://github.com/ministryofjustice/data-platform-support/assets/26111671/fe1e3604-d418-40cd-8f72-e9291eba184f">

so no time restriction, once you get the results, just update here

**Comment by ymao2** [comment]
oh.... I see,  there are more things than I thought,  I need to understand how you use,  we may need to do tunnel like we did for jupyter to forward request to an different port,   could we setup a call then you show me how you use in your local mac? you can check my google calendar (yikang.mao@digital.justice.gov.uk) to find a timeslot ,  thank you

**Comment by ymao2** [comment]
just update,  had a go with @sheilz81 , finally we found a way to work with quarto through rstudio, I am going to make a formal release for new version

**Comment by ymao2** [comment]
I released the new version as below 
<img width="771" alt="Screenshot 2023-06-19 at 14 39 46" src="https://github.com/ministryofjustice/data-platform-support/assets/26111671/f2315693-a28e-4e52-9030-1b0274072d81">
you just need to switch to the new one at anytime.   

I will close this issue :)

**Comment by ThomasHepworth** [comment]
Thank you as always Yikang!

**Comment by sheilz81** [comment]
Thanks so much @ymao2 much appreciated!!
