### ISSUE TITLE
Please make me maintainer of teams that access repos I am the admin of.

### ISSUE THREAD

**Issue by ASolomou** [ministryofjustice/data-platform-support#118]
### What happened?

I am the admin of the following repos. In order to give people access to the repos, I believe I need to be the maintainer of the repo too. Can you please, therefore, make me the maintainer of the following repos? Thanks.

https://github.com/moj-analytical-services/OMSQ-PROBATION-RAP
https://github.com/moj-analytical-services/omsq-probation-data-requests

**Comment by ymao2** [comment]
@ASolomou , could you raise query on operation-engineering slack channel please ?[ask-operations-engineering](https://mojdt.slack.com/archives/C01BUKJSZD4), we don't manage those access any more
