### ISSUE TITLE
Add move s3 file permission to  modernisation-platform-data-eng

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/data-platform-support#119]
### What happened?

I tried to move files from one bucket to another but this failed with Access Denied error. Would it be possible to add the move s3 file permission to the modernisation-platform-data-eng role?

**Comment by julialawrence** [comment]
@SoumayaMauthoorMOJ You might be able to achieve this by removing the bucket policy from the target bucket, doing a copy and then adding the bucket policy back. It's not lack of permissions that is stopping you doing this, it's the bucket policy. You'd encounter the same issue even if you were an admin (ask me how I know :) )

**Comment by SoumayaMauthoorMOJ** [comment]
I tried to move the files using the old restricted-admin role and this passed without any errors. 
Does that mean I should still temporarily remove the bucket policy next time or is there a way of modfying the bucket policy so that it grants the same permissions to modernisation-platform-data-eng? no immediate rush for a solution!

**Comment by julialawrence** [comment]
Because restricted-admin was added as a trusted principal to the bucket policy when it was created. If the policy was managed in code, amending it to add the data-eng role would be trivial but I don't think it is? :(

**Comment by julialawrence** [comment]
@SoumayaMauthoorMOJ If you need any additional assistance with this please reopen,
