### ISSUE TITLE
Please reset my 2FA

### ISSUE THREAD

**Issue by vmohanram** [ministryofjustice/data-platform-support#120]
### Which tool do you need help with?

User and Account

### What happened?

Hi - I forgot my work phone at home (I am in the office today)  which gives me the 2FA auth codes.  Please can you reset my 2FA so I can set it up to work on my personal phone. My GH user name is vmohanram

**Comment by Gary-H9** [comment]
Hello @vmohanram - I've reset your 2FA. 

You should be able to set it up again now. Any issues please re-open the ticket.
