### ISSUE TITLE
Shiny app access to database

### ISSUE THREAD

**Issue by joeprinold** [ministryofjustice/data-platform-support#122]
### Which tool do you need help with?

Database Access

### What happened?

I would like my app (bentham-app) and it's AWS role (alpha_app_bentham-app) to have access to a database (intel) that is stored in the app's bucket (s3://alpha-app-bentham-app/zrefactortest/databases/intel/). This database was built purely though Athena through pydbtools using Presto SQL DDLs and populated with Presto SQL DMLs.

When I add a read_sql command to my R Shiny app (in global.R) to fetch data from this database (intel) then the app no longer builds. I get the following error on build. Note that the app has access to this bucket (s3://alpha-app-bentham-app) and it reads from it, but the database access (or access via Athena) seems to be an issue.

### Relevant log output

```bash
shell: /usr/bin/bash -e {0}
  env:
    AWS_DEFAULT_REGION: eu-west-2
    AWS_REGION: eu-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    APP_ROLE_ARN: ***
    AUTH0_CALLBACK_URL: https://bentham-app-dev.apps.live.cloud-platform.service.justice.gov.uk/callback
    AUTH0_CLIENT_ID: ***
    AUTH0_CLIENT_SECRET: ***
    AUTH0_DOMAIN: alpha-analytics-moj.eu.auth0.com
    AUTH0_PASSWORDLESS: False
    AUTH0_TOKEN_ALG: 
    AUTHENTICATION_REQUIRED: True
    COOKIE_SECRET: 
    ECR_REPO_AUTH0: ***.dkr.ecr.eu-west-2.amazonaws.com/analytical-platform/ap-auth-proxy-prod-ecr
    ECR_REPO_WEBAPP: ***.dkr.ecr.eu-west-2.amazonaws.com/bentham-app-admin-team/***-ecr
    IP_RANGES: ***
    KUBE_NAMESPACE: ***
    NEW_TAG_V: v2.5.1-dev.0
Error: UPGRADE FAILED: context deadline exceeded
Error: Process completed with exit code 1.
```

**Comment by Gary-H9** [comment]
Hi @joeprinold.

We're currently speaking to Data Engineering on how best to facilitate this request. I'll leave this open until we've resolved this.

Apologies for the confusion, thanks, Gary.

**Comment by Gary-H9** [comment]
Closing as per this thread: https://mojdt.slack.com/archives/C8X3PP1TN/p1687250572994119?thread_ts=1686735829.505159&cid=C8X3PP1TN
