### ISSUE TITLE
Seeking copy of a data movement request

### ISSUE THREAD

**Issue by pjooman** [ministryofjustice/data-platform-support#123]
### Which tool do you need help with?

Database Access

### What happened?

I am looking for a data movement request submitted on 3/1/2021 11:30:06 AM for 'Judicial diversity statistics for judges currently in role, and for those joining and leaving the judiciary' and approved by Calum / sent from analytical_platform@digital.justice.gov.uk. Is this something you could dig out for me? I would like to see the terms of the agreement to see if it covers what I am working on rather than having to set up a new agreement.

**Comment by BrianEllwood** [comment]
@pjooman I have been informed that, We do not hold anything over and above the information in the approval email. 
If in doubt, I’d just suggest you complete a new data movement form, not least because the previous approval was following the old process (i.e., not in OneTrust)

**Comment by BrianEllwood** [comment]
@pjooman guidance on https://user-guidance.analytical-platform.service.justice.gov.uk/information-governance.html#data-movements can be found here with links to additional information
