### ISSUE TITLE
Locked out of AP due to 2FA (new phone)

### ISSUE THREAD

**Issue by samhardeman-moj** [ministryofjustice/data-platform-support#124]
### Which tool do you need help with?

User and Account

### What happened?

Hi, I have a new phone which no longer has the Authenticator app installed on it, and I have been asked to complete 2FA to access the AP. Please can someone help me to reset up my 2FA? 

This request is urgent so would appreciate assistance as soon as possible please.

Thanks,
Sam

**Comment by michaeljcollinsuk** [comment]
Hi @samhardeman-moj I've reset your 2FA, please try to login again and you should be prompted to set it up. Any problems please reopen the issue. Thanks

**Comment by michaeljcollinsuk** [comment]
Must have reopened accidentally somehow, sorry
