### ISSUE TITLE
User 'Haziach' unable to log onto the AP

### ISSUE THREAD

**Issue by jessicadaymoj** [ministryofjustice/data-platform-support#125]
### Which tool do you need help with?

User and Account

### What happened?

When trying to log on to the AP, the user reaches the 'There is a problem with your session' screen, resets the session and then tries to log in again, only to end up at the same screen. 
User works in HMPPS and does not have a slack account, so raising the issue on their behalf. Their username is Haziach.

**Comment by jessicadaymoj** [comment]
Hi John - Thank you for resetting the account. Unfortunately, Hazel has tested it and she is still having the same problem.

**Comment by michaeljcollinsuk** [comment]
Hi @jessicadaymoj do you have any update? Could you ask them to try logging in again after first clearing their browser cache (or using a private/incognito window)? Thanks

**Comment by jessicadaymoj** [comment]
Hi @michaeljcollinsuk - I have a catch up wIth Hazel tomorrow, so will ask her to share screen with me in that meeting and try logging in using an incognito window.

**Comment by jessicadaymoj** [comment]
Apologies, unfortunately Hazel is now on Annual Leave until July 10th - I will catch up with her when she gets back and then provide an update.

**Comment by michaeljcollinsuk** [comment]
Thanks for the update @jessicadaymoj. If you dont mind I am going to close the issue for now then, and if you still encounter the issue when your colleague is back, please re-open it  - as that way whoever is covering support that day will be notified
