### ISSUE TITLE
Access to S3 from AP

### ISSUE THREAD

**Issue by paulasoares1** [ministryofjustice/data-platform-support#127]
### Which tool do you need help with?

S3

### What happened?

A new starter who is now set up on GitHub and the Analytical Platform can't access the S3 bucket we have added them too through pydbtools.

Is there anything I need to do to give them further permission? Their GitHub username is garethlomaxds. Thank you.

### Relevant log output

```bash
ClientError: An error occurred (AccessDeniedException) when calling the StartQueryExecution operation: You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again.
```

**Comment by jhackett-ap** [comment]
Hi there!

It looks like your new starter needs Athena permissions. You'd need to ask #ask-data-engineering on slack for that one. Let me know how it goes.

Cheers
John
