### ISSUE TITLE
Brief description of your issue

### ISSUE THREAD

**Issue by alex-pavlopoulos** [ministryofjustice/data-platform-support#128]
### Which tool do you need help with?

Jupyterlabs

### What happened?

I have just found out that a colleague has access to a version of jupyterlabs that has the github extension: [jupyter-lab-datascience-notebook v3.1.14] with Git Ext. I do not have access to this and was wondering how I would go about getting access?

**Comment by jhackett-ap** [comment]
Hi Alex,

It looks like this was a restricted release - I've made it generally available now. It should come up in your available tool versions in the control panel. Let me know if you have any trouble with it.

Cheers
John

**Comment by alex-pavlopoulos** [comment]
Cheers, its working now! Many thanks
