### ISSUE TITLE
Brief description of your issue

### ISSUE THREAD

**Issue by priyapatel8** [ministryofjustice/data-platform-support#129]
### Which tool do you need help with?

GitHub

### What happened?

Hi, yesterday I requested access for username: kings83 to be added standard_database_access. However they have not been added to the main branch usernames list. I am running an SQL session this morning, can you please add her access as soon as you can. Thanks

**Comment by AnthonyCody** [comment]
https://asdslack.slack.com/archives/C1Q0A133Q/p1687335468658559?thread_ts=1687335058.976629&cid=C1Q0A133Q

Data Engineering has picked this up.
