### ISSUE TITLE
Project Access Request Errors

### ISSUE THREAD

**Issue by eleftheriosn** [ministryofjustice/data-platform-support#130]
### Which tool do you need help with?

Database Access

### What happened?

I have made a project access request for my team using the template provided. I requested the data required for our team to function, as we are a team who uses a variety of databases very frequently, often for linking purposes.

Upon committing and requesting a pull, the first attempt came back with errors I fixed, but the second run came with further errors I simply don't get how to fix. 

The requested access and ,yaml file is in the acp-eval-db-access-1, and the pull request is Update acp-eval-db-access.yaml after the first attempt where I tried to fix the errors only for new ones to come up.

If someone could have a look to guide me through or address those errors I would be very grateful.

**Comment by michaeljcollinsuk** [comment]
Hi @eleftheriosn I think this is one for the Data Engineering team - can you add a message (or link to this issue) in the [#ask-data-engineering slack channel](https://mojdt.slack.com/archives/C8X3PP1TN)? Thanks

**Comment by AnthonyCody** [comment]
DE have this. https://mojdt.slack.com/archives/C8X3PP1TN/p1687342715480379?thread_ts=1687342061.203369&cid=C8X3PP1TN
