### ISSUE TITLE
App restart schedule.

### ISSUE THREAD

**Issue by joeprinold** [ministryofjustice/data-platform-support#133]
### Which tool do you need help with?

intel-app-homepage

### What happened?

Is there a way for us to change the restart schedule of an app on the AP ourselves? ...or at least see what it is. intel-app-homepage is the one I'm looking at right now.

### Relevant log output

NA

**Comment by michaeljcollinsuk** [comment]
Hi @joeprinold. It appears that currently `intel-app-homepage` app is set to restart daily at 5:05AM.

Unfortunately we're having some trouble making changes to production applications hosted on the old alpha cluster at the moment. This might change, but in all likelihood the quickest way to get the app restart schedule changed will be to migrate to cloud platform.

After apps have been migrated, you can then define the restart schedule yourself in the github workflow e.g. https://github.com/ministryofjustice/regime-dashboard/blob/main/.github/workflows/build-push-deploy-prod.yml#L161

**Comment by joeprinold** [comment]
Ok thank you. Is it still possible to re-deploy this app though if I have changes?

I have quite an urgent change to make to it. I need to update the link to one of the apps because that app has been migrated and this is the landing page for our users.

**Comment by michaeljcollinsuk** [comment]
Morning Joe, given the circumstances yes can redeploy the app. When your changes are ready please [open an issue here](https://github.com/moj-analytical-services/analytical-platform-applications/issues/new/choose) to request the redeploy. Thanks

**Comment by joeprinold** [comment]
Thanks!
