### ISSUE TITLE
GitHub Org membership

### ISSUE THREAD

**Issue by sjoseph2** [ministryofjustice/data-platform-support#134]
### What happened?

Hi there, on Tuesday I got an email saying that my account was removed from the moj-analytical-services. Could you please restore it back? My username is sjoseph2. I will need to use it soon. Thanks you.

**Comment by ymao2** [comment]
@sjoseph2 , please raise your query on[ #ask-operations-engineering](https://mojdt.slack.com/archives/C01BUKJSZD4) channel, they will solve it for you!
