### ISSUE TITLE
Dash example not working due to flask error

### ISSUE THREAD

**Issue by garethlomaxds** [ministryofjustice/data-platform-support#135]
### Which tool do you need help with?

Control Panel, JupyterLab

### What happened?

I cannot replicate the following: https://user-guidance.analytical-platform.service.justice.gov.uk/appendix/dash.html#example-code I am trying to prototype an internal dashboard. When running the example app.py from the example given I am given the error detailed below. At the end of the attached article it states that the problem may be due to not having access to the right AP instance. It fails on both jupyterlab3113python3.9 git ext and tunnel. 

### Relevant log output

```bash
python3 alpha-cjs-data/eda/app.py 
Traceback (most recent call last):
  File "/home/jovyan/alpha-cjs-data/eda/app.py", line 80, in <module>
    app = dash.Dash(__name__, external_stylesheets=external_stylesheets,url_base_pathname='/_tunnel_/8050/')
  File "/home/jovyan/cjs-timeliness-ml/venv/lib/python3.9/site-packages/dash/dash.py", line 231, in __init__
    self.server.before_first_request(self._setup_server)
AttributeError: 'Flask' object has no attribute 'before_first_request'
```

**Comment by ymao2** [comment]
@garethlomaxds, I think it is due to the newer version of `Flask`, downgrade the Flask to older version, e.g. following one, should work
- `pip uninstall Flask`
- `pip install Flask==2.2.4`

The user-guide need to  be updated, the `dash` version suggested in that page probably becomes outdated

**Comment by ymao2** [comment]
close it as user confirm the issue has been fixed by the above suggestion
