### ISSUE TITLE
I need an IAM Account

### ISSUE THREAD

**Issue by joelstobart-moj** [ministryofjustice/data-platform-support#136]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I need to get an IAM account? I need one that can connect to crd_prod_weekly_stats_export - I've broken some things by moving to an account that is a standard quicksight account...

**Comment by julialawrence** [comment]
Underlying access to resources in QS isn't just controlled by granting QS access to AWS services under Manage Quicksight --> Security & Permissions --> Manage Access to Resources. For some datasets, the user who owns the dataset will also need some addition permissions which are granted via Resource access for individuals and users lower on the same page by clicking IAM Policy Assignments and assigning the user an IAM policy. It's not very intuitive to understand when this needs to be done, but if a user is reporting access issues in QS when QS appears to have access to the correct resources, IAM Policy Assignments is the route to investigate.
