### ISSUE TITLE
Quicksights Account Issue

### ISSUE THREAD

**Issue by jamiemoram** [ministryofjustice/data-platform-support#137]
### What happened?

I was invited to Quicksights and gained access for 7 days before the account reset to show this image: 

![image (2)](https://github.com/ministryofjustice/data-platform-support/assets/21036497/0e03c757-af44-4449-8051-10d3de95eeab)

I am concerned my account reference: 593291632749 is not a member of any teams (aside from the everyone/all-users) and this may be impacting my ability to access Quicksights? I have had my account reset by the Admin and after re-joining it still takes me to this page. 

Any help would be greatly appreciated

**Comment by julialawrence** [comment]
Hi Jamie, I see an invite has been sent to you. Did you receive it?

**Comment by jamiemoram** [comment]
Hi Julia,

I haven't received anything to my knowledge?

Thanks

**Comment by julialawrence** [comment]
@jamiemoram If this is still an issue, can you please reopen or raise another ticket.
