### ISSUE TITLE
I want to delete a repo from my Jupyter Lab

### ISSUE THREAD

**Issue by alex-pavlopoulos** [ministryofjustice/data-platform-support#139]
### Which tool do you need help with?

JupyterLab

### What happened?

I had an issue with a repo that meant I could not pull / push any changes. I ended up trying to delete it, which wasnt possible as you cant delete folders on jupyter that have documents in them. When I then re-cloned the repo it save the new folder in the folder of the old version of that repo (all a bit confusing). Basically I just want to delete the whole folder and start again. All my work is saved on the remote version. 

### Relevant log output

```bash
jovyan@jupyter-lab-datascience-587c7dc7c7-2p6xg:~/cjoe_ccs_comparisons/cjoe_ccs_comparisons$

just an example that I have a repo within a repo now.
```

**Comment by ymao2** [comment]
let me have a look and remove it for you

**Comment by alex-pavlopoulos** [comment]
Thanks, so its the `cjoe_ccs_comparisons` folder from my home directory. Once it has been deleted I can just re clone it. Many thanks!

**Comment by ymao2** [comment]
@alex-pavlopoulos ,  `cjoe_ccs_comparisons` has been removed by me

although I checked the folder permission roughly, you should have permission to remove it even the folder is not empty `rm -rf <folder path>` , but tried to login your pod to remove, failed , there were something which didn't seem right, but anyway I found another way to remove it.  you should be able to reclone it

**Comment by alex-pavlopoulos** [comment]
Great thanks for doing that! I think I tried deleting it in the command line but it then expected me to delete each git file individually. It all got a bit messy, so glad you have sorted it. Many thanks!
