### ISSUE TITLE
add Tom Holt to analytical-platform-iam

### ISSUE THREAD

**Issue by davidbridgwood** [ministryofjustice/data-platform-support#140]
### What happened?

Hey - i've created a couple of PRs in analytical-platform-iam [#700](https://github.com/ministryofjustice/analytical-platform-iam/pull/700) and [#701](https://github.com/ministryofjustice/analytical-platform-iam/pull/701) to add @tomholt1 as a new user and to the relevant team. Could someone to review and help Tom with his first login.

I'm following [these instructions](https://dsdmoj.atlassian.net/wiki/spaces/DE/pages/3862331895/Set+up+AWS+access), let me know if they're out of date and I can update.

**Comment by julialawrence** [comment]
User added to `data-engineering-aws` GH team for access.
