### ISSUE TITLE
Criminal Scenario Tool Dev App

### ISSUE THREAD

**Issue by MattFunnell** [ministryofjustice/data-platform-support#141]
### Which tool do you need help with?

Application Migration Support

### What happened?

Hi - I'm getting a 404 error when trying to access the 'criminal-scenario-tool` dev app (https://criminal-scenario-tool-dev.apps.live.cloud-platform.service.justice.gov.uk/).  

### Relevant log output

```bash
404 error
```

**Comment by jhackett-ap** [comment]
Hi Matt,

It looks like the ingress was deleted - possibly by one of our team while we were looking at something else. Not to worry, I'll get it sorted soonish. This kind of thing won't be routine once things settle, for what it is worth - the less manual intervention there is in the pipeline, the more consistent the result will be!

Thanks
John

**Comment by jhackett-ap** [comment]
This is back up now: upon closer inspection it was actually an issue around one of the previous deploys which was affected by (I believe) a problem with the cloud platform ingress controller - a pretty rare occurrence.



Shout if you need any more help, but for now I'm going to close this thread.

**Comment by MattFunnell** [comment]
Great thanks John!
