### ISSUE TITLE
R Studio - Error occurred during transmission

### ISSUE THREAD

**Issue by jordan-a-carroll** [ministryofjustice/data-platform-support#142]
### Which tool do you need help with?

RStudio

### What happened?

Hi,

When accessing RStudio from the the AP, RStudio attempts to load for a couple of minutes, telling me that its taking longer than usual to start. After a while I then get an error message saying "Could not connect R Session on RStudio Server, Error occurred during transmission (6)". I have tried terminating R, attempting to open it in safe mode, restarting R from the AP tools page and resetting my home directory.

I was able to access RStudio yesterday but then have had this error when trying to access it today. Could you please look into this for me.

Thanks

**Comment by ymao2** [comment]
@jordan-a-carroll ,  let me have a check. I may need to desktop reset for your rstudio

**Comment by ymao2** [comment]
@jordan-a-carroll ,   checked your resource usage, looks like there was very high peak of memory and CPU demand when launching the rstudio,  I guess you may have run some codes requiring lots resources? 

I have reset your rstudio desktop state,  give a try,  you should be able to load the Rstudio (may take a little longer time)
