### ISSUE TITLE
Bucket admin access

### ISSUE THREAD

**Issue by r-mccormack** [ministryofjustice/data-platform-support#143]
### Which tool do you need help with?

S3

### What happened?

Can I be given admin access to the alpha-victims-bill-consultation app bucket, please, as the previous admin has left.

My GitHub username is r-mccormack.

Thanks

**Comment by ymao2** [comment]
@r-mccormack ,  done.   can I remove the preadmin,`Alec Johnson (mralecjohnson)` from control panel?

**Comment by r-mccormack** [comment]
> @r-mccormack , done. can I remove the preadmin,`Alec Johnson (mralecjohnson)` from control panel?

Thanks! Yes, please remove him.
