### ISSUE TITLE
AP security measures

### ISSUE THREAD

**Issue by vonbraunbates** [ministryofjustice/data-platform-support#144]
### What happened?

The data protection team requires the following information about the AP for me to complete a data protection inpact assessment.  (Q5.8 on a "Stage 2 Full DPIA" on OneTrust)

Does the AP have any of the following in place:
- Protection by CCTV / secuity guards / surveillance / smart cards
- Regular review of user access, joiners / movers / leavers
- Staff and third-party awareness of breach notification procedure
- ISO / IEC 27000
- follows the NIST framework
- Cyber Essentials Plus
- Cyber Essential
- SOC 2 certification
- Defence Cyber Protection Partnership

Please contact DataProtection@justice.gov.uk if you need any more information.

### Relevant log output

```bash
None
```

**Comment by ymao2** [comment]
@vonbraunbates ,  please get in touch with `Simon Heron`, our Cyber Security Consultant,  his email `simon.heron@digital.justice.gov.uk`,  he should have the information you need.
