### ISSUE TITLE
Create IAM role for Glue Crawler

### ISSUE THREAD

**Issue by lalithanagarur** [ministryofjustice/data-platform-support#146]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I want to create and run Glue Crawler to export S3 data from s3://alpha-vcms-data to Glue Data Catalog, which requires an IAM role. I get the below error when I try to create an IAM role:
```
We've encountered an error while attempting to create the IAM Role "AWSGlueServiceRole-crawler"
Message from service: "User: arn:aws:sts::593291632749:assumed-role/AWSReservedSSO_modernisation-platform-data-eng_11eb31e568e97345/lalithanagarur@digital.justice.gov.uk is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::593291632749:role/service-role/AWSGlueServiceRole-crawler because no identity-based policy allows the iam:CreateRole action"
```

Once this IAM role is created by the data platform team, I believe I still won't be able to initiate the Glue Crawler due to my MP data engineer role (I will get an error stating that I can't action anything `because no identity-based policy allows ...` . This was the error I got when I tried to create a task to export and RDS snapshot to S3. Please could someone create and run a Glue Crawler with the below details:

![Screenshot 2023-07-05 at 18 09 57](https://github.com/ministryofjustice/data-platform-support/assets/123457715/25f1687a-40d8-4871-882e-aa531c2fa5de)

IAM role: AWSGlueServiceRole-crawler-vcms-data with AWSGlueServiceRole policy and the below policy attached:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::alpha-vcms-data/*"
            ]
        }
    ]
}
```

**Comment by ymao2** [comment]
@lalithanagarur , I just used my account to create a crawler for testing purpose, it worked for me,  but I am not sure I just create one for you based on the above detail 😳 ,  I will ask AP team first on tomorrow SU,   check whether AP team create the crawler on the data engineer's behalf or should we change the permission of data engineer,  will update you once I get the feedback

**Comment by julialawrence** [comment]
Hiya 
Hiya Lalitha
Like KMS keys, iam roles are things you should be defining in code and deploying via github actions. It is not a good practice both in code quality and code security sense to create these kinds of things manually. If you'd like to create a role manually anyway, you have full admin access in the sandbox so you can create it there. :)

**Comment by jacobwoffenden** [comment]
For reference - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_crawler#s3-target-example
