### ISSUE TITLE
Download list of users for a dashboard from AP control panel

### ISSUE THREAD

**Issue by justmiamarjoram** [ministryofjustice/data-platform-support#147]
### Which tool do you need help with?

Auth0

### What happened?

Hello,

My team (DIP) spoke with Julia Lawrence in regards to requesting a download of users for the HMPPS HR dashboard from the AP Control Panel. She suggested we raise a request here.
Is it possible we could have this extract please?

Best regards, Mia

**Comment by LouiseABowler** [comment]
Hi Mia, I've prepared the list of app customers for you. What would be the best way to send it? Also, that information is normally only available for app admins, and I can't see you on the admin list for `hmpps-hr-dashboard`. Could @emmwatson (the only current admin) either add you to the admin list or confirm here that I can send the customer list over?

**Comment by emmwatson** [comment]
@LouiseABowler  - it's also ok to share the list of customers with @sudiptrivedi

**Comment by LouiseABowler** [comment]
Thanks everyone! I have emailed the list over to @sudiptrivedi so I'll mark this issue as resolved now.
