### ISSUE TITLE
App is not whitelisted

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/data-platform-support#148]
We have an issue where, users who use a mac device, are not able to click a link. When they click the link they receive the error below –
error 51.182.252.93 is not whitelisted
The link is - <https://gifts-app.apps.alpha.mojanalytics.xyz/>. On my DOM1 device I am able to click the link fine, it seems to just affect Macs.

[Slack Message](https://mojdt.slack.com/archives/C04M8224WCV/p1688654736146559?thread_ts=1688654736.146559&cid=C04M8224WCV)

**Comment by julialawrence** [comment]
additional range was added to the app vars in the control panel. the break-fix solution was adding the range manually to the cloud platform deployment and then a permanent fix with the updated IP ranges was deployed from the new repository. This currently applies to the migrated version only.
