### ISSUE TITLE
Add external collaborators to a GitHub repository

### ISSUE THREAD

**Issue by sheilz81** [ministryofjustice/data-platform-support#149]
### Which tool do you need help with?

User and Account

### What happened?

Hiya I have a couple of external collaborators that need to be added to a repository on the MoJ github org - is this possible?

**Comment by NickWalt01** [comment]
Hello @sheilz81 yes it is, please fill in this [form](https://github.com/ministryofjustice/github-collaborators/issues/new?assignees=&labels=collaborator%2Cpr-create-issue&projects=&template=create-pr-from-issue.yaml&title=Please+create+an+outside+collaborator%2Fs+pull+request) for the MoJ Org or this [form](https://github.com/moj-analytical-services/github-outside-collaborators/issues/new?assignees=&labels=collaborator%2Cpr-create-issue&projects=&template=create-pr-from-issue.yaml&title=Please+create+an+outside+collaborator%2Fs+pull+request) for the AS Org. FYI: Outside collaborators cannot join a team unless they are made a full org member.
