### ISSUE TITLE
Repo running scripts unreliably

### ISSUE THREAD

**Issue by bethkirby276** [ministryofjustice/data-platform-support#150]
### Which tool do you need help with?

RStudio

### What happened?

Hi,
Myself and a colleague are trying to QA a repo but the script is running unreliably, throwing errors for my colleague that neither of us can reproduce and when sourcing a script it is not running the full script. I have noticed recently on the repo scripts are saved in blob storage that I have not set up and do not understand and also I have received some [Dependabot alerts] which I do nto understand/ recognise so I am wondering if the issues are related. The repo is https://github.com/moj-analytical-services/psychology_services_hr_data
Thanks

**Comment by jacobwoffenden** [comment]
Hey @bethkirby276,

The Dependabot alert have triggered due to vulnerabilities in packages defined within https://github.com/moj-analytical-services/psychology_services_hr_data/blob/main/requirements.txt and their suggestion is to update the package versions.

> the script is running unreliably, throwing errors for my colleague that neither of us can reproduce

Are you able to provide any error messages or screenshots?


> when sourcing a script it is not running the full script

I'm not sure what you mean by this, can you elaborate?

> I have noticed recently on the repo scripts are saved in blob storage

Can you provide more information on this so I can look into it further

Thanks!

**Comment by bethkirby276** [comment]
The Dependabot alert have triggered due to vulnerabilities in packages defined within https://github.com/moj-analytical-services/psychology_services_hr_data/blob/main/requirements.txt and their suggestion is to update the package versions.
I have two alerts are they both about updating packages? 

Are you able to provide any error messages or screenshots?
Thank you, my colleague is going to post details of the errors.

I'm not sure what you mean by this, can you elaborate?
When i click into a script saved on the repo for example leavers.R, the html link indicates a different file location for the script https://github.com/moj-analytical-services/psychology_services_hr_data/blob/main/leavers.R that I am not familar with since I have simply saved the script within the main repo https://github.com/moj-analytical-services/psychology_services_hr_data

**Comment by jacobwoffenden** [comment]
> I have two alerts are they both about updating packages?

Yes, Dependabot opened a pull request to fix, but both were closed

- https://github.com/moj-analytical-services/psychology_services_hr_data/security/dependabot/1
  - https://github.com/moj-analytical-services/psychology_services_hr_data/pull/1
- https://github.com/moj-analytical-services/psychology_services_hr_data/security/dependabot/2
  - https://github.com/moj-analytical-services/psychology_services_hr_data/pull/2

> When i click into a script saved on the repo for example leavers.R, the html link indicates a different file location for the script https://github.com/moj-analytical-services/psychology_services_hr_data/blob/main/leavers.R that I am not familar with since I have simply saved the script within the main repo https://github.com/moj-analytical-services/psychology_services_hr_data

Ah, OK. So this is just how GitHub represents files on the web. The technical details can be found [here](https://docs.github.com/en/rest/git/blobs?apiVersion=2022-11-28#about-git-blobs)
 
If you clone the repository, your file(s) will still be in the path you expect them to be

**Comment by bethkirby276** [comment]
thank you for clarifying
