### ISSUE TITLE
[Feature request] Search for app customers

### ISSUE THREAD

**Issue by glenn-christmas** [ministryofjustice/data-platform-support#151]
### Which tool do you need help with?

Control Panel

### What happened?

Hi, the `gold-scorecard-form` app currently has 18 tabs of customers under the customer management heading. It is time intensive to identify whether someone is on the access list - which we often have to do to troubleshoot when users report they are having access issues. This is currently done by adding their name to the list and seeing if it appears at the end of tab 18 afterwards (if it does, we assume they weren't on the list previously, etc). This can also lead to errors if e.g. there are email typos.

Could a search bar please be added? (Or some means of downloading a CSV to quickly see who is on the list etc?) This would allow us to quickly identify whether someone has access or not. Failing that, would it be possible to revert to the previous approach (as we were easily able to CTRL+F to find email addresses).

Thanks,

Glenn

**Comment by bagg3rs** [comment]
@glenn-christmas 👋 we will add this to our backlog

**Comment by glenn-christmas** [comment]
> @glenn-christmas 👋 we will add this to our backlog

Thanks!
