### ISSUE TITLE
Add ce:CreateReport to AWSReservedSSO_modernisation-platform-data-eng

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/data-platform-support#152]
### Which tool do you need help with?

IAM

### What happened?

Can you please add the `ce:CreateReport` permission to `AWSReservedSSO_modernisation-platform-data-eng` so that we can create cost reports from the console

**Comment by jacobwoffenden** [comment]
Hey @SoumayaMauthoorMOJ,

My initial thought is that access to AWS Billing isn't part of a Data Engineer's job function, I will liaise with the team and get back to you.

**Comment by SoumayaMauthoorMOJ** [comment]
To provide some context, cost reports allows us to understand and hopefully fix anomalous behaviour e.g. S3 costs rocketed in June:
![image](https://github.com/ministryofjustice/data-platform-support/assets/95432492/959c7b9e-c810-4017-9785-e85da8a7e455)
