### ISSUE TITLE
Add data-engineers team to analytical-platform-data-engineering

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/data-platform-support#154]
### Which tool do you need help with?

Github

### What happened?

I have lost maintenance access to https://github.com/ministryofjustice/analytical-platform-data-engineering. I think this is because the data-engineering / data-engineers team was removed? Can you please add data-engineers team as maintainers?

**Comment by julialawrence** [comment]
Hi, I've added data-engineers as an admin for the analytical-platform-data-engineering repository. Can you confirm this has restored your access?

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks @julialawrence I now have admin access on the repo but zenhub is playing up:
![image](https://github.com/ministryofjustice/data-platform-support/assets/95432492/cfbbf151-ea7d-45f7-aa55-d9e600691419)
Any suggestions?

**Comment by SoumayaMauthoorMOJ** [comment]
All sorted now thanks :-)
