### ISSUE TITLE
Urgent dashboard needs to be deployed

### ISSUE THREAD

**Issue by r-mccormack** [ministryofjustice/data-platform-support#156]
### Which tool do you need help with?

RStudio

### What happened?

Hello, what is the situation regarding deployment of new apps at the moment?

We have an RShiny dashboard which urgently needs to be deployed to support the Consultation on the Illegal Migration Bill.

We would hope to deploy a toy version tomorrow followed by updates next week to get the dashboard up to full working order in time for the close of the consultation on the 24th.

What needs to be done to make this happen?

Thanks!

**Comment by julialawrence** [comment]
Actually yes, much easier. Is the new app using the same role/data as the old one?

**Comment by r-mccormack** [comment]
New data, but it will live in a folder in the same bucket. It will have a new list of users, but that is easily arranged. Otherwise it will be essentially the same app, with a few minor updates

**Comment by julialawrence** [comment]
Cool cool cool. We will need some data from you to get started. Can you please fill out this survey? It will still be a bit of a tight squeeze for tomorrow, more likely it'll get finished Monday. Will make things much easier if there's someone we can reach out to on slack when we need you to do something or test something. Do we have a point person we can use for that?
Please fill out all details in this questionnaire as they relate to the new version of the app (please add a note that the old version is being retired.)

**Comment by r-mccormack** [comment]
Thanks Julia! 

Monday will be fine. Our deadline is the end of next week, so if we had something deployed on Monday that is still hopefully enough time to update everything and test.

I am happy to be the point person.

I shall fill that survey out now, thanks!

**Comment by julialawrence** [comment]
Successfully deployed. Closing.
