### ISSUE TITLE
The AP authentication process rejects the codes from my Microsoft Authenticator app

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [ministryofjustice/data-platform-support#158]
### Which tool do you need help with?

Control Panel

### What happened?

I’m using the Microsoft Authenticator app to log into the AP. The AP on my browser takes me to the Google Authenticator window, where I enter the code generated by the Microsoft Authenticator app. I’ve been doing it like this since Sep 2021.

This morning I’m having trouble with authenticating to access the AP using the Microsoft app. It simply won’t accept the authentication codes.

I also use the Microsoft app for GitHub and MoJ Slack and haven't had any problems. This suggests that it isn't an app issue.

Weirdly, though authentication seemingly fails, if I go directly to https://andreassoteriadesmoj-rstudio.tools.analytical-platform.service.justice.gov.uk/, it lets me in.

Some info here:
https://mojdt.slack.com/archives/C0282GUGKL7/p1689317578702789

**Comment by ymao2** [comment]
let me have a look at your login history

**Comment by ymao2** [comment]
hmmm @andreassoteriadesmoj,  couldn't see any error from your login history, and actually it indicates that you have logged in Control panel about an hour ago successfully 

Were you asked to provide the 2fa code when you logged in rstudio?

**Comment by ymao2** [comment]
@andreassoteriadesmoj , just re-checked your login history, looks like you logged in the Control panel a few times, I close this issue
