### ISSUE TITLE
Can't clone project into R on the AP

### ISSUE THREAD

**Issue by KatyScott** [ministryofjustice/data-platform-support#163]
### What happened?

I want to create a new project in R on the Analytical Platform by cloning a project from Git. I can access the project in Git, but when I try to clone it I get an error:

Cloning into 'unitcosting_work'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Do you have any suggestions? I wonder if my AP account/R is/are linked to the right Git account - how can I check that?

### Relevant log output

```bash
Cloning into 'unitcosting_work'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ymao2** [comment]
@KatyScott  have you followed the user-guide below for setting up SSH key?

https://user-guidance.analytical-platform.service.justice.gov.uk/github/set-up-github.html#set-up-github
