### ISSUE TITLE
Cloning git repository to local machine

### ISSUE THREAD

**Issue by aleksploch** [ministryofjustice/data-platform-support#164]
### Which tool do you need help with?

RStudio

### What happened?

I have been trying to follow the instructions on using git on local machines within rstudio using the gert package but I am unable to clone the repository. I have included a PAT within my Renviron and followed the instructions outlined here: https://github.com/moj-analytical-services/git-dom1-demo but I get an error when cloning the directory. Does anyone know of possible solutions to this?

### Relevant log output

```bash
Error in libgit2::git_clone : request failed with status code: 404
```

**Comment by NickWalt01** [comment]
Hello @aleksploch you are not in a team that has access to the repository

**Comment by aleksploch** [comment]
Hi @NickWalt01 thanks seems I figured out this part but now get a new error:

Looking up https credentials for https://github.com/moj-analytical-services/local_test
Error in libgit2::git_clone : request failed with status code: 403

> Hello @aleksploch you are not in a team that has access to the repository

**Comment by aleksploch** [comment]
Of course, no worries. I tried to generate a PAT but I do get the following messages within its info online "This token does not have access to any repositories.". Perhaps this is the issue, that I do not have permission to access any repository with this PAT? I will try to look into how I can change this but if you have ideas for solving this please let me know.

**Comment by NickWalt01** [comment]
You can select the Org repositories you need to access to in the PAT request, assuming you are in a team that has access to the repository

**Comment by ymao2** [comment]
@NickWalt01  and @aleksploch ,   on AP ,  we recommend users to use SSH,  check the user-guide link below 

https://user-guidance.analytical-platform.service.justice.gov.uk/github/set-up-github.html

**Comment by NickWalt01** [comment]
Hello @ymao2, I agree, I assumed @aleksploch has a dom1 machine based on the info provided

**Comment by ymao2** [comment]
@NickWalt01  👍 ,  my intention mainly is for @aleksploch  if he can manage to follow the detailed guide 😊

**Comment by aleksploch** [comment]
Hi both, yes - thank you for your help! I have successfully linked up my PAT with my dom1 machine but now part of our team  have identified problems with admin restrictions when trying to repeat the process. The error message is "The command prompt has been disabled by your administrator". 

![MicrosoftTeams-image](https://github.com/ministryofjustice/data-platform-support/assets/135956897/601d0573-49ef-4d39-ac9a-4bae915f2c8b)

**Comment by julialawrence** [comment]
Hiya as Nick mentioned, you need to be added to `Analysis_and_Performance_HMCTS` team. We can't do that for you but I see a number of maintainers listed for it. I'll DM you the list and you can reach out and ask if one of them might be able to add you.

**Comment by aleksploch** [comment]
Ah thank you @julialawrence , I have added a request to be added earlier today.

**Comment by julialawrence** [comment]
Closing as the issue has been resolved.
