### ISSUE TITLE
Log in emails sent very slowly - preventing user access

### ISSUE THREAD

**Issue by glenn-christmas** [ministryofjustice/data-platform-support#165]
### Which tool do you need help with?

Auth0

### What happened?

When a user attempts to log into one of our analytical platform apps, it can take more than 5 minutes for a link to arrive in their inbox (some are also reporting they are not receiving these links at all - though I suspect they are just considerably delayed). This is preventing users from being able to access our apps.

Please could this be urgently investigated?

**Comment by jacobwoffenden** [comment]
Hi @glenn-christmas,

Which application is this?

Thanks

**Comment by julialawrence** [comment]
This might be auth0 misbehaving. I have seen this before.

**Comment by glenn-christmas** [comment]
Received: from LO2P123MB5862.GBRP123.PROD.OUTLOOK.COM (2603:10a6:600:251::13)
 by CWXP123MB4040.GBRP123.PROD.OUTLOOK.COM with HTTPS; Tue, 18 Jul 2023
 11:39:43 +0000
Received: from AM7PR02CA0013.eurprd02.prod.outlook.com (2603:10a6:20b:100::23)
 by LO2P123MB5862.GBRP123.PROD.OUTLOOK.COM (2603:10a6:600:251::13) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.6609.23; Tue, 18 Jul
 2023 11:39:37 +0000
Received: from AM7EUR03FT055.eop-EUR03.prod.protection.outlook.com
 (2603:10a6:20b:100:cafe::fc) by AM7PR02CA0013.outlook.office365.com
 (2603:10a6:20b:100::23) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.6588.33 via Frontend
 Transport; Tue, 18 Jul 2023 11:39:37 +0000
Authentication-Results: spf=pass (sender IP is 54.240.4.8)
 smtp.mailfrom=eu-west-1.amazonses.com; dkim=pass (signature was verified)
 header.d=amazonses.com;dmarc=fail action=none
 header.from=digital.justice.gov.uk;compauth=softpass reason=202
Received-SPF: Pass (protection.outlook.com: domain of eu-west-1.amazonses.com
 designates 54.240.4.8 as permitted sender) receiver=protection.outlook.com;
 client-ip=54.240.4.8; helo=a4-8.smtp-out.eu-west-1.amazonses.com; pr=C
Received: from a4-8.smtp-out.eu-west-1.amazonses.com (54.240.4.8) by
 AM7EUR03FT055.mail.protection.outlook.com (100.127.141.28) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.6588.33 via Frontend Transport; Tue, 18 Jul 2023 11:39:37 +0000
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=shh3fegwg5fppqsuzphvschd53n6ihuv; d=amazonses.com; t=1689680377;
	h=Content-Type:From:To:Subject:Message-ID:Date:MIME-Version:Feedback-ID;
	bh=whUk7HCr33hcdd/Mkia95lZfC8v76xjm5z2vjbCm9mk=;
	b=SF/jwwdyRiWLKBWIlT2wtl2PTO4KcmHGaV8xxwLb2ObgmOzs/Io5JilxtpGUeoyj
	XbGFIw+VgLYnJqdTEVDvrCdCXwbc/R82z2MTQI7kuuCZcaoXm+KTkrf2UZp4ZmQam0l
	/49asAgYhdI0vtyAe+IbUHBM2XtXOstvOS989AuE=
Content-Type: multipart/alternative;
 boundary="--_NmP-adc6d29cb5e6e97d-Part_1"
From: analytical_platform@digital.justice.gov.uk
To: glenn.christmas@justice.gov.uk
Subject: App sign in - MOJ Analytical Platform
Message-ID: <0102018968cc745a-23088b7d-652a-47dd-8fdf-7fa29f26a328-000000@eu-west-1.amazonses.com>
Date: Tue, 18 Jul 2023 11:39:36 +0000
MIME-Version: 1.0
Feedback-ID: 1.eu-west-1.EcnKM+4y5w3nkd7xAJAqd3so2BEE7jkc0exIQXIspZw=:AmazonSES
X-SES-Outgoing: 2023.07.18-54.240.4.8
Return-Path:
 0102018968cc745a-23088b7d-652a-47dd-8fdf-7fa29f26a328-000000@eu-west-1.amazonses.com
X-MS-Exchange-Organization-ExpirationStartTime: 18 Jul 2023 11:39:37.4898
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id:
 248bdf01-6afb-48b3-226a-08db8783aa8d
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: c6874728-71e6-41fe-a9e1-2e8c36776ad8:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-MS-PublicTrafficType: Email
X-MS-TrafficTypeDiagnostic:
 AM7EUR03FT055:EE_|LO2P123MB5862:EE_|CWXP123MB4040:EE_
X-MS-Exchange-Organization-AuthSource:
 AM7EUR03FT055.eop-EUR03.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Office365-Filtering-Correlation-Id: 248bdf01-6afb-48b3-226a-08db8783aa8d
X-MS-Exchange-AtpMessageProperties: SA|SL
X-MS-Exchange-Organization-SCL: -1
X-Microsoft-Antispam: BCL:0;
X-Forefront-Antispam-Report:
 CIP:54.240.4.8;CTRY:US;LANG:en;SCL:-1;SRV:;IPV:NLI;SFV:SKN;H:a4-8.smtp-out.eu-west-1.amazonses.com;PTR:a4-8.smtp-out.eu-west-1.amazonses.com;CAT:NONE;SFS:;DIR:INB;
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 18 Jul 2023 11:39:37.4273
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 248bdf01-6afb-48b3-226a-08db8783aa8d
X-MS-Exchange-CrossTenant-Id: c6874728-71e6-41fe-a9e1-2e8c36776ad8
X-MS-Exchange-CrossTenant-AuthSource:
 AM7EUR03FT055.eop-EUR03.prod.protection.outlook.com
X-MS-Exchange-CrossTenant-AuthAs: Anonymous
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: LO2P123MB5862
X-MS-Exchange-Transport-EndToEndLatency: 00:00:06.5170400
X-MS-Exchange-Processed-By-BccFoldering: 15.20.6609.017
X-Microsoft-Antispam-Mailbox-Delivery:
	ucf:0;jmr:0;auth:0;dest:I;ENG:(910001)(944506478)(944626604)(920097)(930097);
X-Microsoft-Antispam-Message-Info:
	=?us-ascii?Q?8dcH3eFVr0jPaxP9HeEKIGVBIBppMT3ZxE756NwW4gC+E+2vXrAdLl+nSRR6?=
 =?us-ascii?Q?2fnzr8/2/9WaxNKmhsJp+oDnNDoFQPli9sdmZIz96wdzQDjgXP67WLoVsjvb?=
 =?us-ascii?Q?M3P0JpCHw6gIYDTiBSoDcwJm57AhzJWJKlwDHnna6YLtbO9XQ/cD+5O3EDZA?=
 =?us-ascii?Q?Gg4F9WQbZw/X38kXkXnPaJb7rh/I6JiEi2XBpjoLJwJyZOYr2oPU6V2ptOg8?=
 =?us-ascii?Q?Hw3/9Lsjdl1TQOhMXGZ2rxqUmF9PL7k6jcp/o6Gp7qAS+JYnNkWUZSpaZvH3?=
 =?us-ascii?Q?dSPSRoYmXMFvrxMTjuazYGzlbtcfqK4giIryFc3U7wxEJg/WTlYJz0KT3qX8?=
 =?us-ascii?Q?rhFhWN0rvSQhOJvwgO83erESZcIBrFHoay0MdRAdQzFvVCDuxxQ7xpV9lgEN?=
 =?us-ascii?Q?yv6tu6x8/0H4ey4ZdS1Dtcr/wteELBaEm+JmKbWYFcKcGqsYCFGYNet0ov1D?=
 =?us-ascii?Q?E+52FdtLbX5K2R/FeTQW2C40v57WQkAW4WKzpLp67Bf1hg/pWX58yQCJVjCo?=
 =?us-ascii?Q?ErLTsA9RMGrdocCb3SAxLtuwmhJ5CvQRt+dDsEH6Rw4IrEI0R+3YJuKM/IQp?=
 =?us-ascii?Q?aaL6VHFK8+Scb5+8IJhUDO5ItN4aQGlEW2Q/vId0QpVa9IeLmsgRfC0qfHer?=
 =?us-ascii?Q?SfGen5+pjBuG0+WHHLZyhvqg0IBY4w8Pn+vzZUkYT75nDrjg5P1dWqO5FCnk?=
 =?us-ascii?Q?MAUaoNQp114PVTnJCvnzySw7hi35lQ0ckttJ7/2vVGK2X3NQhwbYMYNlyZEM?=
 =?us-ascii?Q?BOzbfTTx+DFd9tU2pd4Y0kCWOWZF0TkpGH/BOY2Mwym/Y37mPS2KMpv1l9gh?=
 =?us-ascii?Q?ZMgZXA2QG6+hCPsJ3HOO3Amr56S7RbVelabLEP8EpwIuvD6RBRH1ReyJhuhK?=
 =?us-ascii?Q?BcAT9SF+EPoIx+8FKOBPR+IBXfX3oU8ij0yS0VBnkIUBAuNE8zVp4/HjMlzS?=
 =?us-ascii?Q?DcW2CYypKf9MbqNxfcLVMbzW9dOSdljRU9nhL6YekUhovUlB3mCIaAM+bk76?=
 =?us-ascii?Q?c4UxZpm/2mIgLACXycYDINpQBvkh3ICQKtDjT+PGvkaQpkKYqFv3QCmuJqiP?=
 =?us-ascii?Q?k9An4TR/jprJNXxhgUUxyQekoRVcS9aaQTGjdqrLv9GLorY1ypC2p6Up5+tN?=
 =?us-ascii?Q?uwD3PSJmXSSn6KpJ1lDmbjsPI86Xs1TpzHo2lR0x/NuzmLA7wFiwiY86RZ/Z?=
 =?us-ascii?Q?+XOCa9a9uinAOfowS9u8HsfqcUeLKNL+nPOYdg5CE8uWICxUO0Joq8gnoTWU?=
 =?us-ascii?Q?HWrDYepx8l8aWA7L99N284NUaQgOwCGYnSYXU9uw/gO9EA7xMBjI5O/g0r0v?=
 =?us-ascii?Q?N9dgxws2MpvF23xmMOyO79SQfG1MN6KcdFFeiCxzB00QUrrBJd1el9hWVG92?=
 =?us-ascii?Q?CUUDiO03RSY1kW/fQtJt4ViJ0XcLITKnzoTbK2/7knp3hdJ39oNNrvFXzgKT?=
 =?us-ascii?Q?PMrtjPr4V/03NfINMMaKGlKL5kcY4FN4wuJQYO5JjFpYDb6Nv/xQlgUB1X+J?=
 =?us-ascii?Q?b10I0C23vEqXloQyA9+2M9o62px0L/g3NEKZVUJFjjOPjkJhTL5gapABUGF0?=
 =?us-ascii?Q?sruS6Bx8ltm0AI0fYki/lAhCFHZYLB+H4jQ2vz8535RoamwRtbAtTKJBeeFT?=
 =?us-ascii?Q?UJL97DoMVdpZhGdqK1x8klMYvY9llIfkm09yDGvuTxIN/uFnbpVTzf2SEGxE?=
 =?us-ascii?Q?yp0ienkltOOTXRxQYBrhk2Bvxh8=3D?=

**Comment by jacobwoffenden** [comment]
Corresponding Auth0 ID `90020230718113938412812000000000000001223372049136684033`

**Comment by jacobwoffenden** [comment]
Hey @glenn-christmas,

We've tried to reproduce this by sending a request from `gold-scorecard-form-dev`, but it arrives within a minute

This is a hard one to debug because there are so many variables in the path:

User clicks submit -> Auth0 sends email via Amazon SES -> Amazon SES sends mail to Microsoft 365 -> Microsoft 365 processes mail (Safe Link Protection) -> mail arrives in client inbox (Outlook Desktop or Outlook on the web)

Any one of these might've had a delay in processing, and we don't have observability on each component

Outlook desktop _could_ be the culprit here, are you able to test again but using https://outlook.office.com/mail to see if its still delayed

**Comment by glenn-christmas** [comment]
@jacobwoffenden Hi Jacob. I have now tested on the outlook.office.com/mail link and am getting the links almost instantaneously.

**Comment by bagg3rs** [comment]
@glenn-christmas This is then an issue with the desktop Outlook app not refreshing. At a guess (as I have seen this many times with the local cache) It's also possible its an Office or Windows Update or even a policy change to your Windows device. If its still an issue then its worth raising this with the [Technology Portal ](https://mojprod.service-now.com/moj_sp) as its affecting multiple people.

**Comment by bagg3rs** [comment]
You can try toggle off cache mode by Following this [guide](https://support.microsoft.com/en-au/office/turn-on-cached-exchange-mode-7885af08-9a60-4ec3-850a-e221c1ed0c1c) although this maybe set by Administrators so Tech Portal is best place to start.
