### ISSUE TITLE
Unable to login to R studio

### ISSUE THREAD

**Issue by benscott2** [ministryofjustice/data-platform-support#166]
### What happened?

Hi,
I am trying to log into R studio but I can't get through the loading screen. I have the same issue twice in the last couple of days so is there anything you could also do to prevent this happening again please?
Thanks!

**Comment by jhackett-ap** [comment]
Hi Ben,

I think the problem is your MFA - you should have an email to reset it now. Give that a go and let me know if you're still having trouble.

Cheers
John

**Comment by Gary-H9** [comment]
Closing as I believe this is out of date. Please re-open if incorrect.
