### ISSUE TITLE
Cannot launch Jupyter lab

### ISSUE THREAD

**Issue by evincent-moj** [ministryofjustice/data-platform-support#167]
### Which tool do you need help with?

JupyterLab

### What happened?

I can get into the analytical platform control panel but when I try to launch Juypter lab I get the following error:
`state from argument does not match state restored from session`. 

I have tried refreshing and restarting Jupiter first but still getting the same error.

### Relevant log output

```bash
state from argument does not match state restored from session
```

**Comment by julialawrence** [comment]
Could you try the solution advised here? https://github.com/ministryofjustice/data-platform-support/issues/10

**Comment by evincent-moj** [comment]
Yes that's worked - thank you so much!
