### ISSUE TITLE
Allow CP to access Glue Catalog on AP

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/data-platform-support#169]
### Which tool do you need help with?

Amazon Web Services

### What happened?

Hi there -

I need to allow (I think on the Glue Catalog) the Cloud Platform to have permissions to access and use the AP Glue Catalog resources. I have setup everything on the CP end, but need to allow it to access the relevant resources on the AP end now.

See: https://docs.aws.amazon.com/glue/latest/dg/cross-account-access.html

Thanks

**Comment by mshodge** [comment]
Hi @bagg3rs I haven't created a specific role for this yet in the AP. Would the process be:

1. Create a role in AP that can `glue:GetDatabase` on the relevant Glue Catalog database (here: bold_rr_ops_test/mtcars)
2. Then ask AP team to assign that role to the Glue Catalog?

**Comment by julialawrence** [comment]
Hiya, the process would be to create the role and I believe data engineering can add glue access for you.

**Comment by mshodge** [comment]
Thanks @julialawrence showing my inexperience here, especially using the SSO, but how do I go about uploading my created IAM role to the AP AWS? We cannot through the UI anymore.

**Comment by julialawrence** [comment]
Hiya, so you'd like to deploy your role? You've written the policy and you need to create it?

**Comment by mshodge** [comment]
Hi, yes please. I've created the policy using: https://github.com/moj-analytical-services/iam_builder

I need it created on AWS so then I can use data-engineering-database-access to give the relevant glue perms: https://github.com/moj-analytical-services/data-engineering-database-access#adding-app-database-access

Then I need to assign a trust policy (I think) to allow the CP to access the resources (not sure yet how I assign a trust policy).

**Comment by julialawrence** [comment]
@mshodge Please reopen this ticket if this is still an issue.
