### ISSUE TITLE
Pushing to personal repository 

### ISSUE THREAD

**Issue by isobelbochel** [ministryofjustice/data-platform-support#171]
### What happened?

I'm new to GitHub and created a repository for myself (username: isobelbochel). 

I want to push some basic R code to this repository (TestRepo) to try out the processes, however I get an error. 

Could you advise please? 

![image](https://github.com/ministryofjustice/data-platform-support/assets/100926946/a7df5dd1-2772-48a1-8cbd-ed7bf81fee22)

**Comment by julialawrence** [comment]
Hiya, you need to migrate your repository into one of the specified orgs. You can follow the instructions here: https://www.howtogeek.com/devops/how-to-transfer-a-github-repository-to-your-organization-or-another-user/

**Comment by isobelbochel** [comment]
Thanks! Are there any repos which currently exist and can just be used for practise/testing?


[Ministry of Justice]
Isobel Bochel | Principal Statistician
Head of Youth Custody Analysis (YCS)
Data & Analysis
Mobile: TBC
Find out more on People Finder<https://peoplefinder.service.gov.uk/people/robert-crawford>
Follow us on Twitter @MoJGovUK<https://twitter.com/MoJGovUK>
[Protecting and advancing the principles of justice]

**Comment by julialawrence** [comment]
I'm not sure there's a repo in the org that might let you push. Maybe the easiest thing would be for you to create one?

**Comment by isobelbochel** [comment]
No, thank you for your help!


[Ministry of Justice]
Isobel Bochel | Principal Statistician
Head of Youth Custody Analysis (YCS)
Data & Analysis
Mobile: TBC
Find out more on People Finder<https://peoplefinder.service.gov.uk/people/robert-crawford>
Follow us on Twitter @MoJGovUK<https://twitter.com/MoJGovUK>
[Protecting and advancing the principles of justice]
