### ISSUE TITLE
Need access to a repository on Github

### ISSUE THREAD

**Issue by pjrh-moj** [ministryofjustice/data-platform-support#173]
### Which tool do you need help with?

User and Account

### What happened?

I have lost admin rights on the following repository:
[moj-analytical-services/aqa_website](https://github.com/moj-analytical-services/aqa_website)

Please can I (@pjrh-moj) and user @kermathr be added to an administrator team for this repository?

Thanks,
Peter

**Comment by ymao2** [comment]
@pjrh-moj  we don't manage github team any more,  the right place is to raise your query on [#ask-operations-engineering](https://mojdt.slack.com/archives/C01BUKJSZD4)

**Comment by pjrh-moj** [comment]
Thanks - have asked there.
