### ISSUE TITLE
IAM User for UKHSA access to an AP S3 bucket

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/data-platform-support#174]
### Which tool do you need help with?

User and Account

### What happened?

Hi there -

Part of my work on a BOLD project we are exploring ways to give UKHSA/OHID access to a secure S3 bucket. They use WinSCP and it looks like we could give them access by setting up a IAM User (https://winscp.net/eng/docs/guide_amazon_s3).

Would this be possible?

It would be a read-only access so that they can get the data from our end.

Thanks!

**Comment by julialawrence** [comment]
Michael am I misunderstanding or are you looking to create an iam user and hand the credentials for that user to someone outside MOJ?

**Comment by mshodge** [comment]
Hi @julialawrence that's correct.

**Comment by mshodge** [comment]
Hi @jacobwoffenden thanks for the links, would be good if the SFTP server idea can work for both sending and receiving data (as the Essex Police one now needs both sending and receiving data capabilities - originally it was just for us to receive data; and this one needs the ability for us to send data to DHSC only) as we originally scoped it just for receiving data.

**Comment by jacobwoffenden** [comment]
Hey @mshodge! We've got a meeting on Monday to discuss these requests

Will be in touch soon

Cheers

**Comment by julialawrence** [comment]
Need to raise a story for this.
