### ISSUE TITLE
AWS Quicksights Data Permissions

### ISSUE THREAD

**Issue by jamiemoram** [ministryofjustice/data-platform-support#175]
### Which tool do you need help with?

Amazon Web Services

### What happened?

Dashboard in AWS Quicksights is not working. I am an Admin User.

Data views were removed from the database that the dashboard in Quicksight is linked to, these have since been rebuilt but the existing dashboard wont allow me to reset the data 

![image](https://github.com/ministryofjustice/data-platform-support/assets/21036497/015794d9-cb7d-42c0-9e73-e19ceed1cc1d)

I did some troubleshooting and found this link: https://master.d3oeug6bezhkq6.amplifyapp.com/troubleshooting/quicksight-sql-exception.html
but I have tried selecting the 'Security & Permissions' settings and 'Manage' within the 'Quicksight Access to AWS Services' and I get the bellow error in red.

![image](https://github.com/ministryofjustice/data-platform-support/assets/21036497/bf35777e-3380-4a78-9928-861f5d2e0008)

I have even tired importing the data again (which seems to work ok) and attempted to re-build it but every time I drag a field from the data into the dashboard to visualise, I get the Database an SQL Exception error (image attached).

![image](https://github.com/ministryofjustice/data-platform-support/assets/21036497/50fc96fe-ef96-49b6-b15a-daf3d2600471)

I think this might just be a permissions thing?

**Comment by jacobwoffenden** [comment]
Notes:

- Created @jamiemoram as an internal QuickSight user: no joy
- I cannot create a dataset either as an administrator

    ```
    Error details
    region: eu-west-1
    timestamp: 1690374713985
    requestId: 79e959bc-73d2-41f4-a57c-7de22f55a382
    sourceErrorCode: INSUFFICIENT_PERMISSIONS
    sourceErrorMessage: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS 
    Athena client. User: arn:aws:sts::593291632749:assumed-role/aws-quicksight-service-role-v0/QuickSight-RoleSession-1690374713777 is not authorized to perform: athena:ListDataCatalogs because no session policy allows the athena:ListDataCatalogs action [Execution ID not available]
    ```

For future reference, there are some QuickSight docs [here](https://silver-dollop-30c6a355.pages.github.io/search/index.html?q=QuickSight)

**Comment by julialawrence** [comment]
QuickSight permission gremlins have been vanquished. Data restored. Closing.
