### ISSUE TITLE
it's the first time I've tried to get into the AP but I wasn't sent a prompt for setting up the 2factor authentication - so I don't have a code. Could you help me out

### ISSUE THREAD

**Issue by zoewalkerMoJ** [ministryofjustice/data-platform-support#176]
### Which tool do you need help with?

User and Account

### What happened?

it's the first time I've tried to get into the AP but I wasn't sent a prompt for setting up the 2factor authentication - so I don't have a code. Could you help me out

**Comment by jhackett-ap** [comment]
Hi Zoe,

Did you sign in with the same user you've made this report with? I can't find your user in the control panel which is a little bit odd. If not, let me know what username to check with, or have another go at logging in using your zoewalkerMOJ account instead.

Thanks
John

**Comment by michaeljcollinsuk** [comment]
@zoewalkerMoJ can you confirm the link that you are using to log in to control panel is https://controlpanel.services.analytical-platform.service.justice.gov.uk? Can you provide a screenshot of what you see?

**Comment by bagg3rs** [comment]
Continued conversation in slack [here](https://mojdt.slack.com/archives/C4PF7QAJZ/p1692094147950119?thread_ts=1692086283.387809&cid=C4PF7QAJZ)

**Comment by bagg3rs** [comment]
reset of auth0 sent.
