### ISSUE TITLE
External connections blocked?

### ISSUE THREAD

**Issue by r-mccormack** [ministryofjustice/data-platform-support#177]
### Which tool do you need help with?

Application Migration Support, RStudio

### What happened?

I have an app (the newly created imb-consultation-app) which has a feature that allows it to connect to an externally hosted Redis database to store user responses (in a non-sensitive format). 

As you know, we recently picked up an old version of this app to modify it to support a new consultation.

In the old version (last worked on around February last year) I had no problem connecting to the database, but now it doesn't work.

This is the error it gives when running locally. I have not tried deploying it yet, as there is no point until it is working locally.

```
Error in socketConnection(host, port, open = "a+b", blocking = TRUE, timeout = timeout) : 
  cannot open the connection
In addition: Warning message:
In socketConnection(host, port, open = "a+b", blocking = TRUE, timeout = timeout) :
  redis-16606.c269.eu-west-1-3.ec2.cloud.redislabs.com:16606:17968 cannot be opened
```

As you can see the error says blocking = TRUE.

Are you guys now preventing me opening an external connection? If so can this be overridden? Any insight much appreciated!

Thanks

**Comment by r-mccormack** [comment]
If connecting outside the organisation is not acceptable anymore, how about an internal server in AWS?

Would something like in the tutorial below work?

https://aws.amazon.com/getting-started/hands-on/setting-up-a-redis-cluster-with-amazon-elasticache/

Both me locally and the deployed app would need to be able to connect to it.

Let me know what you think.

**Comment by jhackett-ap** [comment]
Just taking a look at what restrictions we have in place vs what we intend to have in place, and seeing if there's a way for me to open this up for you or provide a workaround. 

For the app itself, you should be able to create an elasticache instance in your cloud platform namespace:

https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-imb-fees-consultation-dev/resources

Cloud Platform have a user guide for it here:

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/create.html

Where I'm less clear about this is in the tools cluster. I'll do a bit of digging and work out the best approach.

**Comment by r-mccormack** [comment]
Thanks @jhackett-ap 

That looks promising. Obviously having it working in the deployed version is most important and we could live without it working locally if necessary, though it would make development and testing considerably more difficult, so if we can find a solution that would be great.

Do you know how billing for elasticache works? Could we set this up for free? Our userbase will be very small (~5 people) so we don't need much.

**Comment by jhackett-ap** [comment]
I'm increasingly sure we can set things up so that if you have a dev elasticache instance, we can give you access to it from the tools environment - I think that should get around the issues with access.

In terms of billing, my understanding is that resources deployed via cloud platform will be billed against their account, not yours. Centralised billing is one of the selling points of cloud platform, I believe. They do some reporting on costs too but I can't find the link at the moment - it might be worth asking them about it in #ask-cloud-platform on slack. 

In terms of sizing, the CP user guide does say to try to make economical choices, so I suppose go for the smallest instance and see if that meets your needs first. 

On that note, are you happy to add the terraform as per that guide or do you need a hand?

**Comment by julialawrence** [comment]
Hiya both. `Blocking=TRUE` does not mean we're blocking the connection:

```
blocking: When set to TRUE, this means connection will wait until data is available to read before it continues execution. If set to FALSE, R can continue to do other things while it waits for data.
```

So the good news is, there will be no need for an elasticache instance. The bad news, there needs to be an investigation on the connectivity. The fact that you're not able to connect from your local machine probably means that this isn't something Cloud Platform-related. How is the destination instance configured? Does it have some kind of a security group rule that blocks traffic from anywhere but our tooling cluster?

**Comment by julialawrence** [comment]
Having said that, it would be a pretty good idea to host a dev instance in Cloud Platform regardless rather than routing traffic elsewhere. So worth considering.
