### ISSUE TITLE
Use GitKraken with RStudio on the AP

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [ministryofjustice/data-platform-support#180]
### Which tool do you need help with?

RStudio

### What happened?

Hi, can we use GitKraken (https://www.gitkraken.com/) with RStudio on the AP and, if yes, how can we connect them?

**Comment by ymao2** [comment]
@andreassoteriadesmoj , just briefly checked how to install this client,  tried to install through my rstduio, it failed as it needs certain system library dependency,  so the conclusion is that the current ap rstudio environment cannot support it.  I think probably right now just use the github extension on Rstudio which should cover most what you need for working with github repo, Unless there is urgent reason for using it.

**Comment by andreassoteriadesmoj** [comment]
Thanks for your help @ymao2. Can I ask for clarification please:

>just briefly checked how to install this client, tried to install through my rstduio

What do you mean you tried to install it through RStudio? Do you actually mean that you used the terminal (https://help.gitkraken.com/gitkraken-client/how-to-install/#deb)?

> think probably right now just use the github extension on Rstudio

I use the Git GUI on RStudio all the time. However, it's functionalities are limited and one needs to turn to the command line for more complicated processes (e.g. reverting, moving commits to another branch etc.). GitHub Desktop is also more basic. GitKraken offers a far wider range of functionalities covering more complicated processes.

**Comment by Gary-H9** [comment]
Closing as per response in #181 .
