### ISSUE TITLE
What's the password sudo is asking for?

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [ministryofjustice/data-platform-support#181]
### Which tool do you need help with?

User and Account

### What happened?

Hi,

I tried to install a software (#180), but the terminal on the AP is asking for my password:

>[sudo] password for andreassoteriadesmoj:

Not sure which password it's asking for. I tried my GitHub and RStudio passwords but it doesn't seem to like it.

Any ideas which password is it that it's asking for?

Thank you.

**Comment by Gary-H9** [comment]
Hello @andreassoteriadesmoj. 👋 

Users can install software/packages that do not require administrative access, these will be outwith the scope of the Analytical Platform to support however. 

In the case that a package requires administrative privileges to be installed we cannot provide the credentials for security reasons. 

We will raise a story in our backlog to investigate providing this for users but at first glance, given the licensing implications we think we are unlikely to provide this. 

I'm sorry this is not the answer you were hoping for.

**Comment by andreassoteriadesmoj** [comment]
Makes sense now why the password won't work.

Thanks!
