### ISSUE TITLE
Trying to use MatchingFrontier package

### ISSUE THREAD

**Issue by ib0010** [ministryofjustice/data-platform-support#182]
### Which tool do you need help with?

RStudio

### What happened?

I have installed the packages MatchIt and MatchingFrontier to enable examination of bias/variance trade off from matching approach. MatchIt is native to CRAN, MatchingFrontier is hosted on github. Running example code I am unable to calculate the Frontier, with error suggesting that MatchingFrontier is not able to access MatchIt. The same code/approach works fine on my home computer.

Thanks! 

renv::install("MatchIt")
remotes::install_github("iqss/MatchingFrontier")
library(MatchIt)
library(MatchingFrontier)
data("lalonde", package = "MatchIt")
head(lalonde)

#Estimate the frontier, with default mahalanobis distance
mahal.frontier <- makeFrontier(treat ~ age + educ + race + married +
                                 nodegree + re74 + re75,
                               data = lalonde, 
                               QOI = "FSATT", 
                               metric = "dist",
                               verbose = FALSE)

### Relevant log output

```bash
Error: 'mahalanobis_dist' is not an exported object from 'namespace:MatchIt'
```

**Comment by Gary-H9** [comment]
Hi @ib0010, we understand that this works on your home computer but given the error message, we believe this is an issue with the code itself rather than the platform. We suggest posting in the #r slack channel.
