### ISSUE TITLE
Deployment workflows missing

### ISSUE THREAD

**Issue by r-mccormack** [ministryofjustice/data-platform-support#183]
### Which tool do you need help with?

Application Migration Support

### What happened?

The repo for the imb-consultation-app does not have the CI/CD dev and CI/CD prod workflows in its action menu and there therefore seems to be no way to deploy.

https://github.com/moj-analytical-services/imb-fees-consultation/actions

This app was created in a weird way as it inherited a previous app but was linked to a new repo, so it would never have inherited those workflows from the data platform app template repo. How can I add them?

Thanks!

**Comment by ymao2** [comment]
@r-mccormack , you are working on the wrong repo,  the repo has been migrated into new location,  all the development in the future needs to be in the new repo https://github.com/ministryofjustice/imb-fees-consultation. 
new repo has all those workflow in place. The old repo will be archived soon.  the workflows from old repo for lint have been copied into new repo as well,  but they didn't work, you can remove them if you think they are not useful or not workable

some useful information for managing deployment here
https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#app-deployment

I just checked the github teams on the new repo,  I couldn't find you which means you don't have permission to access or write permission,  you can raise the query  on[ ask-operation-engineer](https://mojdt.slack.com/archives/C01BUKJSZD4) Monday to add you into the admin team

**Comment by r-mccormack** [comment]
Well don't I feel stupid...!

Thanks @ymao2 I shall do that! 

Sorry for bothering you :)

**Comment by ymao2** [comment]
it is easy to get confused especially in the beginning 😅 . 

not all!, you are welcome!
