### ISSUE TITLE
Looking for steps to onboard new services into the AP

### ISSUE THREAD

**Issue by andrewl** [ministryofjustice/data-platform-support#184]
### Which tool do you need help with?

Application Migration Support

### What happened?

Can't immediately see anything signposted in the docs at https://user-guidance.services.alpha.mojanalytics.xyz/get-started.html

**Comment by tom-webber** [comment]
Can you check out the ['Apps' section of the user-guidance documentation](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html)?

We're handling app migration support in the dedicated slack channel [#data-platform-application-migration-support](https://mojdt.slack.com/archives/C0504KY0Z2N) where there's a pinned link to the migration Trello board.

**Comment by julialawrence** [comment]
Hiya @andrewl are you looking to migrate an existing application or create a new one?

**Comment by julialawrence** [comment]
No response, closing.
