### ISSUE TITLE
Which GitHub org to use

### ISSUE THREAD

**Issue by ms130** [ministryofjustice/data-platform-support#185]
### Which tool do you need help with?

User and Account

### What happened?

Hi, which GitHub org should I be using when creating new repos that don't contain an app, e.g. just data analysis, cleaning, etc, `ministryofjustice` or `moj-analytical-services`?

**Comment by julialawrence** [comment]
Might be worth asking ops-eng to see if they have any thoughts.

**Comment by ms130** [comment]
They would probably go for `ministryofjustice`, but they suggested to ask the AP team! Do you know if `moj-analytical-services` is sticking around, or will be retired in favour of `ministryofjustice` only?

**Comment by ymao2** [comment]
@ms130 , had a discussion, we agreed managing one orgs is the better way to go ,  so please choose `ministryofjustice`
