### ISSUE TITLE
Installation of GraphViz library

### ISSUE THREAD

**Issue by simonbutterworth** [ministryofjustice/data-platform-support#188]
### Which tool do you need help with?

JupyterLab

### What happened?

I am trying to call a function in the 'xgboost' package to plot a decision tree. However, it would appear that despite successful installation of the relevant packages, the 'Graphviz' library is not accessible from my environment. The following relevant messages are shown as part of the stack trace:

-> FileNotFoundError: [Errno 2] No such file or directory: PosixPath('dot')
-> ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH

Would it be possible to install the Graphviz library for me? I believe the following command is the way:

sudo apt install graphviz

(source: https://graphviz.org/download/ )

**Comment by simonbutterworth** [comment]
I restarted R but it had no effect. I should note that this is a **Python** package that I am using in **JupyterLab**.

**Comment by tom-webber** [comment]
In the JupyterLab terminal, can you enter:
`conda install -c anaconda python-graphviz`

You'll be prompted as to whether you want to make the suggested changes, which you should review and accept.

After this, you should be able to plot decision trees.

Tested with the following:

```python
from sklearn.datasets import load_iris
from sklearn import tree

clf = tree.DecisionTreeClassifier(random_state=0)
iris = load_iris()
clf = clf.fit(iris.data, iris.target)
tree.plot_tree(clf)
```

**Comment by simonbutterworth** [comment]
Superb - thank you, @tom-webber !
