### ISSUE TITLE
Apparent service outages for AWS UI

### ISSUE THREAD

**Issue by MandarinDuck** [ministryofjustice/data-platform-support#189]
### Which tool do you need help with?

AWS UI

### What happened?

For a few days I have been logged out of AWS intermittently and on attempting re-authentication receive the page below:

>alpha-analytics-moj
>Oops!, something went wrong
>
>There could be a misconfiguration in the system or a service outage. We track these errors automatically, but if the problem persists feel free to contact us.
>Please try again.

Usually I can log in again after some time, but it's quite a long time and so this is proving very disruptive.

### Relevant log output

```bash
invalid_request: the connection was disabled
TRACKING ID: 0b8c8c2f5bd3ba39e4a8
```

**Comment by MandarinDuck** [comment]
Not that particular one, but it's happening today too. I'll take an ID and a timestamp next time.
I have found a fix of sorts which is to re-authenticate on the AP control panel before doing the same on AWS, but it's not great to have to put in two 2FA codes.

**Comment by julialawrence** [comment]
Hiya, do you have another means of authenticating to AWS aside from through the control panel that you're also periodically using?

**Comment by MandarinDuck** [comment]
Yes - [https://alpha-analytics-moj.eu.auth0.com/samlp/NpfImg4P3ynU6HFx7ivYmqUZWQHfwi3Y](https://alpha-analytics-moj.eu.auth0.com/samlp/NpfImg4P3ynU6HFx7ivYmqUZWQHfwi3Y)

**Comment by julialawrence** [comment]
Apologies I just want to make sure I don't misunderstand: are these two separate accounts or the same account you use to authenticate but via 2 different means?

**Comment by MandarinDuck** [comment]
Same account, via this Github user. It's surely the same auth0 process too. The only difference is the URL that prompts the authentication.

**Comment by ymao2** [comment]
@MandarinDuck , we found out there was one trust relationship missing from your alpha_user  role, we added it back, please give another try once you have the chance.

**Comment by MandarinDuck** [comment]
Hello - I had the issue occur again at 13:42 (`TRACKING ID: 4d6335616f74f04a508f`), so it doesn't seem to have resolved it. As always though, verifying via AP first got it to work again.

**Comment by ymao2** [comment]
hmm,  that is very strange 

how you access the aws console ?  which link you use?

normally as I as I know,  users will access the web console page through the control panel  or  use the following link (this link is the same on on control panel with extra parameter to redirect you to the link s3bucket)
https://aws.services.analytical-platform.service.justice.gov.uk/

if you use the first approach, then you will get the session setup , then you won't be asked to re-auth again when accessing the aws console either from cpanel or the link above

if you go for the link directly and the session is expired , you will be asked to re-login again

if you get on aws console link like https://eu-west-1.console.aws.amazon.com/console directly,  it won't work if the session is expired. you have to to use above ways

**Comment by ymao2** [comment]
I seee,  ancient one to me, definitely before I joined this AP, 
yes, please do this new way

**Comment by MandarinDuck** [comment]
It seems to be working better like this. If I have no more issues by the end of the week I'll close the issue.
