### ISSUE TITLE
User Acceptance Testing for hmpps-hr-dashboard.

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/data-platform-support#19]
User Acceptance Testing for hmpps-hr-dashboard.

[Slack Message](https://mojdt.slack.com/archives/C0504KY0Z2N/p1681978896394509?thread_ts=1681978896.394509&cid=C0504KY0Z2N)

**Comment by tom-webber** [comment]
Comments from Emma Watson (app owner):
Issue #1 - None of the charts appear
Issue #2 - Not all of the infoboxes/value boxes appear

**Comment by tom-webber** [comment]
hmpps-hr-dashboard app will resume testing. The original issue (missing content) may have arisen due to trying to access the app during an app restart that we think is due to a memory leak.
