### ISSUE TITLE
AWS console password required from admin

### ISSUE THREAD

**Issue by tomholt1** [ministryofjustice/data-platform-support#192]
### Which tool do you need help with?

Amazon Web Services

### What happened?

Hi, I'm following this page here [Analytical Platform IAM](https://github.com/ministryofjustice/analytical-platform-iam/blob/main/README.md#first-login), specifically `first login` and have not received a password for the AP AWS login. However, I can access AWS through https://moj.awsapps.com/start#/.

**Comment by michaeljcollinsuk** [comment]
Hi @tomholt1 I believe those instructions are out of date, and only SSO should be used to access AWS now via https://moj.awsapps.com/start#/.
