### ISSUE TITLE
S3 bucket admin request

### ISSUE THREAD

**Issue by ms130** [ministryofjustice/data-platform-support#193]
### Which tool do you need help with?

S3

### What happened?

Please could I be made admin of the follow S3 bucket please: alpha-ccd-activities-classification

The owner has left the MoJ and I am currently working on the project which uses data stored there.

Many thanks

**Comment by michaeljcollinsuk** [comment]
Hi @ms130 should I make you an admin so that you can add/remove user access in the future?

**Comment by ms130** [comment]
Yes please

**Comment by michaeljcollinsuk** [comment]
Done, if you need to update users you can do so from this page in the control panel https://controlpanel.services.analytical-platform.service.justice.gov.uk/datasources/748/
