### ISSUE TITLE
Received a query error when re-running code that used to produce outputs

### ISSUE THREAD

**Issue by jdlv500** [ministryofjustice/data-platform-support#194]
### Which tool do you need help with?

JupyterLab

### What happened?

I was running this chunk of code using the same kernel and snapshot date:
```
check1 = pydb.read_sql_query("SELECT year, count(*) as n  FROM fcsq.ca_apps_order_types WHERE year > 2010 and (order_code = 29 OR order_code = 30 OR order_code = 31 OR order_code = 32) group by year order by year")
check1
```
Last week I received outputs, but for some reason whenever I run an SQL query with an athena table in the 'FROM' statement (e.g fcsq.ca_apps_order_types). I receive this error:

`QueryFailed: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: ABVPCWWSZTMEBMJP; S3 Extended Request ID: 3q+AwUo6f8iyzRitSurhaog3Oyf6Gr1usPoepasY36sMaMWTWXtIqPgeUWXXPtCrIdk4EIheqb8=; Proxy: null), S3 Extended Request ID: 3q+AwUo6f8iyzRitSurhaog3Oyf6Gr1usPoepasY36sMaMWTWXtIqPgeUWXXPtCrIdk4EIheqb8= (Bucket: alpha-family-data, Key: CSVs/lookups/ord_type_lookup/app_order_type_lookup.csv). You may need to manually clean the data at location 's3://aws-athena-query-results-593291632749-eu-west-1/tables/1fbe555f-7953-4327-b79a-91864b9bfe5e' before retrying. Athena will not delete data in your account.`

I saw someone had a similar issue 2 months ago and posted in the 'ask-data-engineers' channel (https://asdslack.slack.com/archives/C8X3PP1TN/p1686823719206629), but I don't know whether this problem is still being fixed.

**Comment by ymao2** [comment]
@jdlv500 ,  let me have a look at your role

**Comment by jdlv500** [comment]
Yeah sure thing. I should have read/write access in my team's bucket 'alpha-family-data'.

**Comment by jdlv500** [comment]
Oh wait, it is all working now!

**Comment by ymao2** [comment]
@jdlv500 , I found you have wrong permission for the s3 bucket, I corrected half an hour ago

**Comment by ymao2** [comment]
I think probably that one has fixed your issue 😄 ,  hopefully you wont have this issue again,

**Comment by ymao2** [comment]
I close this query
