### ISSUE TITLE
Cannot check if table exists

### ISSUE THREAD

**Issue by pjrh-moj** [ministryofjustice/data-platform-support#195]
### Which tool do you need help with?

Amazon Web Services

### What happened?

Hi,

There seems to have been a change my Athena permissions, and I can no longer check if tables exist.  This appears to be because I do not have permissions for `athena:GetTableMetadata`.  I used to be able to check if tables existed fine before.

This does not just affect my ability to check for tables, but some other operations too because they can check if the table exists to prevent overwriting it etc.

Can I check if my loss of this permission is deliberate?  And if there is a way of getting it back?

Full error from Athena:
`INFO: AccessDeniedException (HTTP 400). You are not authorized to perform: athena:GetTableMetadata on the resource. After your AWS administrator or you have updated your permissions, please try again.`

**Comment by ymao2** [comment]
@pjrh-moj , AP team is not the team for managing the access to Athena service ( although we are the place for creating the aws role 😊 ), could you raise your query on [data-engineering](https://mojdt.slack.com/archives/CBVUV2613)

**Comment by pjrh-moj** [comment]
Sure - thanks!
