### ISSUE TITLE
Remove FILE_SIZE_LIMIT check in pre-commit hook on AP

### ISSUE THREAD

**Issue by wcerfgba** [ministryofjustice/data-platform-support#196]
### Which tool do you need help with?

RStudio

### What happened?

I am trying to commit a 6.3 MB synthetic data file to a git repository, but the pre-commit hook contains the following check which is preventing me from doing so:

```
FILE_SIZE_LIMIT=5  # In MB
HAS_ERROR=""

for file in $(git diff --cached --name-only | sort | uniq); do
    file_size=$(du --apparent-size -m $(pwd)/$file | awk '{print $1}')
    if [ "$file_size" -ge $FILE_SIZE_LIMIT ]; then
        echo "$file is larger than ${FILE_SIZE_LIMIT}MB."
        HAS_ERROR="1"
    fi
done

if [ "$HAS_ERROR" != "" ]; then
    echo "Can't commit due to oversize files, please unstage before committing." >&2
    exit 1
fi
```

5 MB is not very big and I don't understand why this check is here in the first place.

Due to the permissions on the pre-commit hook script, I'm not able to edit it myself to increase or remove the limit, which is very annoying.

If this is here to discourage accidental uploading of data files, I would suggest additionally testing for common extensions such as `.csv` and `.rds`.

However, in both cases, a flag should be available as an environment variable to enable the user to bypass these restrictions, as there are valid reasons one would want to upload a file greater than 5 MB or a CSV or RDS file.

In my case this is fake, synthetic, test data, which is intended to be used to make our analytical pipeline reproducible, allow us to hold training workshops, and to enable us to write automated tests.

**Comment by ymao2** [comment]
@wcerfgba,  you can use git flag `--no-verify` to skip the pre-commit check, suggest to use git command to make the commit with flag, then you can push to the repo

**Comment by wcerfgba** [comment]
> @wcerfgba, you can use git flag `--no-verify` to skip the pre-commit check, suggest to use git command to make the commit with flag, then you can push to the repo

Oh fab, I'd not come across this flag before! Thanks 🙂
