### ISSUE TITLE
IAM role unable to create new tables in Athena

### ISSUE THREAD

**Issue by vonbraunbates** [ministryofjustice/data-platform-support#197]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I am a data engineer using the IAM role analytical-platform-data-production via SSO.  I am no longer (as of yesterday) allowed to create new tables in Athena due to permission errors.  Example:
```
create table "awsdatacatalog"."delius_prod_dev_dbt"."stg_r_recall_reason"
with (
    table_type='hive',
    is_external=true,
    external_location='s3://mojap-ct-tables/tables/dev/models/database_name=delius_prod_dev_dbt/table_name=stg_r_recall_reason',
    format='parquet'
  )
  as
 select *
 from "awsdatacatalog"."delius_prod"."r_recall_reason"
```
  results in the following error.  I can execute ` select * from "awsdatacatalog"."delius_prod"."r_recall_reason" ` just fine in the same console.

### Relevant log output

```bash
Insufficient permissions to execute the query. User: arn:aws:sts::593291632749:assumed-role/AWSReservedSSO_modernisation-platform-data-eng_11eb31e568e97345/vonbraunbates@digital.justice.gov.uk is not authorized to perform: glue:CreateTable on resource: arn:aws:glue:eu-west-1:593291632749:database/delius_prod_dev_dbt with an explicit deny in a resource-based policy.
```

**Comment by ymao2** [comment]
@vonbraunbates ,  I suspect you may assume the wrong role via sso as the permission from https://github.com/ministryofjustice/modernisation-platform/blob/eeaf72a67a7568994d9485abbc77223fe574d0e5/terraform/environments/bootstrap/delegate-access/policies.tf#L215,   seems `glue:CreateTable`  has been included ( I assume that is permission you need)

Based on the [slack thread ](https://mojdt.slack.com/archives/CBVUV2613/p1681392038079489) you should use `modernisation-platform-data-eng` role, can you check it?

**Comment by vonbraunbates** [comment]
There are two roles called `modernisation-platform-data-eng` in https://moj.awsapps.com/start#/
I am using the second one (`#593291632749`): which one is that terraform file for?

![Screenshot 2023-08-09 at 14-52-44 Amazon Web Services (AWS)](https://github.com/ministryofjustice/data-platform-support/assets/25820816/42db8685-cc1a-42ea-92d0-75d66189d4d6)

**Comment by ymao2** [comment]
I don't know actually,  by looking at your screen,  I think you use the right one ,   since Julie on AL,  let drag @jacobwoffenden in to see whether you can get quick fix,  Jacob,  could you help this one?

**Comment by jacobwoffenden** [comment]
`modernisation-platform-data-eng` is a [permission set](https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html) defined within our AWS organisation ([source](https://github.com/ministryofjustice/aws-root-account/blob/aefbbae11e64b1b14805aacd6718bf01c5cca2fa/management-account/terraform/sso-admin-permission-sets.tf#L157-L163)), which uses the statements defined in the link @ymao2 referenced ([source](https://github.com/ministryofjustice/modernisation-platform/blob/a3f1315d7e6326cfe8c870d538c88491f0bc7239/terraform/environments/bootstrap/delegate-access/policies.tf#L234)) which contains `glue:CreateTable` on `resources = ["*"]`

I've had a look through CloudTrail and I think the event in question is [`42df637d-4ffd-422c-8c80-62fb593650c1`](https://eu-west-1.console.aws.amazon.com/cloudtrail/home?region=eu-west-1#/events/42df637d-4ffd-422c-8c80-62fb593650c1), which has the following error

```json
"errorCode": "AccessDenied",
"errorMessage": "An unknown error occurred"
```

I've found another `CreateTable` event ([`e3053816-49da-464f-b0bc-868d715594a4`](https://eu-west-1.console.aws.amazon.com/cloudtrail/home?region=eu-west-1#/events/e3053816-49da-464f-b0bc-868d715594a4)) targeting `hmpps_pathfinder_prod_dev_dbt`, and that was successful.

Digging further, the Glue catalogue has an explicit deny statement within it's settings ([source](https://eu-west-1.console.aws.amazon.com/glue/home?region=eu-west-1#/v2/security/settings)) (this is mentioned in the actual error message `...with an explicit deny in a resource-based policy.`)

```json
{
    "Sid" : "delius",
    "Effect" : "Deny",
    "Principal" : "*",
    "Action" : [ "glue:UpdateTable", "glue:UpdatePartition", "glue:UpdateDatabase", "glue:DeleteTableVersion", "glue:DeleteTable", "glue:DeletePartition", "glue:DeleteDatabase", "glue:CreateTable", "glue:CreatePartition", "glue:CreateDatabase", "glue:BatchDeleteTableVersion", "glue:BatchDeleteTable", "glue:BatchDeletePartition", "glue:BatchCreatePartition" ],
    "Resource" : [ "arn:aws:glue:eu-west-1:593291632749:table/delius*/*", "arn:aws:glue:eu-west-1:593291632749:database/delius*" ],
    "Condition" : {
      "StringNotLike" : {
        "aws:userId" : [ "REDACTED_LIST" ]
      }
    }
}
```

@vonbraunbates I can't see your user ID within the list, and I also cannot find where this is defined using GitHub Code Search

**Comment by vonbraunbates** [comment]
@jacobwoffenden  does that deny statement simply mean that I can't call any schema or table `delius*` ?
That might explain why I'm also getting this error for a database called `nomis_ao_dev_dbt` if there's a similar policy for NOMIS.
The database names are hard-coded by https://github.com/moj-analytical-services/create-a-derived-table so I'll do some digging tomorrow and see if I can create databases with a different name.

**Comment by jacobwoffenden** [comment]
Yes, @vonbraunbates, there's a statement for NOMIS

```json
{
    "Sid" : "nomis",
    "Effect" : "Deny",
    "Principal" : "*",
    "Action" : [ "glue:UpdateTable", "glue:UpdatePartition", "glue:UpdateDatabase", "glue:DeleteTableVersion", "glue:DeleteTable", "glue:DeletePartition", "glue:DeleteDatabase", "glue:CreateTable", "glue:CreatePartition", "glue:CreateDatabase", "glue:BatchDeleteTableVersion", "glue:BatchDeleteTable", "glue:BatchDeletePartition", "glue:BatchCreatePartition" ],
    "Resource" : [ "arn:aws:glue:eu-west-1:593291632749:table/nomis*/*", "arn:aws:glue:eu-west-1:593291632749:database/nomis*" ],
    "Condition" : {
      "StringNotLike" : {
        "aws:userId" : [ "REDACTED_LIST" ]
      }
    }
}
```

I could manually add your user ID to the lists for Delius and NOMIS, but I'm unsure if there are any requirements regarding user agreements/vetting, or any automation that will correct drift. It has been suggested by @gwionap that this is managed [here](https://github.com/moj-analytical-services/data-engineering-infra/tree/develop#protect-curated-databases-in-glue), but my GPG key hasn't been added to that repo, so I can't verify 😭

**Comment by tom-webber** [comment]
Hi @vonbraunbates - this comes up every now and then, but create and delete statements including database names containing some of the core databases are protected by the [data-engineering-infra repo](https://github.com/moj-analytical-services/data-engineering-infra).

Specifically I believe it's this file: https://github.com/moj-analytical-services/data-engineering-infra/blob/develop/Pulumi.data-engineering-infra-alpha.yaml

It's possible for authorised users to add exceptions, but the likely best solution is to rename tables before you create thrm unless it's critical.
