### ISSUE TITLE
Cannot activate my R Studio 

### ISSUE THREAD

**Issue by TedHuJustice** [ministryofjustice/data-platform-support#198]
### Which tool do you need help with?

RStudio

### What happened?

I cannot activate my R Studio on Analytical Platform and the reset function does not help

**Comment by ymao2** [comment]
@TedHuJustice, I just checked your namespace,  hmm, something is not right, somehow you have a scheduler (the scheduler is the one for activating your idled tool) for juptyer but the tool is rstudio 🤔 

not sure how this happened,  what I can do is to remove the two from your namespace,  then you make a fresh rstudio deployment ?  this way shouldn't affect the files on your environment as they are persisted,  but you may need to reinstall the R packages,  does this sound ok to you?

**Comment by TedHuJustice** [comment]
@ymao2, yes, please. Could you also share detailed step-by-step instructions and relevant links, please?

**Comment by tom-webber** [comment]
@TedHuJustice can you provide an update on this issue after @ymao2's intervention? 
Were you able to redeploy/re-launch RStudio through the control panel?

**Comment by TedHuJustice** [comment]
@tom-webber - Thank you for your message, I tried but it did not solve the problem. Could we arrange a virtual call if possible, please?

**Comment by ymao2** [comment]
@TedHuJustice ( cc @tom-webber ) sorry,  was distracted by other things, Let me clean your  namespace now

**Comment by ymao2** [comment]
@TedHuJustice ,  just found out your namespace has the `rstudio-scheduler` but somehow was scaled down to 0,  I scaled it back,  I think it should solve  your issue,  could you re-open your rstudio and wait for a couple of minutes to see whether the rstudio can be activated ?

**Comment by TedHuJustice** [comment]
@ymao2 @tom-webber : thank you both, but it doesn't seem to help. Could you let me know what to do, pls?

**Comment by TedHuJustice** [comment]
@ymao2 thank you - how is 4pm this afternoon in your diary?

**Comment by ymao2** [comment]
@TedHuJustice, I just tried activating your rstudio through https://tedhujustice-rstudio.tools.analytical-platform.service.justice.gov.uk/ ( I cannot access it of cause),  it works for me,  are you sure you clicked right button ?
<img width="1011" alt="Screenshot 2023-08-14 at 13 07 55" src="https://github.com/ministryofjustice/data-platform-support/assets/26111671/7be13845-571b-4e7f-93cc-832c090728b6">


it is ok to me,  could you send me invite? yikang.mao@digital.justice.gov.uk

**Comment by ymao2** [comment]
close it
