### ISSUE TITLE
Azure Storage Setup

### ISSUE THREAD

**Issue by jamiemoram** [ministryofjustice/data-platform-support#199]
### Which tool do you need help with?

MoJ Cloud Platform

### What happened?

I need to create some Azure storage but my credentials are not permitted. I wondered if someone here may be able to support with this?

**Comment by Gary-H9** [comment]
Hi @jamiemoram I'm afraid we don't deal with Azure generally and more specifically, don't deal with user accounts. I'd suggest first asking whoever provided you the credentials to give you a contact who can help out. I'm sorry I can't be of more use here.
