### ISSUE TITLE
Error Deploying a new version of Shiny App - hmpps-hr-dashboard

### ISSUE THREAD

**Issue by emmwatson** [ministryofjustice/data-platform-support#200]
### What happened?

Hi - I've fixed a bug on the hmpps-hr-dashboard and updated the underlying data.  I'm trying to deploy a new version of the app but I get an error - screenshot below - please could someone help me sort out what the problem is as I'm not sure what this error means. Thanks.

[Screenshot 2023-08-10 115759](https://github.com/ministryofjustice/data-platform-support/assets/78847467/b78d82a2-6212-41d5-a2fb-b88ff4eea222)

**Comment by tom-webber** [comment]
Hi @emmwatson, can you please post this in the [#data-platform-application-migration-support](https://mojdt.slack.com/archives/C0504KY0Z2N) slack channel as it pertains to app migration support?

**Comment by tom-webber** [comment]
Resolved through application support channel. This app was using the previous system for injected secrets from cloud platform and the github actions workflows needed to be updated to reflect the name changes to the secrets. The workflows were also brought up to date with other recent changes.
