### ISSUE TITLE
Github no admin rights

### ISSUE THREAD

**Issue by KristinaGray** [ministryofjustice/data-platform-support#201]
### Which tool do you need help with?

User and Account

### What happened?

Hi all. We have a github repo where 'settings' seem to have disappeared (even for the admin). Please could you add all those with access to the admin group? Thanks. https://github.com/moj-analytical-services/cjoe_ccs_comparisons

**Comment by KristinaGray** [comment]
Yes please!

**Comment by tom-webber** [comment]
Renamed team as per OpsEng request, and assigned as admin.
