### ISSUE TITLE
Delete S3 bucket with read-only access

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [ministryofjustice/data-platform-support#202]
### Which tool do you need help with?

Amazon Web Services

### What happened?

Hi there,

We don't need S3 bucket `alpha-bold-rr-offender-management-analysis` anymore, however the only person with admin access has now left the team. I'm the team G7 and I can confirm that the bucket can now be deleted.

Is there anything else that I need to do or are you going to delete it for us please?

Thanks

**Comment by michaeljcollinsuk** [comment]
@andreassoteriadesmoj I have updated your access level admin for bucket `alpha-bold-rr-offender-management-analysis`, this will allow you to remove the bucket yourself via the control panel via https://controlpanel.services.analytical-platform.service.justice.gov.uk/datasources/1541/

**Comment by andreassoteriadesmoj** [comment]
Thanks. I can confirm that it's worked.
