### ISSUE TITLE
IAM policy change request for cross-account bucket access for Prisoner Money

### ISSUE THREAD

**Issue by ushkarev** [ministryofjustice/data-platform-support#205]
### Which tool do you need help with?

S3

### What happened?

We have a service running on Cloud Platform that puts files into an S3 bucket (`mojap-land`) owned by the analytical platform AWS account. Our IAM role had to change but I stupidly forgot that the IAM policy must be changed in the AP AWS account too!

Old role was
`arn:aws:iam::754256621582:role/money-to-prisoners-prod-api-live`
and this should be changed to
`arn:aws:iam::754256621582:role/cloud-platform-irsa-f18ffa578df06513-live`

I presume this was part of the IAM policy on the `mojap-land` bucket but I don’t know how/where this is managed…

**Comment by ushkarev** [comment]
Seeing as the policy must be reflected on the IAM role I'm using, could you also let me know what the permissions are set to? Presumably _at least_ `s3:PutObject` and `s3:PutObjectAcl` on `arn:aws:s3:::mojap-land/hmpps/prisoner-money/*`?

**Comment by ymao2** [comment]
@ushkarev , had a look at this bucket's permissions you mentioned,  I couldn't find anything like `money-to-prisoners-prod-api-live` ,  found a few permissions link to `754256621582`, but none of them seems relating to the `money`

I did found  a few permissions related `arn:aws:s3:::mojap-land/hmpps/prisoner-money`, basically the permission allowed are `s3:PutObject`,  `s3:ListMultipartUploadParts`

Based on the tags on those buckets , those buckets are managed by the data-engineering team,  not our AP team, and probably your change is not only affect `mojap-land`, there are other buckets names like `mojap-land-preprod` and `mojap-land-dev`..

So sorry again 😊 ( I should have checked before asking you to raise the issue 🤦‍♀️ ), you need to raise this query on [data-engineering slack channel ](https://mojdt.slack.com/archives/CBVUV2613),  but you can provide this ticket for them to check
