### ISSUE TITLE
File not reading in correctly from Athena into RStudio

### ISSUE THREAD

**Issue by kings83** [ministryofjustice/data-platform-support#207]
### Which tool do you need help with?

Athena, RStudio

### What happened?

When I (or other members of my team) read in a csv file from Athena it loses some of the data. The file itself has 2041 rows, and when you read it in the file in R Studio has the same dimensions. But only the first 264 rows have meaningful data. From rows 265-1788 the rows all contain NAs, then from 1789 onwards there is some data but some variables (our ID variable specifically) is not the same as it should be (it changes from Names to random numbers). I have tried reading in the file in chunks, or only a few of the columns and every time, if I try to read in >49 rows, the first 12-16% are fine then after that are NAs or distorted values. I have no issues reading in other larger csv files in the same script, so it doesn't seem to be a memory issue.

**Comment by ymao2** [comment]
@kings83,  remember you 😊 ,  a few more things I want to ask
  - have you tried reading the csv file directly from Athena? 
  - have you tried querying the csv data from AWS Athena query interface directly?
  - Have you tried querying the csv data by using Jupyter tool?
  
and is it possible to pass your code to me I can have a look?

**Comment by kings83** [comment]
Hi ymao2, 

The issue didn't bother me for a while but we're rerunning the analysis with new data and I'm having the issue again (although I have temporarily found a way to read it in in chunks, it's not a permanent solution). 

No I haven't tried any of the above - do you have code for doing them? 

Also, I'm happy to have you look at my code. The code being used to read it in is: (let me know if you want me to send the full code - would I just paste it in here?)

ji_raw <- Rdbtools::read_sql("SELECT * FROM data_eng_uploader_prod_alpha_judicial_modelling.judicial_itineraries_2021_22_v2") %>%
  select(-"extraction_timestamp")

**Comment by ymao2** [comment]
The reasons for doing above 3 are 
- check whether raw csv file can be loaded into rstudio --> if yes,  means  the raw csv file is ok
     the process for doing it  in my mind
     - download the file from s3 bucket,  or you upload the csv file from your local  to Rstudio
     - then use `read_csv = read.csv('./data.csv')`  to read the file, then inspect the data frame to see whether data is ok

- check the data by running Athena Query through AWS web console directly ---> if yes,  means process of uploading the csv through uploader to DP is ok 
    you can get on the aws web console via https://aws.services.analytical-platform.service.justice.gov.uk/
   then search `Athena` and launch the query edit  ---> if you have issue, I can have a go to see whether I have permission to do so
   
- if 1 and 2 are all ok,  then it maybe to do with the R package you use for running this query? then maybe give a go for using alternative R package or another programming language 


so all in all just want to run a few things to check which step went wrong from raw data -> DP -> code. 

from the code you shared,  does look very simple,...  you said you have read the data chunk by chunk, can you share that part code please?

**Comment by kings83** [comment]
When I upload the file directly to RStudio then read it in, it's fine. 

I can also view the file fine in Athena using the Query editor. 

The function I'm using to read it in is the only one I'm aware of to read csv files from Athena to RStudio on the AP but I'll try and find another (do you know any?). It's worth adding that I am using the same function to read in other files from the same area on Athena and having no issues with those files (some of which are larger than this one). I only have an issue with this specific one. 

The code I've used to read the data in chunks is as follows: (although I've recently discovered it doesn't read in all the data, some rows are missing even though the file seems fine) 


ji_rows <- seq(0,2000,by=50)
ji_raw <- data.frame(row_no = integer(),
                     judge_name = character(),
                     judge_type_name = character(),
                     base_loc_type_name = character(),
                     base_loc_name = character(),
                     days_sat = character(),
                     total_sitting_days = character())

for (start_n in ji_rows) {

  if (start_n < 2000) {
      end_n <- start_n + 49
  } else if (start_n == 2000) {
    end_n <- start_n + 43
    }

  ji_temp <- Rdbtools::read_sql(paste0("SELECT ROW_NUMBER() OVER() AS row_no, judge_name, judge_type_name,
                                              base_loc_type_name, base_loc_name, days_sat, total_sitting_days
                                      FROM data_eng_uploader_prod_alpha_judicial_modelling.judicial_itineraries_2021_22_v3
                                      OFFSET ", start_n, "
                                      LIMIT ", end_n - start_n + 1))

  ji_raw <- bind_rows(ji_raw, ji_temp)

}

**Comment by kings83** [comment]
Hi, I have an additional question. Our data agreements specify that we use the AP uploader, however as we are having issues with uploading this dataset in that format do you know if we'd be able to use the method I tested above to formally upload it? As in upload to RStudio directly from my drive, then save to an s3 bucket.

**Comment by kings83** [comment]
@ymao2 - do you know if we're able to use the above method instead of the AP uploader? Our analysis has been held up for over a week due to this data issue, so any advice would be greatly appreciated!

**Comment by julialawrence** [comment]
Hiya, Yikang is on leave for the next few weeks but we are actually unable to advise as to the scope of your data agreement. Potentially a question in ask-data-engineering might have an answer?
