### ISSUE TITLE
Reset phone - need to reset 2FA on AP

### ISSUE THREAD

**Issue by aliceoleary0** [ministryofjustice/data-platform-support#208]
### Which tool do you need help with?

User and Account

### What happened?

Hi there,

I got locked out of my phone and had to reset it/ download Authenticator etc. from scratch.

I now need to re-add the AP to the phones authenticator app (which I guess means resetting 2FA on my AP account).

Please could you help me to do this?

Thanks,
Alice

**Comment by ymao2** [comment]
@aliceoleary0  have done the reset for your 2fa on AP
