### ISSUE TITLE
prisonsreadyreckonerapp access issue

### ISSUE THREAD

**Issue by Eleanor-Rose** [ministryofjustice/data-platform-support#210]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I am using some code which requires access to prisonsreadyreckonerapp bucket on AWS and have been granted access by one of the admins. I can see the bucket in my list of buckets in the warehouse data tab on the AP, but can't access the data inside it. When I try to open the bucket on AWS, I get the following error message: 
Insufficient permissions to list objects
After you or your AWS administrator has updated your permissions to allow the s3:ListBucket action, refresh the page. Learn more about Identity and access management in Amazon S3 
I have been removed and re-added, but this  didn't solve the issue
Thanks!
Ellie

**Comment by ymao2** [comment]
@Eleanor-Rose , sorry for this, there is bug on control pane related to the function of granting the s3bucket access,  let me fix this issue for you 

cc @michaeljcollinsuk

**Comment by ymao2** [comment]
@Eleanor-Rose , your permission has been fixed, should be ok now
