### ISSUE TITLE
Creating new S3 bucket

### ISSUE THREAD

**Issue by paulasoares1** [ministryofjustice/data-platform-support#212]
### Which tool do you need help with?

S3

### What happened?

Hello, I tried to create a new bucket but received the error below. Do I need to request permission to create a bucket?

Also, is there a way to load in data from a SharePoint folder directly to S3?

Thanks in advance!

### Relevant log output

```bash
Failed to create bucket
To create a bucket, the s3:CreateBucket permission is required.
```

**Comment by michaeljcollinsuk** [comment]
Hi @paulasoares1 how did you try to create the S3 bucket? Was it via the AWS console? As you will not have access to create in this way, but you can create a new bucket via the control panel via the [Warehouse Data tab](https://controlpanel.services.analytical-platform.service.justice.gov.uk/warehouse-data/).

**Comment by paulasoares1** [comment]
That worked, thank you!
