### ISSUE TITLE
Access Issue?

### ISSUE THREAD

**Issue by jdsjgu** [ministryofjustice/data-platform-support#213]
### What happened?

Hello,

In attempting to access https://alpha-ppas-wfp.s3.eu-west-1.amazonaws.com/Prison-Staffing-Model/Prison-Level-Data/NOTQAd-raw-pipeline-ts-2023-05-31-w-leavers.rds I encountered the following 'Access Denied' error:

![image](https://github.com/ministryofjustice/data-platform-support/assets/112960276/9dc55f42-f550-48e9-a4b2-a15a7cb25234)

I would be extremely grateful if you could please look into this.

Thanks very much,

Jonathan

**Comment by jdsjgu** [comment]
Hello Michael!  I have recently been granted access (by Weiwei Bendixen) for the first time.

**Comment by michaeljcollinsuk** [comment]
@jdsjgu there was a bug this afternoon when trying to update access to S3 buckets, in order to fix I granted access again. I think this should have resolved the issue, can you check? Thanks

**Comment by jdsjgu** [comment]
I have just checked, and unfortunately I got the same error message

**Comment by michaeljcollinsuk** [comment]
@jdsjgu Could you please try to login to the control panel, click the "datasources" tab, find `alpha-ppas-wfp`, click the "Manage datasource" button and then click "Open on AWS" button, to see if you are able to access the bucket that way? This is the direct link to the page with this button https://controlpanel.services.analytical-platform.service.justice.gov.uk/datasources/
