### ISSUE TITLE
Unable to find resource name for required dataset - not authorised via Glue to access tables in the electronic monitoring service database

### ISSUE THREAD

**Issue by edemirbag** [ministryofjustice/data-platform-support#215]
### Which tool do you need help with?

Amazon Web Services, Control Panel, Database Access, User and Account

### What happened?

I'm currently filling out a database access request (.yaml config file) according to [this](https://github.com/moj-analytical-services/data-engineering-database-access/blob/ff81cf4132444f51b10b00f8d15daecb4ec762dd/README.md#access-to-curated-databases) and [this](https://github.com/moj-analytical-services/data-engineering-database-access/blob/ff81cf4132444f51b10b00f8d15daecb4ec762dd/README.md#submitting-a-database-access-request) process on behalf of our team. This access is needed as part of the Electronic Monitoring (EM) Migration project. We have established that we will require access to the EM RF data which (we think) is in an S3 bucket called s3://electronic-monitoring-service-curated/. We're also likely to need access to all tables in the electronic monitoring service database ("electronic_monitoring_service/full").

In the config file, we are asked to list out each resource (the databases and tables that the project needs access to) and access level we need for our project (see [here](https://github.com/moj-analytical-services/data-engineering-database-access/blob/ff81cf4132444f51b10b00f8d15daecb4ec762dd/README.md#available-resources)), in the form `<database name>/<access level of said database>`.

I am not sure what the exact resource name should be for the EM RF data we need access to in s3://electronic-monitoring-service-curated/ to list it together with "electronic_monitoring_service/full" - possibly something along the lines of "electronic-monitoring-service-curated/em-rf-data/full".

When I try to search for the resource name via the recommended method (https://eu-west-1.console.aws.amazon.com/glue/home?region=eu-west-1#/v2/data-catalog/databases), I get the error message “alpha_user_edemirbag/edemirbag is not authorized to perform: glue:GetDatabases” when trying to access all tables in the electronic monitoring service database.

[Here](https://github.com/moj-analytical-services/data-engineering-database-access/blob/ff81cf4132444f51b10b00f8d15daecb4ec762dd/README.md#available-resources) it says that sensitive tables can usually be requested by name and to find the names of the tables we need, we can ask on the #ask-data-engineering channel on ASD Slack - and when adding these to our config file, to list them as: [db-name]/[table-name].

Could I please have help with fixing my AWS Glue permissions as well as with identifying the name of the dataset we need access to please?

Many thanks,
Emir Demirbag

### Relevant log output

```bash
I get the error message “alpha_user_edemirbag/edemirbag is not authorized to perform: glue:GetDatabases” when trying to access all tables in the electronic monitoring service database via https://eu-west-1.console.aws.amazon.com/glue/home?region=eu-west-1#/v2/data-catalog/databases.
```

**Comment by michaeljcollinsuk** [comment]
Hi @edemirbag this will need support from the data engineering team, can you raise this request in the [#ask-data-engineering slack channel](https://mojdt.slack.com/archives/C8X3PP1TN)? You can link directly to this issue in your message there 🙂. Thanks

**Comment by edemirbag** [comment]
Hi @michaeljcollinsuk, this has been resolved - thanks for your help
