### ISSUE TITLE
[GitHub Actions, R] - Cannot set up linting GitHub action because of package dependencies

### ISSUE THREAD

**Issue by glenn-christmas** [ministryofjustice/data-platform-support#217]
### Which tool do you need help with?

RStudio

### What happened?

Hello, I am struggling to implement linting via GitHub actions. I've tried multiple ways (I've not been able to get Super-Linter working at all, so have tried an alternative approach with the YAML file generated using `usethis::use_github_action("lint-changed-files")`.  Latest run is here: https://github.com/moj-analytical-services/CCMBPT_general/actions/runs/5949560310/job/16135592845.

From reading the error log, I believe this is due to the `testthat` package, which is a dependency of `lintr`. This is really odd because I am able to run an equivalent linting process just fine on a [personal device/repo](https://github.com/GlennChristmas/package_lintr_testing/actions/runs/5907100069/job/16032634346) with essentially the same YAML, DESCRIPTION and NAMESPACE files saved in the repo (DESCRIPTION and NAMESPACE are used as `lintr` seems to need to read these in - it typically is used on R package repos). I can't see anybody discussing this as an issue in the `testthat` github page, so I'm assuming it's not an issue with `testthat` itself. I'm wondering if there is some sort of MoJ security issue that makes downloading `testthat` or its dependencies difficult via GitHub actions? (Again, odd, because these install/load just fine in RStudio.)

I believe this is due to package dependency issues. I have tried:

- Setting the R version loaded in the action to 4.1.2 instead of the latest it defaults to.
- Using any::<insert_package_dependency_here> under `uses: r-lib/actions/setup-r-dependencies@v2` (see the YML file for examples). Even when I provided dependencies of dependencies (e.g. stringi -> testthat -> lintr) it doesn't work.
- I've tried switching caching of packages off `cache-version: false`.

Unfortunately these actions (and combinations of them) either result in the same error, or an error earlier in the run. Is there anything I could change to get this working?

I'm aware of locally-ran Git Hooks as an alternative approach but from digging through MoJ Slack it seems these can vary in performance between Operating Systems, so would like to avoid this if possible.

**Comment by BrianEllwood** [comment]
Hi @glenn-christmas  we have seen this with some of the migrated apps and its around the packages being in the base build , and the fix was to switch the version in the dockerfile to :r4.1-shiny0.0.6

**Comment by glenn-christmas** [comment]
Thanks @BrianEllwood, this repo doesn't have a dockerfile as it's not an application. I assume I could replicate that in the action yaml file itself (i.e. by specifying R version 4.1.0 is used)? I didn't spot anything related to the Rshiny package being an issue previously but I can of course try that (e.g. `any::rshiny`)? Have I understood this correctly?

**Comment by BrianEllwood** [comment]
Hi @glenn-christmas sorry i thought this was a app that was been migrated, as it is not its not really an issue we support. that said (and i'm no expert) it sounds like an issue between unbuntu and the rshiny you are using - I'd check the version you have working locally to see if that rshiny version is different.  You could also try asking in the ask-data-eng slack channel  see if they can help. Cheers Brian

**Comment by tom-webber** [comment]
Hi @glenn-christmas this could be a compatibility issue with the `testthat` library and the ubuntu OS.

[Here is a thread in the `testthat` repo referring to the same error you linked to](https://github.com/r-lib/testthat/issues/1373). This was supposedly resolved a couple of years ago.

This was an issue we faced before, and we fixed by moving to Ubuntu Focal (20.04, referenced in the workflow as`ubuntu-20.04`). That may be worth trying.

**Comment by tom-webber** [comment]
[A more recent iteration of the issue, more relevant as it's building on ubuntu 22.04](https://stackoverflow.com/questions/73355191/issue-installing-package-testthat-r-on-ubuntu-22-04)

**Comment by glenn-christmas** [comment]
Thanks @tom-webber, I will try with a different version of ubuntu.

**Comment by glenn-christmas** [comment]
Hi again @tom-webber. I'm afraid `ubuntu-20.04` [gave me an error ](https://github.com/moj-analytical-services/CCMBPT_general/actions/runs/5951319192/job/16140898220) related to `stringi` which is a dependency of `testthat`. So it's a different error, but it looks like a similar issue. Also checked `ubuntu-18.04` and found that it's no longer supported. I've also tried `windows-latest` and didn't have luck with that, either. Are you aware of any other R projects that use linting as a GitHub action, more than happy to copy/paste from their YAML file if it works.

**Comment by tom-webber** [comment]
Have you tried using Focal? `20.04`?

**Comment by tom-webber** [comment]
This is almost certainly an ubuntu-specific issue with the `testthat` package. 

You might be able to play around with installing the ubuntu package `r-cran-testthat` with a run command
```      - name: Install r-cran-testthat
        run: apt-get update -y && apt-get install -y r-cran-testthat
```
You'll likely have to play around to get this to work, as it's not something we work with.

**Comment by tom-webber** [comment]
Googling that `stringi` error led me to:
https://community.rstudio.com/t/problem-when-publishing-an-app/137096

**Comment by glenn-christmas** [comment]
Looks like 32nd time's the charm https://github.com/moj-analytical-services/CCMBPT_general/actions/runs/5952554806/job/16144780685. Thanks for your support @tom-webber! The fix in the end was https://stackoverflow.com/questions/71696731/fail-to-install-package-rcpparmadillo-on-ubuntu-20-04-r-version-4-1-3 

I.e. I added `sudo add-apt-repository --enable-source --yes "ppa:c2d4u.team/c2d4u4.0+"` to your suggested change above, which seemed to ensure I could install a copy of the `stringi` package that could build properly, and therefore ensure the `testthat` dependency was met for `lintr`.

I'll now investigate how/whether I can cut down the runtime with caching packages etc as the runtime (c.10 minutes) isn't ideal, but will close this issue as it's resolved. Just a quick related question to all of this @tom-webber, I'm aware GitHub says users running actions on non-public repos [have a limited no. of minutes of actions per month before they are charged](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions). However, when I check my usage stats, despite having ran hundreds of minutes of actions in the private `CCMBPT_general` repo over the last few working days, my [usage ](https://github.com/settings/billing ) is still apparently zero minutes. Is this something I need to be wary of?
