### ISSUE TITLE
Admin access to a webapp, as the previous Admins have left the department

### ISSUE THREAD

**Issue by kermathr** [ministryofjustice/data-platform-support#218]
### What happened?

Please could I get admin access to the AQA Website webapp, as the previous admin's have left the department.
I am the admin owner of the repository (https://github.com/orgs/ministryofjustice/teams/aqa-website-admin), and am currently going through the migration process, but need admin access to the webapp on the AP to confirm customer/IP range access.

Happy to provide any further details as necessary and any help you could provide on this would be most appreciated

**Comment by Gary-H9** [comment]
Hi @kermathr, I've assigned you as an Admin to the application in Control Panel. 

Any issues please get in touch.

**Comment by kermathr** [comment]
Thanks! :)
