### ISSUE TITLE
Won't let me log in safety diagnostic tool 

### ISSUE THREAD

**Issue by jonnybliss95** [ministryofjustice/data-platform-support#219]
### Which tool do you need help with?

Auth0, Control Panel

### What happened?

I get to the log in page but it then refuses me to log in saying it is not whitelisted. Could this be resolved please

**Comment by tom-webber** [comment]
Can you post the error? This sounds as though your IP address is not whitelisted. Do you know the access criteria for the app? E.g. you need to be on a specific VPN?

**Comment by jonnybliss95** [comment]
Error
IP 20.26.11.108 is not whitelisted
It keeps saying the above message

**Comment by jonnybliss95** [comment]
Hi,

It’s still saying the same message. Can you fix please

Regards,

Jon

**Comment by jonnybliss95** [comment]
How do I get it to work?

**Comment by michaeljcollinsuk** [comment]
@miller-william @lucypitches as app admins, are you able to confirm this user should be able to access the app?

**Comment by miller-william** [comment]
This is linked to this issue I raised [here](https://github.com/ministryofjustice/data-platform-support/issues/232 ). 

I  think these should be added - it looks like it could be related to the thread here: 
https://mojdt.slack.com/archives/C032BQQHJE5/p1693474501339529

**Comment by michaeljcollinsuk** [comment]
@jonnybliss95 The allowed IP addresses have been updated, so you should now be able to access the app.
