### ISSUE TITLE
How to run background jobs/nohup

### ISSUE THREAD

**Issue by maryboeker** [ministryofjustice/data-platform-support#221]
### Which tool do you need help with?

RStudio

### What happened?

I have a question about how best to run jobs in RStudio that take a long time. I am currently running a script using the nohup command, but it looks like this still uses my working memory, meaning that my RStudio is still blocked up. Is that right? Is there any way that I can run one of these jobs in the background and still be able to use my RStudio as normal?

**Comment by BrianEllwood** [comment]
Hi @maryboeker apparently if you append   a "&" at the end of your nohup command it will run in the background

see link for example [https://www.ibm.com/docs/en/aix/7.2?topic=n-nohup-command](url)

**Comment by maryboeker** [comment]
Thank you! I have now closed all background jobs, cleared the environment, and restarted my RStudio, but for some reason it still indicates that I am using about 80% of my memory. It also keeps crashing and I was only able to start in safe mode. I am not sure if one of the background jobs is secretly still running somewhere or if something else is the problem.

**Comment by BrianEllwood** [comment]
@maryboeker  do not do anything just yet - i will get back to you as soon as i can

**Comment by BrianEllwood** [comment]
@maryboeker can i check this is your production account ?

**Comment by maryboeker** [comment]
Sorry - what is a production account?

**Comment by maryboeker** [comment]
Hm, I am not sure - is there a way I can check?

**Comment by BrianEllwood** [comment]
Hi @maryboeker sorry for the delay i have checked your rstudio on the cluster and can see no issues there, it looks like its time for you to try a reset of your home directory but  I assume you will loose any uncommitted & unpushed changes.

**Comment by maryboeker** [comment]
Is there any way to save these somehow? It won't let me open the file list at the moment, but is there a way to get to my files before resetting so I can copy and paste them?

**Comment by maryboeker** [comment]
It turns out it is possible to get to the files via JupyterLab. However, I have now performed the home directory reset, but my RStudio still starts up in the same state - i.e. with lots of stuff in the memory and not connecting to anything.

**Comment by BrianEllwood** [comment]
Hi 
@maryboeker 
 we have tried reseting your rstudio from the back end can you give it a go and see if its fixed please ?

**Comment by maryboeker** [comment]
It works now!!!! Thank you!!

**Comment by BrianEllwood** [comment]
brilliant sorry it took so long !

**Comment by BrianEllwood** [comment]
note  this fixed this issue 

kubectl exec -ti $RSTUDIO_POD -n $USER_NAMESPACE-c r-studio-server -- sh

mv /home/$USER/.local/share/rstudio /home/$USER/.local/share/rstudio-backup

kubectl rollout restart deployment.apps/$RSTUDIO_DEPLOYMENT -n $USER_NAMESPACE
