### ISSUE TITLE
The new link is not working?

### ISSUE THREAD

**Issue by MickAlston** [ministryofjustice/data-platform-support#222]
### What happened?

The new link is not working.

**Comment by BrianEllwood** [comment]
@MickAlston could you please give some more information about the issue ?

**Comment by MickAlston** [comment]
Morning Brian,

All seems to be working fine now 😊



Kind Regards

Mick Alston

Mick Alston
Senior Prison Custody Officer
House-Blocks 10, 11 & 12
Sodexo Government
HMP Northumberland
Morpeth
Northumberland
NE65 9XG
UNITED KINGDOM
+441670 383288
***@***.******@***.***>
***@***.******@***.***>
sodexo.com<https://www.sodexo.com/fr/home.html>

***@***.******@***.******@***.***[A blue and white logo  Description automatically generated]

[Rainbow Bar]
