### ISSUE TITLE
Requesting access to user created bucket - alpha-criminal-history

### ISSUE THREAD

**Issue by lalithanagarur** [ministryofjustice/data-platform-support#223]
### What happened?

Please could I get read/write access to the user created bucket alpha-criminal-history. 

I have reached out to the admin owner of the bucket but I've not had a response. I need access as I am working on shifting the derived criminal history tables to Create a Derived Table. 

Please let me know if you need any other information. 

Thank you.

**Comment by lalithanagarur** [comment]
Hi Julia, I'm not sure who their LM is, let me see if Michael can help me on this. @mshodge - are you able to help with this?

**Comment by julialawrence** [comment]
Lalitha, I've granted you read/write access on the bucket as approved by Philip H.

**Comment by Gary-H9** [comment]
Closing as per the above.
