### ISSUE TITLE
JupyterLab times out

### ISSUE THREAD

**Issue by ani-setchi** [ministryofjustice/data-platform-support#225]
### Which tool do you need help with?

JupyterLab

### What happened?

I've come back to JupyterLab after a couple of years and I am getting a Server Connection Error every 10 minutes. I've restarted a few times but no improvement. I checked slack and there is a mention of a Flake8 solution but I can't find the option within JupyterLab to self-serve. Could you please help me as it's impacting my work. Github username is ani-setchi. TIA

### Relevant log output

```bash
Server Connection Error A connection to the Jupyter server could not be established. JupyterLab will continue trying to reconnect. Check your network connection or Jupyter server configuration
```

**Comment by michaeljcollinsuk** [comment]
@ani-setchi I've tried taking a look at the logs and usage metrics, and there are some memory spikes, but nothing that seems too unusual.

I found the old support ticket that mentions flake8 - do you see an error message related to flake8 at all? E.g.:
```
jupyterlab-flake8 ran into an issue connecting with the terminal. Please try reloading the browser or re-installing the jupyterlab-flake8 extension
```
If not, I think that might be a different issue, but will look into it.

Have you tried resetting your home directory to see if that helps? Instructions can be found on the [help page in control panel here](https://controlpanel.services.analytical-platform.service.justice.gov.uk/help/). Although this is more commonly used as a fix for Rstudio, it is worth trying in the meantime. And I will come back to this next week to see if I can help further.

**Comment by michaeljcollinsuk** [comment]
Also can I check, does the error kick you out of the jupyter lab entirely (forcing you to re-open from the tools page in control panel https://controlpanel.services.analytical-platform.service.justice.gov.uk/tools/)? Or does it kick you out of the open notebook? If possible, a screenshot of page when you get the error would be useful. Thanks
