### ISSUE TITLE
Request to increase maximum memory on AP for a subset of our team

### ISSUE THREAD

**Issue by edemirbag** [ministryofjustice/data-platform-support#227]
### Which tool do you need help with?

Control Panel, JupyterLab

### What happened?

We've been working on generating synthetic data in python (using the sdv package) within a Jupyter notebook on the analytical platform. We're running into an issue where our execution is terminated, probably due to reaching memory limits. [This page](https://user-guidance.analytical-platform.service.justice.gov.uk/annexes.html#memory-limits) of the AP user guide suggests that admins are open to increasing maximum memory. We’d like to request more, however I wasn’t able to monitor our memory usage using Grafana (https://grafana.services.alpha.mojanalytics.xyz/?orgId=1) as that page in the guide recommends. We’re therefore unsure as to exactly how much of an increase to request and would appreciate some assistance. Cheers

**Comment by edemirbag** [comment]
Hi @tom-webber, yes it was alpha_user_devarrowsmith and alpha_user_kalebsofer.

And it would be helpful if the memory increase could be applied to:
  - alpha_user_kalebsofer
  - alpha_user_staberinde
  - alpha_user_devarrowsmith
  - alpha_user_jazjax
  - alpha_user_edemirbag

Thanks

**Comment by edemirbag** [comment]
Update: on 5/9 @Tom Webber changed the configuration of our JupyterLab instances allocating an initial 24 GiB (from previous 12GiB memory limit) each to kalebsofer, staberinde, devarrowsmith and edemirbag. This should allow us to continue our work on generating synthetic data in this environment. These memory changes are to persist until the changes are reverted, so we (edemirbag, staberinde) have agreed to let Tom W know when the work is complete. It was noted that it’s also possible that using the 'Restart' button in control panel will overwrite these settings. We’ll inform Tom W / the AP admin team if this happens to any of the instances.

**Comment by Gary-H9** [comment]
Closing this issue as it seems to be resolved, if I'm mistaken please re-open.
