### ISSUE TITLE
Unable to see resource usage

### ISSUE THREAD

**Issue by grahamison** [ministryofjustice/data-platform-support#230]
### Which tool do you need help with?

Control Panel

## What happened

On the control panel home page, I click on 

<img width="598" alt="image" src="https://github.com/ministryofjustice/data-platform-support/assets/17812211/eed87409-f902-4278-9e71-9a3f419aff98">

and get taken to a page of blank charts saying "No data"

<img width="1962" alt="image" src="https://github.com/ministryofjustice/data-platform-support/assets/17812211/49a2dac8-890d-45a8-b8ff-e6a5e24146c8">

## What I expected to happen

I expected to see charts showing my resource usage. (I currently want to monitor my JupyterLab usage.)

**Comment by mitchdawson1982** [comment]
Agreed to pick the issue with with Yikang and Michael for discussion.
