### ISSUE TITLE
Brief description of your issue

### ISSUE THREAD

**Issue by Emmadufty** [ministryofjustice/data-platform-support#231]
### What happened?

I cannot access repositories handed over by a colleague (who has since left). The original links (provided by the colleague) now return a 404 error page. I have searched moj-analytical-services for them, but nothing appears. Please could you advise on how I find/access these. The repositories concerned are:

•	https://github.com/moj-analytical-services/case-duration-forecasting
•	https://github.com/moj-analytical-services/crown-trial-explorer 
•	https://github.com/moj-analytical-services/crown-hearings-forecasting
•	https://github.com/moj-analytical-services/crown-flow-explorer
•	https://github.com/moj-analytical-services/crown-timeliness-forecasting
•	https://github.com/moj-analytical-services/crown-plea-forecasting

**Comment by mitchdawson1982** [comment]
I have advised that Emma's line manager is an admin on all of the noted repos and can make the necessary changes for access.
