### ISSUE TITLE
Need to add IP address from private Serco managed prison to the safety-diagnostic-tool app IP allow list

### ISSUE THREAD

**Issue by miller-william** [ministryofjustice/data-platform-support#232]
### Which tool do you need help with?

Control Panel

### What happened?

We've been contacted by a user in HMP Dovegate who is unable to access the `safety-diagnostic-tool` application. This is a Serco managed private prison. Their IP address: `217.22.14.151` is not an option to allow on the AP app page.

**Comment by mitchdawson1982** [comment]
Looking into this.

**Comment by michaeljcollinsuk** [comment]
@miller-william I have added a new IP allowlist labelled "HMP Dovegate" with the above IP address. [I saw your message on the related issue](https://github.com/ministryofjustice/data-platform-support/issues/219), do you want me to add the following IP addresses to the same allowlist?
```
20.26.11.71/32
20.26.11.108/32
```

**Comment by miller-william** [comment]
Yes, based on this [slack thread](https://mojdt.slack.com/archives/C032BQQHJE5/p1693474501339529), I think that makes sense. They are addresses for prison sites and we want all prison sites to have access to this app.

**Comment by michaeljcollinsuk** [comment]
Ok I've added all three IP's now. You should now be able to select this allowlist via the "manage app" page in control panel. The app will need to redeployed for the changes to come into effect.

**Comment by michaeljcollinsuk** [comment]
@miller-william have you updated the allowlists for the app?

**Comment by miller-william** [comment]
Yes I have - thank you.

**Comment by michaeljcollinsuk** [comment]
@miller-william Thanks, I've updated the IP allowlists for the old app in the alpha cluster at https://safety-diagnostic-tool.apps.alpha.mojanalytics.xyz/. For it to be applied in the new app (at https://safety-diagnostic-tool-dev.apps.live.cloud-platform.service.justice.gov.uk/) you will need to trigger a redeploy as mentioned above, if you have not done so already.

**Comment by miller-william** [comment]
@michaeljcollinsuk  I'm struggling to re-deploy the new app. Guidance says:

> Deploying your application to your production environment is done through the -prod workflow, which will build-push-deploy either:
> 
> after a pull request is merged into main
> upon publishing a release

But I've published a new release and it fails https://github.com/ministryofjustice/safety-diagnostic-tool/actions/runs/6156743815

What's the correct way to trigger a redeployment when I don't have any code changes?

**Comment by michaeljcollinsuk** [comment]
@miller-william my apologies, the user guidance is incorrect and needs updating, creating a new release will not trigger a redeploy.

To redeploy prod without pushing any new changes, you can find the most recent successful deployment from the main branch, and click the `re-run all jobs` button - so in this case this one https://github.com/ministryofjustice/safety-diagnostic-tool/actions/runs/6107960355

**Comment by miller-william** [comment]
Thank you - that has worked.
