### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Ringham1** [ministryofjustice/data-platform-support#235]
### What happened?

I am attempting to log in to the Safety Diagnostic Tool and, I am getting the below message

IP 20.26.11.71 is not whitelisted
The app has been gated by the IP_RANGES setting, your IP address is not within this allow list. If this is not what you expected, please contact an app admin to check the existing IP_RANGES setting on the app-detail page through Control panel.
The app admin can add/remove the IP_RANGES on Control panel. Any new changes related to this setting won't be applied to deployment environments automatically, they will be taken into effect from the next deployment.
If you couldn't get in touch with an app admin, alternatively raise a [Analytical Platform Support Request](https://github.com/ministryofjustice/data-platform-support/issues/new/choose).

**Comment by mitchdawson1982** [comment]
Hi, can you share the url that you are using please? This should be working on the new application url's.

**Comment by Ringham1** [comment]
Good afternoon,

Below is the link that I am using

https://safety-diagnostic-tool.apps.live.cloud-platform.service.justice.gov.uk/

Many thanks

Robyn Ingham
Safer Custody Analyst
HMP Lowdham Grange
Lowdham
Nottingham
NG14 7DA

01159669264
***@***.******@***.***>

**Comment by mitchdawson1982** [comment]
Hi, The redeployment of the application was completed successfully yesterday. Have you been able to retest since then ?

**Comment by Ringham1** [comment]
Morning,

Yes thankfully I am.

Many thanks for your help

Robyn Ingham
Safer Custody Analyst
HMP Lowdham Grange
Lowdham
Nottingham
NG14 7DA

01159669264
***@***.******@***.***>
