### ISSUE TITLE
R Studio not opening

### ISSUE THREAD

**Issue by maryboeker** [ministryofjustice/data-platform-support#236]
### Which tool do you need help with?

RStudio

### What happened?

My RStudio has stopped working again (I had requested support on this last week, and it was a memory issue, and the pod was reset, which made it work again). I am now having the same issue as I had before - a blank screen after I enter my TFA.

**Comment by mitchdawson1982** [comment]
Currently reviewing the last resolution for this issue. Perhaps an increase in memory is required.

**Comment by maryboeker** [comment]
Thank you, I can open it up again now!
