### ISSUE TITLE
App incorrectly flagged as shutdown

### ISSUE THREAD

**Issue by chrisbanbury** [ministryofjustice/data-platform-support#237]
### Which tool do you need help with?

Application Migration Support

### What happened?

I signed off UAT for an app but it isn't being redirected to the new URL, instead it's showing the 'Application Shutdown' message.  Please can this be set to redirect instead? The URL is https://matrixbooking.apps.alpha.mojanalytics.xyz/ but the github name is matrix-booking: https://github.com/ministryofjustice/matrix-booking/

**Comment by julialawrence** [comment]
Apologies and thanks for flagging it. We've amended the redirect. Can you give it 2 minutes and try again please?

**Comment by chrisbanbury** [comment]
Works now, thanks
