### ISSUE TITLE
Process to enable 2FA on `bold-case-info-dashboard`

### ISSUE THREAD

**Issue by wmartin-gss** [ministryofjustice/data-platform-support#238]
### Which tool do you need help with?

MoJ Cloud Platform

### What happened?

I've been asked by cybersecurity how involved the process of adding 2FA via the auth proxy image is? Our app (`bold-case-info-dashboard`) uses the auth proxy image with an HMPPS Auth backend

**Comment by ymao2** [comment]
@wmartin-gss, the auth-proxy is only proxy for different authentication flows and does't have such feature, probably won't have the plan for this feature.  but it may be achievable via Auth0 as we have one setup for another app,  we will have discussion around it tomorrow

**Comment by wmartin-gss** [comment]
Thanks for your reply @ymao2; I asked the HMPPS Auth team in parallel and they've been able to enable 2FA for us on their end, so don't worry about an answer for this.
