### ISSUE TITLE
Question about app logs

### ISSUE THREAD

**Issue by wmartin-gss** [ministryofjustice/data-platform-support#239]
### Which tool do you need help with?

MoJ Cloud Platform

### What happened?

Another question from cybersecurity: are the app logs (i.e. the output from stdout/stderr of our app) stored in a place that is read-only once they are written? Are there any checks (e.g. hashing) to ensure the integrity of these log files?

**Comment by wmartin-gss** [comment]
@ministryofjustice/data-platform Just wanted to ask if I could have an estimate for how long my question might take to be answered please? We're waiting on Cybersecurity sign-off before rolling out our app, so it would be helpful to have an accurate estimate of how long we can expect to wait for answers to propagate on to our operational delivery board

**Comment by julialawrence** [comment]
Apologies for the delay. We do not manage logs on applications hosted on Cloud Platform. Would you be able to pose your question in #ask-cloud-platform instead please?

**Comment by Gary-H9** [comment]
Closing ticket
