### ISSUE TITLE
Re-activating external access to the Platform

### ISSUE THREAD

**Issue by dami-moj** [ministryofjustice/data-platform-support#242]
### Which tool do you need help with?

User and Account

### What happened?

As part of a data-sharing project, External associates with username - mjchalkley , pauldmartyn,  didartls  and steveking358 were granted access to the AP, which was due for a review on the 31st of August, 2023. 
Can you help re-instate their access. Thanks

**Comment by bagg3rs** [comment]
👋 @dami-moj All users except for `mjchalkley` who is still part of https://github.com/moj-analytical-services will need to request access to the AS GitHub Org via slack [#ask-operations-engineering](https://moj.enterprise.slack.com/archives/C01BUKJSZD4). You can request on behalf of all of them at the same time if you would like. 

e.g. 
> Afternoon could I please be added to the Analytical Services GitHub Org, my github name is `github user name` thank you.

Further getting started guidance can be found [here](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#3-create-github-account)

**Comment by bagg3rs** [comment]
Could we get a screenshot or error message? clicking on https://alpha-analytics-moj.eu.auth0.com/v2/logout sometimes helps with browser issues.

There is some common errors and solutions [here](https://user-guidance.analytical-platform.service.justice.gov.uk/errors.html#too-many-redirects-error-in-browser)

**Comment by dami-moj** [comment]
@moj-data-platform-robot Hi, can anyone help with this issue, Richard was previously on it but now away.

**Comment by bagg3rs** [comment]
I am back today @dami-moj 
Can you post a screenshot of the error that mjchalkley gets?

**Comment by dami-moj** [comment]
![AP error page](https://github.com/ministryofjustice/data-platform-support/assets/111752353/72d508f4-5c32-4543-bac7-90229b8c3700)
Awesome. Thanks for taking this up. mjchalkley and pauldmartyn are having this error page. GitHub 2FA settings are in place.

**Comment by bagg3rs** [comment]
Users added to AS org
Any issues try to clear session by using https://alpha-analytics-moj.eu.auth0.com/v2/logout and then logging back in.

**Comment by bagg3rs** [comment]
confirm with @dami-moj that we can close issue
