### ISSUE TITLE
Removal of access to many s3 buckets

### ISSUE THREAD

**Issue by robert-g-green** [ministryofjustice/data-platform-support#243]
### Which tool do you need help with?

S3

### What happened?

Hi, my user account (robert-g-green) has access to several buckets that I no longer require access to. Please could I be removed from these:
alpha-accommodation-employment-data
alpha-covid-19-prisons-rap
alpha-covid-19-recurring-reports
alpha-cpt-stats-publication
alpha-data-update-and-dashboards
alpha-hmpps-covid-data-processing
alpha-hmpps-workforce-stats
alpha-probation-equalities-monitoring-tool-data-wrangling
alpha-probation-service-performance-data

**Comment by bagg3rs** [comment]
@robert-g-green you can manage access to buckets via the [Control Panel](https://controlpanel.services.analytical-platform.service.justice.gov.uk/datasource-access) 
See our guidance [here](https://user-guidance.analytical-platform.service.justice.gov.uk/data/amazon-s3/#manage-access-to-a-bucket)

**Comment by robert-g-green** [comment]
@bagg3rs this is only possible for buckets that you are admin for. The list I have provided are ones I am not admin of, and several of which the admin has left. Do you have the ability to do a bulk access removal?

**Comment by bagg3rs** [comment]
@robert-g-green I see I can remove you in that case.

**Comment by bagg3rs** [comment]
@robert-g-green these should all be removed now.

**Comment by robert-g-green** [comment]
Thanks @bagg3rs
