### ISSUE TITLE
GitHub repo admin request

### ISSUE THREAD

**Issue by ms130** [ministryofjustice/data-platform-support#244]
### Which tool do you need help with?

User and Account

### What happened?

Hi, please could I be made admin of the following repo please, the owner has since left:

moj-analytical-services/ccd-activities-classification-setup-eval

Thanks

**Comment by mitchdawson1982** [comment]
Hi, Could you re raise this issue via the #ask-operations-engineering slack channel as they deal with these types of requests,
Many Thanks
