### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by raustin18** [ministryofjustice/data-platform-support#246]
### Which tool do you need help with?

Control Panel

### What happened?

![Capture1](https://github.com/ministryofjustice/data-platform-support/assets/143815163/cb75c706-cd31-426b-bf34-fedc28865019)

I am trying to log onto the control panel for the first time so that I can download R studio, but every time I try I can never get past the github logins. I manage put my username and password in and then put my authentication code in and just as it looks like it is loading this screen appears. I'm not sure what to do now.

**Comment by Gary-H9** [comment]
Hi @raustin18 have you tried clicking on the "reset your session" hyperlink in that page (referring to the image you've included)?

**Comment by raustin18** [comment]
Hey @Gary-H9, I've tried that a few times and it just ends up cycling round the same thing every time and eventually lands on this page again

**Comment by mitchdawson1982** [comment]
Hi @raustin18, let me know when you have some time to go over the issue?

**Comment by raustin18** [comment]
Hi @Gary-H9, I'm free now if you are

**Comment by mitchdawson1982** [comment]
HI @raustin18, Before you can access control panel you will need to follow the instructions to join the MOJ Analytical Service Organisation.

**Comment by mitchdawson1982** [comment]
Thanks. Please re raise if this is still an issue after that.

**Comment by raustin18** [comment]
Thank you for your help @mitchdawson1982 and @Gary-H9 - all seems to be working now! :)

**Comment by mitchdawson1982** [comment]
Great news 👍🏻
