### ISSUE TITLE
When running code (often using s3) I get an Rcpp error - function 'Rcpp_precious_remove' not provided

### ISSUE THREAD

**Issue by Ewal205** [ministryofjustice/data-platform-support#247]
### What happened?

When trying to run lines typically that download data from s3 I get the following error:

Error in read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'

This has only started in the last couple of weeks - running scripts that I have not changed (I think) and have had no issues running before. Happens on multiple repos.

### Relevant log output

```bash
Error in read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'
```

**Comment by mitchdawson1982** [comment]
Hi, @Ewal205 Can you advise if you have tried to reinstall / upgrade the Rcpp package ?

**Comment by Ewal205** [comment]
I have tried both of those and have also tried reverting one stage back. I have also uninstalled both it and tidyverse (which I think depends on it) and then reinstalled tidyverse only to try and install Rcpp via a dependency rather than directly - none working!

**Comment by mitchdawson1982** [comment]
I believe you need to use Rcpp >=1.0.7, can you confirm if this is the case ?

**Comment by Ewal205** [comment]
So do I! - But I can't seem to do it - update.packages('Rcpp') does nothing and I tried editing the renv requirements file from 1.0.6 to 1.0.7 and it won't run...

**Comment by Ewal205** [comment]
I have managed to update the package via updating the CRAN repository that the lockfile is referencing! Solved the error - thank you!
