### ISSUE TITLE
Rglpk not installing on new version of app

### ISSUE THREAD

**Issue by elliepage** [ministryofjustice/data-platform-support#248]
### What happened?

Trying to install packages on the new version of the app for the first time and Rglpk won't install. Originally it had problems even installing renv so I cleared my projects and that now works, but Rglpk doesn't.

### Relevant log output

```bash
Error: Error installing package 'Rglpk':
=================================

* installing *source* package ‘Rglpk’ ...
** package ‘Rglpk’ successfully unpacked and MD5 sums checked
** using staged installation
./cleanup: 2: cd: can't cd to src/GLPK
** libs
/bin/bash: line 0: cd: GLPK: No such file or directory
make: *** [Makevars:10: GLPK.ts] Error 1
ERROR: compilation failed for package ‘Rglpk’
* removing ‘/home/elliepage/sat/renv/library/R-4.0/x86_64-pc-linux-gnu/.renv/1/Rglpk’
install of package 'Rglpk' failed [error code 1]
```

**Comment by julialawrence** [comment]
Hiya could you provide some additional detail? Which app and how are you trying to install the new package?

**Comment by elliepage** [comment]
the app is just called sat, and I was under the impression the packages should install from the lockfile when I run renv::init() but it gets stuck at Rglpk.

**Comment by julialawrence** [comment]
could you link the workflow please?

**Comment by elliepage** [comment]
What do you mean by that?

**Comment by julialawrence** [comment]
apologies, what I meant was where are you seeing this error?

**Comment by elliepage** [comment]
In the console of R

**Comment by julialawrence** [comment]
@elliepage if you're still having this issue can you please reopen the ticket?
