### ISSUE TITLE
AP Authentication

### ISSUE THREAD

**Issue by BrianEllwood** [ministryofjustice/data-platform-support#25]
Hi there, I'm having issues logging on the AP this morning. Following authentication I am being redirected to a webpage that says:
```state from argument does not match state restored from session ```
rather than the AP. I've tried restarting my session but this hasn't fixed it. Please could you advise me re. what to try next. Thanks!

[Slack Message](https://mojdt.slack.com/archives/C4PF7QAJZ/p1682068024377609?thread_ts=1682068024.377609&cid=C4PF7QAJZ)

**Comment by LouiseABowler** [comment]
Recommended that the user visit https://controlpanel.services.analytical-platform.service.justice.gov.uk/oidc/logout/ to force a logout before retrying. No follow-up from the user; closing.
