### ISSUE TITLE
Cannot launch Rstudio

### ISSUE THREAD

**Issue by lhan1825** [ministryofjustice/data-platform-support#252]
### Which tool do you need help with?

RStudio

### What happened?

I have not able to launch my Rstudio for the last few days, I have tried to restart the AP and restart my Rstudio. 
But I keep getting the error message saying 'Could not connect to the R session on Rstudio Server. Error occurred during transmission.'

Could someone help to resolve this please?

Thank you

**Comment by bagg3rs** [comment]
@lhan1825 can you try the following https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/#clearing-your-rstudio-session

**Comment by lhan1825** [comment]
> @lhan1825 can you try the following https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/#clearing-your-rstudio-session

Hi, thanks for the guidance, I have tried this just now and still getting the same error message.

**Comment by lhan1825** [comment]
Hi @bagg3rs , I'm still unable to launch Rstudio, could you kindly help me to resolve this please? Thanks.

**Comment by bagg3rs** [comment]
Hi @lhan1825 we do have a path forward, let me get a team member to follow up with you. Sorry for delay.

**Comment by ymao2** [comment]
@lhan1825 ,  I have reset your rstudio's desktop state,  could you give a try? hopefully you can get the rstudio launched
