### ISSUE TITLE
Re-adding my github to the platform

### ISSUE THREAD

**Issue by aceross** [ministryofjustice/data-platform-support#253]
### Which tool do you need help with?

Control Panel, User and Account

### What happened?

I used my previous github account `aceross` in joining the MoJ. I added my justice.gov.uk email but did not set it to primary. I've experienced issues where I cannot be added by my work email to app-admin, as it is not found (github only has my personal email as primary). I've now set github to use the work email as primary and have been told I need to be removed and re-added to the platform in order to solve this.

**Comment by BrianEllwood** [comment]
@aceross so have you changed your github username from aceross ?

**Comment by aceross** [comment]
I haven't changed anything. My lead is trying to add me to admin for an app and can't find my email. We asked in #data-platform-application-migration-support and they suggested I be removed and re-added. The issue, I am told, is that I hadn't put my justice email as primary in my github account. The suggestion was that "ask the user to change the primary email of his github account, then re-signup the cpanel".

**Comment by BrianEllwood** [comment]
Hi @aceross  We have checked control panel and nothing needs to be done as  the Control panel has picked up your new primary email,  your team should now be able to grant the permission based on this new email.

**Comment by aceross** [comment]
OK - I will inform my line manager. Thanks!
