### ISSUE TITLE
Create dev and prod IAM roles for bold rr ops project

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/data-platform-support#254]
### Which tool do you need help with?

Amazon Web Services

### What happened?

Hey. 

Thanks for all the help the team has been giving William Martin and Andreas on the BOLD work. 

For the work a single IAM role `alpha_app_bold-case-info-dashboard` was originally created. However, it seems both **prod** and **dev** environments of the app are using that role. There seems there may be a risk here, and that perhaps we should have two separate IAM roles (each pointing at the data required only for their respective environments). 

Possible approach is:
- Create alpha_app_bold-case-info-dashboard-dev pointing at S3 bucket alpha-bold-rr-ops/dev
- Create alpha_app_bold-case-info-dashboard-prod pointing at S3 bucket alpha-bold-rr-ops/prod
- Delete alpha_app_bold-case-info-dashboard (the original IAM role that we no longer will need)

From here I can re-setup all the Athena permissions myself needed in those roles. 

Many thanks

Michael

**Comment by julialawrence** [comment]
Hiya Michael,

We currently don't support this functionality. We have raised an issue on our backlog, however it's difficult for us to give an estimate of completion as we have only had one request for this so far.

**Comment by mshodge** [comment]
Thanks @julialawrence is the norm for the same role to be used across `dev` and `prod` apps? If so, and that's been cleared with Cyber Security in the past maybe we don't need to have two?

**Comment by julialawrence** [comment]
That is left up to the discretion of the app owner. Usage of the development environment isn't required for deployment into production so owners (either because they choose not to or are advised not to) can disable it. At present, we are only able to support these environments under this limited constraint.

**Comment by julialawrence** [comment]
@mshodge Hiya if you I can answer some additional questions for you on this issue, please don't hesitate to raise another ticket.
