### ISSUE TITLE
Loading S3 bucket into R

### ISSUE THREAD

**Issue by AmyCookson23** [ministryofjustice/data-platform-support#256]
### Which tool do you need help with?

RStudio, S3

### What happened?

I've never loaded an S3 bucket into Rstudio before and unsure how to do this. The process I following using training videos didn't work:

install.packages("renv")
renv::restore()
offenders <- botor::s3_read("s3://alpha-bold-rr-offender-management/03dece3a-a28a-4d8b-94e8-e01d965ef61c.csv")

After trying to read the alpha bucket I got this error message: Error in s3_download_file(uri, t) : 
  Python `ClientError`: An error occurred (403) when calling the HeadObject operation: Forbidden

I'm not sure if I've just missed a step or done something completely wrong.

### Relevant log output

```bash
Error in s3_download_file(uri, t) : 
  Python `ClientError`: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by michaeljcollinsuk** [comment]
The problem looks to be a permissions error trying to access the `alpha-bold-rr-offender-management` bucket. I have checked the datasource, and you do not have access, you will need to reach out to one of the bucket admins, who can grant you access via the control panel. The admins for this bucket are:

andreas.soteriades@digital.justice.gov.uk (andreassoteriadesmoj)
William Martin (wmartin-gss)
antony.scott@justice.gov.uk (antonyjscott)

**Comment by AmyCookson23** [comment]
Thank you so much, I'll reach out to the admins now.

**Comment by michaeljcollinsuk** [comment]
I'll close this ticket now, but feel free to reopen if you still need support
