### ISSUE TITLE
our-coding-standards webpage not updated with latest merge

### ISSUE THREAD

**Issue by annie-howard** [ministryofjustice/data-platform-support#257]
### Which tool do you need help with?

Amazon Web Services, Application Migration Support

### What happened?

I have made an update to the repo https://github.com/moj-analytical-services/our-coding-standards by merging my feature branch. However, the webpage (https://moj-analytical-services.github.io/our-coding-standards/accurate.html) has not updated to reflect. I can't see any other instructions so assumed that merge would update the webpage. Can you advise me on what I need to do to deploy the updated web page? Thank you!

**Comment by NickWalt01** [comment]
Hi, the commit needs to be made onto the master branch for GH Pages to pick it up. The last commit on main was Sep 6, 2022. The last time the repo [GH Action](https://github.com/moj-analytical-services/our-coding-standards/actions/workflows/pages/pages-build-deployment) that pushes the changes to GH Pages was last year as well

**Comment by NickWalt01** [comment]
There is no manual option with the GH Pages setup on the repo, it is using the old method of GH Pages built from a branch, the new option is to use a GH Pages GH Action similar to this [file](https://github.com/ministryofjustice/operations-engineering-user-guide/blob/64d999ac608e3803378ac4c4013ae97e4a75feef/.github/workflows/publish.yml#L46) which can be manually started. I am not familiar with how this docs site is built based on the files in the repo. But a blank commit to the main branch might start the publish process as there is no branch protection on the master branch

**Comment by annie-howard** [comment]
Thanks @NickWalt01 so to clarify, the existing GH actions won't work. The recommendation is to set up a new GH actions workflow from scratch?

**Comment by michaeljcollinsuk** [comment]
@annie-howard I am not familiar with the repo, but checking the [repo Settings > Pages](https://github.com/moj-analytical-services/our-coding-standards/settings/pages), under the Build and Deployment section it has details about deployments that may be useful:

> Your GitHub Pages site is currently being built from the /docs folder in the master branch. [Learn more about configuring the publishing source for your site](https://docs.github.com/articles/configuring-a-publishing-source-for-github-pages/).

As your changes were outside of the docs folder, this seems to be the reason they were not deployed. It looks like the project is using an R library called Bookdown to build the `docs` directory - [this section of the docs might help you](https://bookdown.org/yihui/bookdown/build-the-book.html#build-the-book). But again I am not familiar with this, so it may be best that you either speak with a previous contributor to the repository for further guidance, or there is also an #r slack channel where you might be able to get advice on how to use Bookdown

**Comment by NickWalt01** [comment]
Hi @annie-howard the last time the GH action ran for theGH Pages on Main it passed, but if the commit was correct or not as per @michaeljcollinsuk comment suggests I do not know, this isn't a doc tech stack have seen before, ours is based on this [repo](https://github.com/ministryofjustice/template-documentation-site)

**Comment by annie-howard** [comment]
Thanks both! Your comments have helped a lot. Looking into it now and waiting PR from team member which will hopefully kick off the deployment once merged.

**Comment by annie-howard** [comment]
This is now resolved. Thank you!
