### ISSUE TITLE
Brief description of your issue

### ISSUE THREAD

**Issue by ed969** [ministryofjustice/data-platform-support#258]
### Which tool do you need help with?

RStudio

### What happened?

<img width="953" alt="RStudio Login attempt" src="https://github.com/ministryofjustice/data-platform-support/assets/127107930/b918676c-4e4e-4b55-b54c-380795a6640c">

**Comment by ymao2** [comment]
I am looking at it now

**Comment by ymao2** [comment]
@ed969 , I have reset your rstudio's desktop state,  give a try to see whether you can launch the rstudio

**Comment by ed969** [comment]
@ymao2, thank you very much, just tried it now and all appears to be working fine.

**Comment by ymao2** [comment]
you are welcome 👍 , I close this issue
