### ISSUE TITLE
Add IP addresses to the allow list for `bold-case-information-dashboard`

### ISSUE THREAD

**Issue by wmartin-gss** [ministryofjustice/data-platform-support#259]
### What happened?

This request is strongly linked to #251; would you please add the following IP addresses to the allow list for our app's dev and prod namespaces?

- 54.217.50.18
- 52.208.202.111
- 52.49.144.209

These IP addresses have been requested by cyber-security for a test using [Cymulate](https://cymulate.com/).

**Comment by wmartin-gss** [comment]
@ministryofjustice/bold-rr-ops-team for reference

**Comment by julialawrence** [comment]
Hiya, are you not able to do this via control panel?

**Comment by wmartin-gss** [comment]
Hi Julia, thank you for the quick response; I don't have the option to do this via the control panel, only a selection of options and a message saying to raise a support request for other IP ranges (see attached screenshot).
<img width="975" alt="Screenshot 2023-09-29 at 16 06 22" src="https://github.com/ministryofjustice/data-platform-support/assets/97306842/e21e57f0-3b2a-443a-bc47-36a10a97c24c">

**Comment by ymao2** [comment]
@wmartin-gss , I see , could you give a name for the above ip_address just like above `DOM1`,  then I can add them into our ip_address lookup table, after I complete it, you can start to choose them via control panel

**Comment by wmartin-gss** [comment]
Thanks @ymao2 - perhaps Cymulate or something like that? I think that's the name of the cybersecurity tool

**Comment by ymao2** [comment]
don't have much knowledge for cybersecurity tool, let me add those ip_ranges into  cpanel

**Comment by ymao2** [comment]
done, you can choose those ip_ranges from app-detail page
