### ISSUE TITLE
Network Intel App, doesn't load properly

### ISSUE THREAD

**Issue by BrianEllwood** [ministryofjustice/data-platform-support#26]
Hello,
The *Network Intel App*, doesn't load properly (see attached image). It only loads a blank screen with a transparent grey overlay that flashes. We ran the app locally and it runs ok, so it may be an AP issue. Could you please manually restart the app to see if it resolves the issue? If you can also send the app logs that would be great. Thank you!

[Slack Message](https://mojdt.slack.com/archives/C4PF7QAJZ/p1682074996005719?thread_ts=1682074996.005719&cid=C4PF7QAJZ)

**Comment by LouiseABowler** [comment]
Two issues identified:
- Some RShiny errors in the logs.
- After a restart of the app was triggered, it never completed.

The app admins were shown how to access the logs (Control Panel / Manage webapp page for this app / Scroll down to end). @jhackett-ap redeployed the app and the app admins reported it working normally. For full details, see the [Slack thread](https://mojdt.slack.com/archives/C4PF7QAJZ/p1682074996005719).
