### ISSUE TITLE
Access to ccmbpt-guidance Cloud Platform app (can't currently amend customer list)

### ISSUE THREAD

**Issue by glenn-christmas** [ministryofjustice/data-platform-support#261]
### What happened?

Hello,

[ccmbpt-guidance](https://ccmbpt-guidance.apps.live.cloud-platform.service.justice.gov.uk/) seems to have disappeared from my list of apps for which I can add/remove customers. I have a new joiner I'd like to provide access to. Could I please have access to this again so I can add them.

**Comment by julialawrence** [comment]
@glenn-christmas Are you still experiencing this issue?

**Comment by julialawrence** [comment]
Glenn, are you saying you can't access the namespace or the app information is no longer accessible in the control panel for you?

**Comment by glenn-christmas** [comment]
@julialawrence App info isn't available in the control panel. I'm not sure if this is a technical issue or if I've just not been added. I assumed I was added but perhaps not? If I'm not, please could I be added and I'll add my new joiner.
