### ISSUE TITLE
First deployment after the migration failed - regime dashboard app

### ISSUE THREAD

**Issue by andriasarri** [ministryofjustice/data-platform-support#263]
### Which tool do you need help with?

Application Migration Support

### What happened?

Hi, I tried to create a new release for the regime dashboard (first time after the migration) and it looks like the deployment failed. [https://github.com/ministryofjustice/regime-dashboard/deployments/prod]. 

Looking at the actions the following error appears:
Deploy Helm Chart into Cloud Platform
Process completed with exit code 1

Would you be able to help me with this? The app is set up to restart every Tuesday at 4pm. I hope this error is not going to create an issue with the restart this afternoon.

**Comment by julialawrence** [comment]
Fix applied, closing.
