### ISSUE TITLE
I need access for Quicksight please

### ISSUE THREAD

**Issue by opmoj** [ministryofjustice/data-platform-support#264]
### What happened?

https://github.com/ministryofjustice/data-platform-support/issues/105

Could you please grant my user alpha_user_opmoj/opmoj the same level of access again? I left the team for a few months but I'm now back and would require the same access. Please see thread link above. Julia sorted this out previously. Thank you.

**Comment by opmoj** [comment]
Are you able to give similar access to JeffreyOBMoJ and creader-moj as well?

**Comment by creader-moj** [comment]
@julialawrence alpha users for myself and Jeffrey: alpha_user_ JeffreyOBMoJ/JeffreyOBMoJ and alpha_user_creader-moj/creader-moj

**Comment by julialawrence** [comment]
@opmoj confirmed access. Other user requests tracked in another ticket.
