### ISSUE TITLE
prison-network-app greyout issue

### ISSUE THREAD

**Issue by joeprinold** [ministryofjustice/data-platform-support#265]
### Which tool do you need help with?

Application Migration Support

### What happened?

I am getting an issue where users are complaining that an app deployed on the platform is cutting out randomly (and therefore losing data that users have entered into the app). The app is called prison-network-app-prod and the problem only seems to have surfaced since the migration to the Cloud Platform. I can't spot a pattern to this behaviour. I don't see anything in the error logs when the issue occurs. The issue doesn't occur when running the app locally in RStudio.

The screen goes grey and the app doesn't appear to completely reload, but it loses all stored data.

The issue occurred once at around 2023-10-04 14:46:09.662 (or a minute or two either side of this). Log seems to indicate that at this time the user is being re-authenticated???

### Relevant log output

```bash
{"time":"2023-10-04T13:46:09.662Z","hostname":"data-platform-app-prison-network-app-prod-5d996f474d-dbb2l","pid":18,"level":"debug","name":"middleware","message":"Run userAuthenticated......"}
```

**Comment by joeprinold** [comment]
Is anyone able to look into this issue?

**Comment by julialawrence** [comment]
Raised a ticket in the backlog, closing
