### ISSUE TITLE
Access to new starters

### ISSUE THREAD

**Issue by jamiemoram** [ministryofjustice/data-platform-support#266]
### What happened?

I have requested access to Analytical Platform for two new PA's on the Calculate Release Dates team but have yet to hear anything, can someone please fast-track this? I emailed analytical_platform@digital.justice.gov.uk with their GitHub and email accounts. Thanks

**Comment by bagg3rs** [comment]
@jamiemoram apologies for this being missed invites sent to `creader-moj` and `JeffreyOBMoJ`
