### ISSUE TITLE
R Studio project won't execute code

### ISSUE THREAD

**Issue by DavidJBowers** [ministryofjustice/data-platform-support#267]
### Which tool do you need help with?

R Studio

### What happened?

My R Studio seems to be running very slowly and one of my projects won't work at all. When I load it and try to run even a simple test (test <-1) it soft locks. Reloading the page produces a blank screen and then eventually the choices to restart in safe mode or terminate R. 

I've tried restarting via the control panel and resetting the home directory, but the problem persists.

**Comment by julialawrence** [comment]
Closing as no additional answers from user.
