### ISSUE TITLE
Unexpected loss of service / pod-restart on pfg-dash-moj.apps.live.cloud-platform

### ISSUE THREAD

**Issue by ltd-pa** [ministryofjustice/data-platform-support#268]
### Which tool do you need help with?

Application Migration Support

### What happened?

I was using an application: https://pfg-dash-moj.apps.live.cloud-platform.service.justice.gov.uk/ that was migrated on to the cloud platform. I did something else for 30 minutes or so and then came back. The screen was greyed out, but rather than creating a new session when I pressed refresh - I got an out of service landing page - it was a few minutes before the app became accessible again. 

I expected the session to refresh, not the app to become unavailable for a period. Grafana doesn't seem to imply that any of the instances hit their memory limits (although I may be misunderstanding the dashboard). 

Grateful if you advise on what the issue is that lead to lack of service (and whether this can be mitigated in future). 

### Relevant log output

```bash
See utilisation logs at: https://grafana.live.cloud-platform.service.justice.gov.uk/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=default&var-cluster=&var-namespace=data-platform-app-pfg-dash-moj-prod&from=now-24h&to=now&refresh=10s
```

**Comment by julialawrence** [comment]
Being tracked in backlog issue, closing.
