### ISSUE TITLE
Access to an S3 bucket

### ISSUE THREAD

**Issue by Emmadufty** [ministryofjustice/data-platform-support#269]
### Which tool do you need help with?

Amazon Web Services, S3

### What happened?

Please could I get access to an S3 bucket called "alpha-css-temp". 

I have inherited a project which uses data stored in this bucket (someone called Oliver previously had access, but has since left the organisation). 

I require user (read?) access, so be able to query this data via Athena (and through Rstudio). I have permission from my line manager.

**Comment by michaeljcollinsuk** [comment]
Hi @Emmadufty I cant find a bucket with the name `alpha-css-temp`. I can see one called `alpha-ccs-temp`, did you mean that? 

If so, the bucket admins for the `alpha-ccs-temp` bucket are:
Ivy.Lau1@justice.gov.uk (ilaumoj)
david.wall1@justice.gov.uk (walld1)
marcus.john-baptiste@justice.gov.uk (marcus-j-b)
andrew.bardo@justice.gov.uk (andrewbardo)

Any of these users will be able to grant you access via the Control Panel, if you are able to reach out to them to ask? Alternatively, if you could get your line manager to drop a comment here confirming permission, then I can grant access. Thanks

**Comment by Emmadufty** [comment]
Hi, yes please that’s the one!

**Comment by michaeljcollinsuk** [comment]
Thanks for confirming, please see the list of bucket admins in previous comment to reach out to to request access - or ask your line manager to add a comment here, confirming you have permission to access, and I can update this for you myself. Thanks

**Comment by Emmadufty** [comment]
Hi Michael,

My line manager is @Faas, ***@***.***> who already has access to this bucket (I think). Henryk, could you please confirm for Michael I’m able to access to this?

**Comment by Emmadufty** [comment]
Hi Michael,

Could you give Emma access to this bucket?

Thank you!

Henryk

From: Dufty, Emma ***@***.***>
Sent: 13 October 2023 09:34
To: ministryofjustice/data-platform-support ***@***.***>; Faas, Henryk ***@***.***>
Subject: RE: [ministryofjustice/data-platform-support] Access to an S3 bucket (Issue #269)

Hi Michael,

My line manager is @Faas, ***@***.***> who already has access to this bucket (I think). Henryk, could you please confirm for Michael I’m able to access to this?

**Comment by michaeljcollinsuk** [comment]
Hi @Emmadufty you should now have access.
