### ISSUE TITLE
Need permissions to link Athena / S3 to QuickSight

### ISSUE THREAD

**Issue by creader-moj** [ministryofjustice/data-platform-support#272]
### Which tool do you need help with?

Amazon Web Services

### What happened?

**What** 
Could you please grant my user alpha_user_creader-moj/creader-moj and alpha_user_ JeffreyOBMoJ/JeffreyOBMoJ the same level of access so that we're able to connect Athena queries to QuickSight. We are both currently able to access the data + run queries in Athena directly. 

**Background**
Please see issue this issue for background: https://github.com/ministryofjustice/data-platform-support/issues/105

Per a comment from @julialawrence on the issue linked above, it seems the solution is: 

> After a somewhat painful debugging back-and-forth, it turns out that attaching a policy to user in QuickSight does not mean the same thing as attaching a policy to a user in other parts of AWS. In order to give Oma the right level of access, it turned out that there was a need to add AthenaFullAccess policy, but not via IAM to the quicksight service role, but in QuickSight:
> User picture in top-right --> Manage QuickSight --> Security & Permissions --> Resource access for individual users and groups --> IAM policy assignments, and create an assignment for the Full Access policy to Oma's user. That was the only way the access could be granted.

**Comment by creader-moj** [comment]
Hi @julialawrence - thanks for sorting out Oma's access! Following up for Jeffrey and myself, is there anything we can help with here?

**Comment by julialawrence** [comment]
Ok I see creader-moj.

**Comment by julialawrence** [comment]
@creader your access should be set, please test.

**Comment by creader-moj** [comment]
Thank you @julialawrence !!!!! Really appreciate the help on this one. I can confirm that I am now able to validate the connection to Athena + set up a new datasource.

**Comment by julialawrence** [comment]
Awesome. Closing!

**Comment by julialawrence** [comment]
Apologies, I thought you confirmed access. I misunderstood. You should have the same permissions as Oma now. Is Oma seeing the same error?

**Comment by creader-moj** [comment]
Oma and myself are sorted, it's just @JeffreyOBMoJ (alpha_user_ JeffreyOBMoJ/JeffreyOBMoJ) that we need to sort access for.

**Comment by JeffreyOBMoJ** [comment]
In case any changes were made, I just tried logging in and out and removed cookies but I'm still having the same issues @julialawrence .
