### ISSUE TITLE
Unable to Install GitHub

### ISSUE THREAD

**Issue by hashim-iqbal-gov** [ministryofjustice/data-platform-support#273]
### What happened?

Hello, I am unable to download and install github on my issued laptop (C10023353). I need access to the software to establish myself on the analytical platform, however whenever I attempt to download the software from the website it displays "virus detected" or "blocked". How can i proceed in order to access github?

**Comment by hashim-iqbal-gov** [comment]
Ah I see, I've been following the steps form this guide however I'm still unable to launch git bash in the browser in order to do certain steps - such as set my username to associate with your Git commits for every repository, or add SSH Keys for JupyterLab and R. How can I do that?

**Comment by jacobwoffenden** [comment]
> Ah I see, I've been following the steps form this guide however I'm still unable to launch git bash in the browser in order to do certain steps - such as set my username to associate with your Git commits for every repository, or add SSH Keys for JupyterLab and R. How can I do that?

Hi @hashim-iqbal-gov,

Have you launched a tool from the Control Panel? [This section](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#create-and-add-jupyterlab-ssh-key-to-github) of the documentation contains instruction on how to create SSH keys in the launched tool

Could you provide any screenshots of what you are seeing?

Thanks!
