### ISSUE TITLE
Decommission app: interventions-deploy

### ISSUE THREAD

**Issue by andrewc-moj** [ministryofjustice/data-platform-support#274]
### Which tool do you need help with?

Application Migration Support

### What happened?

App called `interventions-deploy` can be decommissioned.
Checked with customers as noted [here](https://mojdt.slack.com/archives/C8X3PP1TN/p1697104083373769?thread_ts=1697099746.389249&cid=C8X3PP1TN)

**Comment by Gary-H9** [comment]
Hi @andrewc-moj - we will decommission the app. :)

We'd look to delete the associated S3 bucket as part of this activity, is this acceptable to you?

**Comment by andrewc-moj** [comment]
Hey @Gary-H9  - yeah, i've moved the data i needed into another bucket so more than happy for it to be freed up

**Comment by Gary-H9** [comment]
Looking at this now. App deleted in the Control Panel `Successfully deleted interventions-deploy app`

Now looking to remove the namespace and S3 bucket.

**Comment by Gary-H9** [comment]
Completed, S3 bucket will be removed as part of another ticket.
