### ISSUE TITLE
AWS CLI login

### ISSUE THREAD

**Issue by dami-moj** [ministryofjustice/data-platform-support#275]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I have tried setting up my AWS SSO following the guide provided here [Access by SSO with GitHub](https://github.com/ministryofjustice/analytical-platform-iam/blob/main/documentation/AWS-CLI.md#access-by-sso-with-github).

However, upon ruuning

`SSO session name (Recommended): dev # this can be called anything`
`SSO start URL [None]: https://moj.awsapps.com/start#/`
`SSO region [None]: eu-west-2  # this will be a drop down option to select appropriate region`
`SSO registration scopes [sso:account:access]: # keep default and just press enter`

Authorizing the request - results in `invalid grant provided`

**Comment by Gary-H9** [comment]
Hi @dami-moj can you add a screenshot of what you're seeing please? Thanks!
