### ISSUE TITLE
Access to S3 bucket not working

### ISSUE THREAD

**Issue by liztindale-moj** [ministryofjustice/data-platform-support#277]
### Which tool do you need help with?

S3

### What happened?

I've been asked to quality assure a project conducted in the Prisons Business Partnering team, and have been granted read/write access to their S3 bucket (alpha-prisons-bpt) to complete this task. When I look in S3 I can enter the bucket and see all the files in it, but can't interact with them (e.g., can't download). When I try to import the data through RStudio, I get an Access Denied error. I've restarted my RStudio and my laptop and it's still not working.

### Relevant log output

```bash
Could not read s3://alpha-prisons-bpt/Regime /In-Cell Tech/Launchpad VfM Eval Data/Employment on Release/Employment on release 04 19 - 08 23.xlsx
Error: AccessDenied (HTTP 403). Access Denied
```

**Comment by Gary-H9** [comment]
👋  Hello @liztindale-moj - please get in touch with the bucket admin and ask them to change the permissions they granted you. When they grant them we think they've included the bucket name in the path, this ought to be removed and should be ~ `/Regime /In-Cell Tech/Launchpad VfM Eval Data` 

![image](https://github.com/ministryofjustice/data-platform-support/assets/26419401/1547d8ea-84a3-41f8-8f3e-5be97a4c0ecd)
