### ISSUE TITLE
Access denied exception for AP S3 bucket when transferring data using generic-data-analytics-extractor on Dev environment

### ISSUE THREAD

**Issue by amolphalnikar** [ministryofjustice/data-platform-support#278]
### Which tool do you need help with?

S3

### What happened?

We (Interventions team) are seeing some Access denied exception for AP S3 bucket when transferring data using generic-data-analytics-extractor on Dev environment. 

The IRSA service account is configured in [https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespa[…]hmpps-interventions-dev/resources/analytical-platform-access.tf](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-dev/resources/analytical-platform-access.tf#L10C11-L10C11) and used in https://github.com/ministryofjustice/hmpps-interventions-service/blob/main/helm_deploy/hmpps-interventions-service/values.yaml

Previously it was using access keys which was changed to service account sometime back. We had few other issues which were resolved and for reference please check the slack conversation - https://mojdt.slack.com/archives/C8X3PP1TN/p1697109831782559

### Relevant log output

```bash
upload failed: export/data/database_name=db08b48c376b780aa9_public/table_name=supplier_assessment_appointment/extraction_timestamp=20231013091821Z/supplier_assessment_appointment.jsonl to s3://moj-reg-dev/landing/hmpps-interventions-dev/data/database_name=db08b48c376b780aa9_public/table_name=supplier_assessment_appointment/extraction_timestamp=20231013091821Z/supplier_assessment_appointment.jsonl An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
upload failed: export/logs/database_name=events/table_name=events/extraction_timestamp=20231013091821Z/events.log to s3://moj-reg-dev/landing/hmpps-interventions-dev/logs/database_name=events/table_name=events/extraction_timestamp=20231013091821Z/events.log An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by bagg3rs** [comment]
This is being investigated [here](https://moj.enterprise.slack.com/archives/CBVUV2613/p1697196718603219)

**Comment by jacobwoffenden** [comment]
Hi @amolphalnikar,

We've just deployed a change to update the ARN that is allowed to push to `s3://moj-reg-dev/landing/hmpps-interventions-dev` - This is now the Cloud Platform IRSA ARN you provided on Slack.

Can you please rerun the transfer and let us know the outcome.

Thanks!

**Comment by amolphalnikar** [comment]
Thanks @jacobwoffenden - I have updated on slack and updating over here as well.

 - My sincere apologies, I provided prod ISRA details of prod rather than dev by mistake hence my retest failed. The dev environment details are as below. Please can these be updated ?
 
`arn:aws:iam::754256621582:role/cloud-platform-irsa-3a5441239a9f9979-live`

`%kubectl get sa hmpps-interventions-to-ap-s3 -oyaml -n hmpps-interventions-dev 
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::754256621582:role/cloud-platform-irsa-3a5441239a9f9979-live
  creationTimestamp: "2023-08-14T13:36:25Z"
  name: hmpps-interventions-to-ap-s3
  namespace: hmpps-interventions-dev
  resourceVersion: "1209651497"
  uid: e74f3614-ba9f-4d1b-bdb4-73ec76346cf9`

**Comment by jacobwoffenden** [comment]
Hey @amolphalnikar!

No worries, I've opened a new PR for the new ARN. It should get picked up and deployed tomorrow.

I will let you know when it can be tested again.

Cheers!

**Comment by jacobwoffenden** [comment]
Hi @amolphalnikar,

This has been deployed, please test again.

Thanks!

**Comment by amolphalnikar** [comment]
Hi @jacobwoffenden 

Thanks for making this change. We are in the process of making change and deploying. Once we test, we will let you know.

Many Thanks

**Comment by amolphalnikar** [comment]
Hi @jacobwoffenden 

After running, I don't see any errors in the logs. 
Do you know who can check S3 bucket s3://moj-reg-dev/landing/hmpps-interventions-dev/ and confirm if there are files transferred around 15:21 ?

Many Thanks

**Comment by jacobwoffenden** [comment]
Hey @amolphalnikar,

There are logs and metadata in `s3://moj-reg-dev/landing/hmpps-interventions-dev` with an extraction timestamp of `20231017152146Z`

Can we call this a success?

Cheers!

**Comment by amolphalnikar** [comment]
Hi @jacobwoffenden ,

Yeah, that looks good then. Thanks for checking.

For changes to pre-prod and then prod, should I raise similar JIRA ticket ? 

Many Thanks

**Comment by jacobwoffenden** [comment]
Hey @amolphalnikar,

You should be able to create a pull request yourself on [github.com/ministryofjustice/register-my-data](https://github.com/ministryofjustice/register-my-data), specifically

- [preprod](https://github.com/ministryofjustice/register-my-data/blob/main/stacks/moj-reg-preprod/config.yaml#L28-L29)

- [prod](https://github.com/ministryofjustice/register-my-data/blob/main/stacks/moj-reg-prod/config.yaml#L33-L34)

Failing that, register-my-data is a product of Data Engineering, so you could ask in [`#ask-data-engineering`](https://moj.enterprise.slack.com/archives/C8X3PP1TN)

Thanks!

**Comment by amolphalnikar** [comment]
Closing the issue as this is fixed in dev environment.
