### ISSUE TITLE
Add option to enable Web Application Firewall for data platform apps

### ISSUE THREAD

**Issue by wmartin-gss** [ministryofjustice/data-platform-support#279]
### Which tool do you need help with?

MoJ Cloud Platform

### What happened?

Cybersecurity has requested this be enabled for our application; I've managed to modify the helm chart for our app to add this in temporarily while they conduct their tests, but would much rather this were managed by the Data Platform team. 

Relevant guidance for enabling this on the Cloud Platform is [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html). I've had a stab at putting this together as a patch on [the analytics-platform-helm-charts repo](https://github.com/ministryofjustice/analytics-platform-helm-charts/) so it's easier to apply if you do decide to support this:

```diff
diff --git a/charts/webapp-cp/templates/ingress.yaml b/charts/webapp-cp/templates/ingress.yaml
index 9e860b4f..a3819b4f 100644
--- a/charts/webapp-cp/templates/ingress.yaml
+++ b/charts/webapp-cp/templates/ingress.yaml
@@ -3,6 +3,12 @@ kind: Ingress
 metadata:
   name: {{ template "stripPrefixSuffixFromName" . }}
   annotations:
+{{ if .Values.ModSec.enabled }}
+    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
+    nginx.ingress.kubernetes.io/modsecurity-snippet: |
+      SecRuleEngine On
+      SecDefaultAction "phase:2,pass,log{{ if .Values.GithubTeam }},tag:github_team={{ .Values.GithubTeam }}{{ end }}"
+{{ end }}
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_headers "X-Content-Type-Options: nosniff";
@@ -10,7 +16,11 @@ metadata:
     external-dns.alpha.kubernetes.io/set-identifier: "{{ template "stripPrefixSuffixFromName" . }}-{{ .Values.Namespace }}-green"
     external-dns.alpha.kubernetes.io/aws-weight: "100"
 spec:
+{{ if .Values.ModSec.enabled }}
+  ingressClassName: modsec
+{{ else }}
   ingressClassName: default
+{{ end }}
   tls:
     - hosts:
         - {{ template "stripPrefixSuffix" . }}
diff --git a/charts/webapp-cp/values.yaml b/charts/webapp-cp/values.yaml
index 407fa256..5936cfbc 100644
--- a/charts/webapp-cp/values.yaml
+++ b/charts/webapp-cp/values.yaml
@@ -1,5 +1,6 @@
 ReplicaCount: 1
 GithubRepo: ""
+GithubTeam: ""
 Namespace: ""
 Alerts:
   enabled: false
@@ -85,6 +86,8 @@ Secrets:
     Parameters: {}
 Ingress:
   Port: 80
+  ModSec:
+    enabled: false
 ServiceAccount:
   RoleARN: ""
 Cron:
```

I'll update this issue with any relevant information from the cybersecurity test when I have it, as they're running the tests both with and without the WAF enabled.

**Comment by julialawrence** [comment]
Hiya William, if I'm reading this right, enabling this is passing an annotation to the ingress resource? If so, we can raise a story to allow you specify custom annotations in your workflows to pass to the chart.

**Comment by wmartin-gss** [comment]
I think there's slightly more than that, as the `ingressClassName` under `spec` needs to be updated to `modsec` as well

**Comment by julialawrence** [comment]
Gotcha, we can make that configurable as well, no problem. I will raise an issue on our backlog to implement, once that's done, I will close this ticket with the link to our issue so you can track. :)

**Comment by julialawrence** [comment]
And cheers for doing most of the work for us already. :P Are you looking to move teams by any chance?

**Comment by julialawrence** [comment]
Have raised an issue in our backlog to implement.

**Comment by wmartin-gss** [comment]
If it's helpful @julialawrence, I found this example of enabling ModSec in the HMPPS Helm charts ([values](https://github.com/ministryofjustice/hmpps-helm-charts/blob/81faa8520085fdb96f88cb96f0e22fa5749771a8/charts/generic-service/values.yaml#L62C3-L62C29) and [ingress](https://github.com/ministryofjustice/hmpps-helm-charts/blob/81faa8520085fdb96f88cb96f0e22fa5749771a8/charts/generic-service/templates/ingress_cp.yaml#L22-L27), via [this Slack thread](https://mojdt.slack.com/archives/C57UPMZLY/p1697527301102999))
