### ISSUE TITLE
Keep AP account active

### ISSUE THREAD

**Issue by lauratraceymoj** [ministryofjustice/data-platform-support#280]
### Which tool do you need help with?

User and Account

### What happened?

My team member (github username `hollygatward`) is going on a career break so won't be using their AP account for 6 months, how do I make sure their account isn't deactivated for inactivity?

**Comment by julialawrence** [comment]
Hiya Laura, do you need to keep it active? I think it's fairly easy to reactivate once she's returned if the github account is removed from the org.

**Comment by lauratraceymoj** [comment]
We were just trying to avoid having to request access to and re-clone team repos when she returns, but happy to leave it if it's not possible to keep it active

**Comment by julialawrence** [comment]
No action needed.
