### ISSUE TITLE
RShiny App not working as expected

### ISSUE THREAD

**Issue by Eve-Dolling** [ministryofjustice/data-platform-support#281]
### Which tool do you need help with?

RStudio

### What happened?

I’m updating an R Shiny web app, the updated code works on my local app and on a Pull Request has passed all of the auto checks on Github. However when I try to access the web app I see this a notification stating that 'An Error has occurred. Check your logs or contact the app author for clarification'

I'm not sure how to progress?

**Comment by jacobwoffenden** [comment]
Hi @Eve-Dolling,

I've recreated this by adding myself as a customer to `hlt-portal`.

When accessing the app, the following warning is shown by the `webapp` container:

```json
{"level":"info","message":"Warning: Error in BAU_24m_trends_monthly_perc_pts_increase_green_3month_only: could not find function \"BAU_24m_trends_monthly_perc_pts_increase_green_3month_only\"\n","service":"shiny.stderr"}
```

This information can be obtained from Cloud Platform's Kibana ([link](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.namespace_name,negate:!f,params:(query:data-platform-app-hlt-portal-dev),type:phrase),query:(match_phrase:(kubernetes.namespace_name:data-platform-app-hlt-portal-dev))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.container_name,negate:!f,params:(query:webapp),type:phrase),query:(match_phrase:(kubernetes.container_name:webapp)))),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:'NOT%20log:%20%20%22%2Fhealthz%22'),sort:!()))), specifically [this](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/doc/167701b0-f8c0-11ec-b95c-1d65c3682287/live_kubernetes_cluster-2023.10.16?id=30be2f68-9456-14da-1b74-cd4d5713565a) document.

**Comment by Eve-Dolling** [comment]
Thanks so much for this Jacob I’ve just rectified the code and it now works fine 😊

**Comment by jacobwoffenden** [comment]
Thanks, @Eve-Dolling!

I'll close this ticket, but please get in touch if you need further assistance.

Thanks!
