### ISSUE TITLE
Lost access

### ISSUE THREAD

**Issue by sboltonmoj** [ministryofjustice/data-platform-support#282]
### Which tool do you need help with?

Database Access, RStudio, User and Account

### What happened?

I have lost access to the Analytical Platform during my maternity leave.  My GitHub username is sboltonmoj. Is there a way to get this back so that I have my previous set up? I need admin access to the following repos: https://github.com/moj-analytical-services/hr-arm-recruitment-data-processing, https://github.com/moj-analytical-services/Oleeo, https://github.com/moj-analytical-services/hr-arm-recruitment-d-i , https://github.com/moj-analytical-services/RecruitmentTimeToHire

![AP](https://github.com/ministryofjustice/data-platform-support/assets/98838647/a5fa6c0f-e67f-4540-820a-a4b4b0e709fe)

**Comment by NickWalt01** [comment]
Hi @sboltonmoj have tried your username and it has been longer than 90 days and GH hasn't remembered your settings. I have sent out a new invite to the AS Org and will see what teams can get you access to the repo's

**Comment by sboltonmoj** [comment]
Thanks Nick. I'm having issues logging in to GitHub using 2FA. It keeps saying "Two-factor code verification failed. Please try again." I've used my recovery key to log in, and tried rescanning the QR code to set up 2FA again but it still comes up with that message.

**Comment by NickWalt01** [comment]
Sure, for GitHub when lose 2fa: https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials

If it is the 2FA for the AP tool that would be for [#ask-analytical-platform](https://mojdt.slack.com/archives/C051XTZNLJX) to reset

**Comment by jacobwoffenden** [comment]
Thanks, @NickWalt01, however our support process is now through GitHub ([link](https://github.com/ministryofjustice/data-platform-support/issues/new/choose))

@sboltonmoj I have reset your MFA, can you please try logging in to Control Panel again, you might need to reset your session, this should allow you to reconfigure your MFA.

As for access to those repositories, @emmatearse should be able to add you to the relevant teams.

Thanks!

**Comment by jacobwoffenden** [comment]
Hi @sboltonmoj,

We've not heard back in a few days, so we'll close this issue.

If you're still having trouble, please reopen and let us know.

Thanks!
