### ISSUE TITLE
Cannot access Rshiny apps due to error page: 'IP XX.XXX.XXX.XX is not whitelisted'

### ISSUE THREAD

**Issue by Emmadufty** [ministryofjustice/data-platform-support#283]
### Which tool do you need help with?

Rshiny app

### What happened?

Trying to access the following Rshiny apps, but instead get a page with the IP error. 

https://[crown-flow-explorer.apps.live.cloud-platform.service.justice.gov.uk](https://crown-flow-explorer.apps.live.cloud-platform.service.justice.gov.uk/)/

**Comment by jacobwoffenden** [comment]
Hi @Emmadufty,

crown-flow-explorer is accessible from DOM1, if you require a new range adding, you could reach out to the app owner @ojtattersall

Thanks!

**Comment by Emmadufty** [comment]
Hi Jacob,

Oliver no longer works with us, so cannot ask him to add me.

Thanks,

Emma

**Comment by jacobwoffenden** [comment]
Hi @Emmadufty,

As Oliver has left, we need you to identify a new application administrator, once assigned, they can amend the IP ranges via the Control Panel

Thanks!

**Comment by Emmadufty** [comment]
Hi Jacob,

Could @Chander, ***@***.***> and @Faas, ***@***.***> please be assigned as application administrators?

Many thanks,

Emma

**Comment by jacobwoffenden** [comment]
As GitHub stripped the emails, I reached out to @Emmadufty, and the newly identified admins are @henryk01trent and @satchandersan

@satchandersan has approved ownership change via email

**Comment by jacobwoffenden** [comment]
Hi @Emmadufty,

As discussed on Microsoft Teams, the allowed IP ranges can be updated by @satchandersan or @henryk01trent following https://user-guidance.analytical-platform.service.justice.gov.uk/apps/manage-app-settings-from-cpanel.html#ip-whitelist

If you require further assistance please let us know.

Thanks!
