### ISSUE TITLE
Unbale to grant a user access to an S3 folder

### ISSUE THREAD

**Issue by jessicadaymoj** [ministryofjustice/data-platform-support#287]
### Which tool do you need help with?

User and Account

### What happened?

Hi - I am unable to grant a user access to an S3 bucket, despite them being a member of the github `moj-analytical-services` organisation.
Is there anything additional that they need to do in order to appear in the _grant user access_ user list which I can see via the control panel? 
Thanks

**Comment by Emterry** [comment]
Hi Jessica, what bucket are you trying to add them too? also have they accepted their invite to the organisation? 

Thanks

**Comment by jessicadaymoj** [comment]
Hi - They have accepted their invite to the organisation and I am trying to add them to the `alpha-app-gpc-anomalies` bucket. 
Thanks

**Comment by Emterry** [comment]
hi - whats the details of the user you are trying to add? e.g name, email?
Thanks

**Comment by jessicadaymoj** [comment]
email: mercedes.denton@justice.gov.uk
username: gpccompliance

**Comment by Emterry** [comment]
Can you ask the User to log onto the control panel, this should hopefully resolve the issue. The guidance can be found here if needed  https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#quickstart-guide

once they have done that can you update me please as to if it resolves the issue

Thanks

**Comment by jessicadaymoj** [comment]
Thank you - I won't be able to check with with the user until Tuesday, so will provide an update after that if it still isn't working!

**Comment by Emterry** [comment]
Thanks thats great

**Comment by jessicadaymoj** [comment]
That has resolved the issue - thank you!

**Comment by jhpyke** [comment]
Closed as resolved
