### ISSUE TITLE
New Dashboard Request

### ISSUE THREAD

**Issue by dm371** [ministryofjustice/data-platform-support#290]
### Which tool do you need help with?

Application Migration Support, RStudio

### What happened?

I have been asked by Julia Lawrence to write a support request regarding a new dashboard I am looking to code and implement through the analytical platform. 

I am in Strategic Workforce and Pay Modelling in the Modelling Hub, and am currently writing a coded model to replace existing staff targeting processes across the public prison estate. As part of this work, we would like to produce an informative, front-facing dashboard, coded in Rshiny. This dashboard will incorporate outputs from the targeting model alongside data captured through an under-development shift-planning tool. The purpose of the dashboard, in the first instance, will be to visualise comparisons between modelled staffing targets, mapped to different work areas within prisons, and actual staff allocations to those same work areas. This information is not currently available to colleagues, and we are working closely with other workforce planning teams to address any overlap and if/how our work might feed into larger tools in the future.

As the targeting model is currently under development, the finalised data I will be looking to visualise are not currently on the AP (although data drivers for the model are). The operational tool to capture shift patterns is also still under development, so these data are also not currently held on the AP. The purpose of raising this ticket now is to begin scoping how a dashboard like this could be implemented through the AP, what limitations there may be, and to discuss scoping initial coding and onboarding using dummy data, so that when the targeting model is finalised (slated for between financial year-end and the end of June 2024) its rollout can be synchronised with the rollout of the dashboard. Ultimately, we would like to synchronise dashboard updates with targeting model runs. These are currently planned to be run quarterly. Only one of these runs per year is likely to be used for financial targeting, with the other three planned to assess changes to the in-year position or to the model assumptions/code prior to the following year's financial targeting run. As such, updates to the dash may end up being once per year or quarterly, but these discussions are ongoing.

**Comment by BrianEllwood** [comment]
Hi @julialawrence ticket raised as requested - what is the process now please ?

**Comment by julialawrence** [comment]
We will discuss it in standup next week. Please raise it on Monday.

**Comment by BrianEllwood** [comment]
@julialawrence I am not in Next week hopefully you will see this Monday

**Comment by dm371** [comment]
Hi All- don't know if any progress on this?

**Comment by julialawrence** [comment]
Hiya @dms371 -- we have raised a story in our backlog for the next sprint to work on reenabling new app onboarding. We typically close support issues once we raise a story, so you can track the progress of your request here: https://github.com/ministryofjustice/data-platform/issues/1700

**Comment by dm371** [comment]
Ah thanks very much! I'll track it there then!
