### ISSUE TITLE
User cannot access safety diagnostic tool app

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/data-platform-support#292]
### Which tool do you need help with?

Application Migration Support

### What happened?

Original request came in via email from [Esra.Sari@hmiprisons.gov.uk](mailto:Esra.Sari@hmiprisons.gov.uk) on 13/10/23.

Original email:
I have tried to do this, it talks about repository’s I don’t understand what these are, this is impacting on critical inspection work, can you please advise?
I am in a prison I have no access to a phone.
I really need to access the safety diagnostic tool I am unclear why this has suddenly stopped. Github is confusing.

Follow up email:
This is a follow up message – why has my access to the platform been stalled please? Can this be rectified as I need to use it to inspect.

![Screenshot 2023-10-19 at 11 29 26](https://github.com/ministryofjustice/data-platform-support/assets/15347726/c547939e-5165-4fa2-a262-bf80bc217ba7)

**Comment by michaeljcollinsuk** [comment]
@jacobwoffenden has emailed the user to check which url they are using to attempt to access the app.

Looking at the screenshot provided, it appears the user is trying to access Control Panel, based on the title in the open tab. Also the safety-diagnosis-tool app only uses Nomis for login, not the passwordless flow that appears in the screenshot. So we need further information about the URL and login process they are following in order to provide further support. 

Link to team chat about the issue in slack: https://mojdt.slack.com/archives/C04M8224WCV/p1697711206617129

**Comment by jacobwoffenden** [comment]
No response, chased user.

**Comment by jacobwoffenden** [comment]
User has responded, no longer requires support
