### ISSUE TITLE
I cannot access the platform

### ISSUE THREAD

**Issue by SKAUR2023** [ministryofjustice/data-platform-support#294]
### Which tool do you need help with?

Control Panel

### What happened?

![image](https://github.com/ministryofjustice/data-platform-support/assets/148537244/5dafe8e1-a270-4912-95c1-671942775560)

The message stating I need access keeps appearing everytime i try to login

**Comment by glenn-christmas** [comment]
@SKAUR2023 Hello, please contact ccmanalytics_asd@justice.gov.uk regarding this issue as it looks like my team will need to add you to the access list for this app.

**Comment by michaeljcollinsuk** [comment]
Thanks @glenn-christmas for responding. @SKAUR2023 I will close this issue, if you need further help after being granted access, please create a new issue.
