### ISSUE TITLE
Urgent: My colleague with GitHub username jhubermoj cannot access GitHub via 2FA

### ISSUE THREAD

**Issue by georginaeaton** [ministryofjustice/data-platform-support#295]
### Which tool do you need help with?

User and Account

### What happened?

Colleague with username jhubermoj cannot access github or the AP because 2FA is not working. Previously 2fa was done via work phone with the number XXXXXXXXXX, however after recent phone upgrade this is no longer working. Git hub recovery codes have been tried but are not working. Please could the 2FA be reset to a new device with number XXXXXXXXXX, as urgent work needs to be completed.

**Comment by michaeljcollinsuk** [comment]
@georginaeaton I have reset 2FA for the user `jhubermoj`. When they next log in to control panel [(here)](https://controlpanel.services.analytical-platform.service.justice.gov.uk/), at which point they will be prompted to setup their 2FA again.

However if the user has lost access to github, they will need to resolve this before being able to log in. Have you followed steps in the github advice to try to resolve? https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials

**Comment by michaeljcollinsuk** [comment]
I had a call with @jhubermoj on Friday to discuss this issue, there was no way for us to restore github access. Github support can help to restore access but this takes 1-3 business days. Closing this issue as control panel 2FA has been reset, please open an issue if there are any further issues after github access is restored.
