### ISSUE TITLE
I cannot access the AP Control Panel

### ISSUE THREAD

**Issue by shanurmiah** [ministryofjustice/data-platform-support#296]
### Which tool do you need help with?

Control Panel

### What happened?

There is a problem with your session

It might have timed out in which case you can[ reset your session ](https://alpha-analytics-moj.eu.auth0.com/v2/logout?returnTo=https%3A%2F%2Fcontrolpanel.services.analytical-platform.service.justice.gov.uk%2Foidc%2Flogout%2F), and login again.

If resetting your session doesn't help, it's possible that

    You may need to ensure you are in the [MoJ Analytical Services](https://github.com/moj-analytical-services) team on GitHub.
    You may have migrated to a newer version of the platform, so your account on this version is no longer available.

**Comment by ymao2** [comment]
@shanurmiah , your github account has been removed from `moj-analytical-services` ,   you need to follow the guide below to make request to re-join the `moj-analytical-services`
https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#4-access-the-analytical-platform

after you join back, then give an another try

**Comment by ymao2** [comment]
@shanurmiah,  have you raised your query on[#ask-operations-engineering](https://asdslack.slack.com/archives/C01BUKJSZD4)?, we normally won't do it on user's behalf. 
The email link is only used if you couldn't get the invite in a few days,  I think email (`operations-engineering@digital.justice.gov.uk`) is correct,  just didn't put it in correct format in the user-guide which we will update it soon

**Comment by shanurmiah** [comment]
Ok thanks, I will email them.
