### ISSUE TITLE
I cannot log in to to the Regime Dashboard or SDT

### ISSUE THREAD

**Issue by PaulBrinkworth** [ministryofjustice/data-platform-support#299]
### What happened?

I get an error message that IP 83.104.166.252 is not whitelisted

**Comment by ymao2** [comment]
@PaulBrinkworth,  sounds like you are not in one of following allowed ip_ranges(VPNs) chosen by this app.

`102PF Wifi, Digital Wifi and VPN, DOM1, QUANTUM, MoJo`

is it possible for you to use any one of above? If not and you believe your vpn should be added in the above list,  you can contact the app admin to add yours.  One of app admins is [Andria.Sarri@justice.gov.uk](mailto:Andria.Sarri@justice.gov.uk)

**Comment by ymao2** [comment]
it could be although I am not really sure,  but in the past, have you ever used any other VPN? e.g. DOM1,  
or how about you turn on GlobalProtect, then try again?

**Comment by PaulBrinkworth** [comment]
Just thought I would let you know the issue seemed absolutely aligned to GlobalConnect not working; it's working again today of its own accord and I can now access the SDt and Regime Dashboard :)

**Comment by ymao2** [comment]
Glad to hear your problem is solved,   thank you for letting me know, 😊
