### ISSUE TITLE
Dev Deployment failed during Helm Chart Upgrade

### ISSUE THREAD

**Issue by jhenfrancis** [ministryofjustice/data-platform-support#300]
### What happened?

Deployment of gpc-anomalies app on dev has failed multiple times with error:

> Error: UPGRADE FAILED: context deadline exceeded
> Error: Process completed with exit code 1.

Hoping someone can help me please?

### Relevant log output

```bash
process_ip_range=$(echo $IP_RANGES | sed "s/,/\\\,/g")
  
  helm upgrade --install --wait --timeout 10m0s --namespace $KUBE_NAMESPACE $KUBE_NAMESPACE mojanalytics/webapp-cp \
  --set AuthProxy.Env.Auth0Domain=$AUTH0_DOMAIN \
  --set AuthProxy.Env.Auth0Passwordless=$AUTH0_PASSWORDLESS \
  --set AuthProxy.Env.Auth0TokenAlg=$AUTH0_TOKEN_ALG \
  --set AuthProxy.Env.AuthenticationRequired=$AUTHENTICATION_REQUIRED \
  --set AuthProxy.Env.IPRanges=$process_ip_range \
  --set AuthProxy.Image.Repository=$ECR_REPO_AUTH0 \
  --set AuthProxy.Image.Tag="v5.3.3" \
  --set Namespace=$KUBE_NAMESPACE \
  --set Secrets.Auth0.ClientId=$AUTH0_CLIENT_ID \
  --set Secrets.Auth0.ClientSecret=$AUTH0_CLIENT_SECRET \
  --set Secrets.Auth0.CookieSecret=$COOKIE_SECRET \
  --set ServiceAccount.RoleARN=$APP_ROLE_ARN \
  --set WebApp.Image.Repository=$ECR_REPO_WEBAPP \
  --set WebApp.Image.Tag=$NEW_TAG_V \
  --set WebApp.Name=$KUBE_NAMESPACE \
  --set WebApp.resources.limits.cpu=100m \
  --set WebApp.resources.limits.memory=1Gi \
  --set WebApp.resources.requests.cpu=100m \
  --set WebApp.resources.requests.memory=1Gi \
  shell: /usr/bin/bash -e {0}
  env:
    AWS_DEFAULT_REGION: eu-west-2
    AWS_REGION: eu-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    APP_ROLE_ARN: ***
    AUTH0_CALLBACK_URL: https://gpc-anomalies-dev.apps.live.cloud-platform.service.justice.gov.uk/callback
    AUTH0_CLIENT_ID: ***
    AUTH0_CLIENT_SECRET: ***
    AUTH0_DOMAIN: alpha-analytics-moj.eu.auth0.com
    AUTH0_PASSWORDLESS: True
    AUTH0_TOKEN_ALG: 
    AUTHENTICATION_REQUIRED: True
    COOKIE_SECRET: 
    ECR_REPO_AUTH0: ***.dkr.ecr.eu-west-2.amazonaws.com/analytical-platform/ap-auth-proxy-prod-ecr
    ECR_REPO_WEBAPP: ***.dkr.ecr.eu-west-2.amazonaws.com/gpc-anomalies-admin-team/***-ecr
    IP_RANGES: ***
    KUBE_NAMESPACE: ***
    NEW_TAG_V: v0.7.1-dev.24
Error: UPGRADE FAILED: context deadline exceeded
Error: Process completed with exit code 1.
```

**Comment by ymao2** [comment]
I am checking

**Comment by ymao2** [comment]
@jhenfrancis ,  checked your app,  2 issues 
- CPU limits:  your app requires more limit on your new PR, bump your CPU limit : suggest CPU limit to 200m,  CPU request limit to 150m 
- Your new PR is having following error 
```
{"level":"info","message":"INFO: (Data scanned: 505 Bytes)\n","service":"shiny.stderr"}
{"level":"info","message":"\nListening on http://127.0.0.1:7999\n","service":"shiny.stderr"}
{"level":"info","message":"Warning: Error in warning_text: could not find function \"warning_text\"\n","service":"shiny.stderr"}
{"level":"info","message":"  96: dots_list\n  95: div\n","service":"shiny.stderr"}
{"level":"info","message":"Warning: Error in warning_text: could not find function \"warning_text\"\n","service":"shiny.stderr"}
{"level":"info","message":"  96: dots_list\n  95: div\n","service":"shiny.stderr"}
```

**Comment by ymao2** [comment]
Highly recommend to follow the guide below to access grafana,  kubectl log and kibana on CP

https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#managing-and-monitoring-deployments

then you can 
1 - monitor your resource usage : e.g. 
https://grafana.live.cloud-platform.service.justice.gov.uk/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=data-platform-app-gpc-anomalies-dev&from=now-3h&to=now
2 - check the error log more efficiently

**Comment by jhenfrancis** [comment]
Thanks @ymao2 . I'll try those and fix the error. How did you get the logs below in that helpful format? Are there specific filters you're using? I had a hard time searching on Kibana:

```
{"level":"info","message":"INFO: (Data scanned: 505 Bytes)\n","service":"shiny.stderr"}
{"level":"info","message":"\nListening on http://127.0.0.1:7999\n","service":"shiny.stderr"}
{"level":"info","message":"Warning: Error in warning_text: could not find function \"warning_text\"\n","service":"shiny.stderr"}
{"level":"info","message":"  96: dots_list\n  95: div\n","service":"shiny.stderr"}
{"level":"info","message":"Warning: Error in warning_text: could not find function \"warning_text\"\n","service":"shiny.stderr"}
{"level":"info","message":"  96: dots_list\n  95: div\n","service":"shiny.stderr"}
```

**Comment by ymao2** [comment]
I made an example for you, then you can use it for next time ( I am not expert either 😊 ),  I agree it is not straightforward to filter the log out 
[app_log](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.namespace_name,negate:!f,params:(query:data-platform-app-gpc-anomalies-dev),type:phrase),query:(match_phrase:(kubernetes.namespace_name:data-platform-app-gpc-anomalies-dev))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.container_name,negate:!f,params:(query:webapp),type:phrase),query:(match_phrase:(kubernetes.container_name:webapp)))),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:'NOT%20log:%20%20%22%2Fhealthz%22'),sort:!()))

next time change the filter below for prod env `data-platform-app-gpc-anomalies-prod` and the time window
<img width="1605" alt="Screenshot 2023-10-23 at 15 38 24" src="https://github.com/ministryofjustice/data-platform-support/assets/26111671/04fa3990-3241-457c-a1f8-9cefc598045d">

**Comment by jhenfrancis** [comment]
Thank you! That was very helpful, really appreciate your help. I've been able to deploy the app successfully so I'll close this issue
