### ISSUE TITLE
AP user guidance and Data Discovery Tool apps appear to be down

### ISSUE THREAD

**Issue by annie-howard** [ministryofjustice/data-platform-support#301]
### What happened?

Data Discovery Tool and AP User guidance apps appear to be down. Other websites load fine so it's not a wifi issue.
![Screenshot 2023-10-24 at 10 25 55](https://github.com/ministryofjustice/data-platform-support/assets/90615915/a4e507a5-e651-43bc-b5da-acba978e13d9)

**Comment by Gary-H9** [comment]
Hi @annie-howard. I'm able to connect to the [guidance](https://github.com/ministryofjustice/data-platform-support/issues/301) without issue. What's the other link you are trying to access and are you connected to the VPN?

**Comment by Gary-H9** [comment]
If [this](https://data-discovery-tool.analytical-platform.service.justice.gov.uk/) is the same link you are using to access data discovery I am able to access this as well which I'm afraid point to a local issue.

**Comment by annie-howard** [comment]
Oh yes connecting to the digital VPN has fixed it. Is that a new requirement? It's not something I've had to do in the past, unless my vpn has always been connected and it's just kicked me out now for some reason

**Comment by Gary-H9** [comment]
Glad to hear it! I believe it should be on by default. I'll close the ticket now, any issues please get back in touch.
