### ISSUE TITLE
Cannot deploy JupyterLab

### ISSUE THREAD

**Issue by jm-campbell** [ministryofjustice/data-platform-support#302]
### Which tool do you need help with?

Control Panel, JupyterLab

### What happened?

I cannot deploy an up-to-date version of JupyterLab. When I click the Deploy button it just says "Failed" every time, regardless of which version I select.

### Relevant log output

```bash
Here's what it says underneath:

Looks like your current deployment (jupyter-lab-2.0.5: v2.0.0) was not recognised within current maintained tool release versions, No worry you can still open it and have a look, then feel free to switch one of versions from above dropdown list.
```

**Comment by Gary-H9** [comment]
Hi @jm-campbell, this was an old version of Jupyter which is no longer supported. We've removed it now, can you try again and let us know the result?

**Comment by jm-campbell** [comment]
Hi @Gary-H9, it still just says Failed when I try to deploy.

**Comment by jm-campbell** [comment]
<img width="1490" alt="Screenshot 2023-10-25 at 09 50 33" src="https://github.com/ministryofjustice/data-platform-support/assets/98318421/c995abc2-5523-4d23-8a31-f1dde6251642">

When I click Deploy it says "Deploying" for a second or two before switching to "Failed".

**Comment by Gary-H9** [comment]
Apologies for the delay @jm-campbell, we've taken some actions on our side, could you try again please?

**Comment by jm-campbell** [comment]
Hi @Gary-H9,

Sorry for the delay on my end, I wasn't working Friday or yesterday.

It works! I now have up-to-date JupyterLab running. Thank you so much for your help!

**Comment by Gary-H9** [comment]
No problem at all @jm-campbell , glad it's sorted now. Apologies this took a bit longer than we desired, it was not a part of our stack that I was fully familiar with. I'll close the issue now, if you have any other problems please get in touch.
