### ISSUE TITLE
Access to an S3 bucket with no owner

### ISSUE THREAD

**Issue by Emmadufty** [ministryofjustice/data-platform-support#305]
### Which tool do you need help with?

S3

### What happened?

Hello,

I've inherited AP projects from someone (Oliver) who left the organisation a few months ago. To run these projects, I require access to the following S3 buckets:

_alpha-ci-trial-forecasting_
_alpha-crown-flow-database_
_alpha-app-crown-flow-explorer_ (this might be a subfolder within alpha-crown-flow-database...?)

Please could I get access to this? 
I have permission from my line manager [@henryk01trent](https://github.com/henryk01trent)

Many thanks,

Emma

**Comment by jacobwoffenden** [comment]
Hey @henryk01trent,

Can you pop a comment on this ticket with your approval

Cheers!

**Comment by henryk01trent** [comment]
Approved

Thanks,
Henryk

**Comment by jacobwoffenden** [comment]
Thanks, @henryk01trent!

@Emmadufty, I've just granted you access to these data sources, let me know if you can't access them,

As Oliver has left, the following data sources require a new admin:

- alpha-crown-flow-database
- alpha-crown-plea-forecasting
- alpha-hmcts-moj-crown-consolidation

**Comment by michaeljcollinsuk** [comment]
@henryk01trent as requested I have made you an admin of:
  *   alpha-crown-flow-database
  *   alpha-crown-plea-forecasting
  *   alpha-hmcts-moj-crown-consolidation

I'll close this issue as resolved now, but please reopen if you need further help with this.
