### ISSUE TITLE
Allow listing issue - Crown Court Performance - new MoJ Internet Egress 

### ISSUE THREAD

**Issue by haroonadalat** [ministryofjustice/data-platform-support#307]
### Which tool do you need help with?

User and Account

### What happened?

A project is underway to migrate DOM1 users away from Atos proxied internet access onto the MoJ Internet Gateway. A user of Crown Court Performance has reported an allow listing block page, as they are on the new internet egress pilot. 
![image](https://github.com/ministryofjustice/data-platform-support/assets/98106318/fa14bc91-9cdd-40a7-a54c-81aa6bd7a98a)

Can the following IP's be allow listed in the MoJ AP:
moj_official:
  production:
    # MoJO Production Account BYOIP CIDR range
    - 51.149.250.0/24
    # ARK Corsham Internet Egress Exponential-E
    - 51.149.249.0/29
    # ARK Corsham Internet Egress Vodafone
    - 194.33.249.0/29
    # ARK Corsham Internet Egress Exponential-E
    - 51.149.249.32/29
    # ARK Corsham Internet Egress Vodafone
    - 194.33.248.0/29
    # Azure Landing Zone Egress
    - 20.49.214.199/32
    - 20.49.214.228/32
    - 20.26.11.71/32
    - 20.26.11.108/32

These are from https://github.com/ministryofjustice/moj-ip-addresses/blob/main/moj-cidr-addresses.yml

Thanks,

Haroon

**Comment by bagg3rs** [comment]
@haroonadalat 👋 Should those ARK addresses be `/24`?

**Comment by haroonadalat** [comment]
> @haroonadalat 👋 Should those ARK addresses be `/24`?

@bagg3rs I've seen that /24 quoted in different places, but was using what looked to be a canonical page for copynpaste which stated /29. I'm seeing /24 referenced in VF documentation as well

**Comment by bagg3rs** [comment]
Thanks I think that must be the management or other range so we will update our ranges to 24 and I will raise that change on the CIDR repo.

**Comment by michaeljcollinsuk** [comment]
@bagg3rs to confirm, should I create new IP allowlists for the following:

# MoJO Production Account BYOIP CIDR range
51.149.250.0/24

# ARK Corsham Internet Egress Exponential-E
51.149.249.0/24
51.149.249.32/24

# ARK Corsham Internet Egress Vodafone
194.33.249.0/24
194.33.248.0/24

# Azure Landing Zone Egress
20.49.214.199/32
20.49.214.228/32
20.26.11.71/32
20.26.11.108/32

I was thinking of adding these as four new lists, that then can be applied to this app specifically. Rather than update the existing DOM1 allowlist, which would apply the changes to all apps that use this allowlist. What do you think?

**Comment by bagg3rs** [comment]
@michaeljcollinsuk 👍

**Comment by michaeljcollinsuk** [comment]
@bagg3rs I was unable to add IP `51.149.249.32/24` as this failed validation:
```
51.149.249.32/24 should be an IPv4 or IPv6 address
```
FYI `51.149.249.32/29` is already included in one of the

**Comment by bagg3rs** [comment]
Oh yes change .32 to 0/24 for the whole range

**Comment by michaeljcollinsuk** [comment]
@haroonadalat I have added the new IP ranges so that app admins can now apply these themselves via control panel as required. If individual users are having issues accessing a particular app, ask them to get in touch with the app admin so that they can update the allowed IP's for their app.
