### ISSUE TITLE
Unable to install packages in to a new project

### ISSUE THREAD

**Issue by crew1512** [ministryofjustice/data-platform-support#310]
### Which tool do you need help with?

Control Panel

### What happened?

I'm starting a new project in R via the AP and at the moment, am unable to load any packages I would normally be fine loading in. Simple packages like "renv" and "tidyverse". I get this message:
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpkXUOpZ/downloaded_packages’

However, there is no package installed and it doesn't appear in the library! 

Maybe it's Friday and my brain is a bit mashed, but I've done this many times before with other projects and experienced no issues. No settings have been changed within my R either. 

### Relevant log output

```bash
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpkXUOpZ/downloaded_packages’
```

**Comment by michaeljcollinsuk** [comment]
It may be that there is an issue with your session, please try following the steps detailed here to clear your session and restart Rstudio https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/#clearing-your-rstudio-session. Let me know if this resolves your issue. Thanks

**Comment by crew1512** [comment]
Hi, I'm still getting this error. I've restarted everything and it's finally allowed me to install and load renv but it won't allow me to do anything else: 

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

**Comment by michaeljcollinsuk** [comment]
The error shared seems to be the same that this user reported in https://github.com/rstudio/renv/issues/981. Its unclear from reading that what causes the issue, but [see this comment](https://github.com/rstudio/renv/issues/981#issuecomment-1136149575) for a proposed solution.

As suggested, could you try opening your `.Rprofile` file and removing the `source("renv/activate.R")` line, then trying to install packages again?
