### ISSUE TITLE
Access to S3 buckets

### ISSUE THREAD

**Issue by jtattersall09403** [ministryofjustice/data-platform-support#312]
### Which tool do you need help with?

S3

### What happened?

Please could you grant me access to the following S3 buckets? I am the team lead for the apps that use these buckets and need access so I can work on the apps. The admin is currently on leave. Thanks!
- alpha-prison-network-app
- alpha-app-bentham-app
- alpha-app-drug-conveyancing
- alpha-app-prison-visitor-app

**Comment by jhpyke** [comment]
@miller-william you are listed as an admin on all of the above buckets - can you give the above user access (assuming you approve of their request)?

**Comment by miller-william** [comment]
Done

**Comment by jhpyke** [comment]
Closed with access provided to user
