### ISSUE TITLE
Brief description of your issue

### ISSUE THREAD

**Issue by KellyAmpleford** [ministryofjustice/data-platform-support#314]
### Which tool do you need help with?

User and Account

### What happened?

I have been unable to access the analytics platforms which i regularly use. Please can this be re instated please. 

Many thanks
Kelly

**Comment by michaeljcollinsuk** [comment]
Hi @KellyAmpleford I've checked and you are not a member of the MoJ Analytical Services organisation, which is the first step to accessing the AP. Not clear when/why you would have been removed, did you change github accounts perhaps? You will need to reregister, please follow the steps in the user guidance under "Access the Analytical Platform" https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#4-access-the-analytical-platform
