### ISSUE TITLE
Re-access to analytic platform

### ISSUE THREAD

**Issue by SarahHassan20** [ministryofjustice/data-platform-support#315]
### Which tool do you need help with?

RStudio

### What happened?

I am no longer able to access the analytic platform as my account was deactivated due to inactivity. 
I now require access again to continue work on a research project.

**Comment by michaeljcollinsuk** [comment]
@SarahHassan20 you will need to make a request to rejoin the MOJ Analytical Services organisation, and then try to log in to the Control Panel. Please see steps in the user guidance https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#join-moj-analytical-services
