### ISSUE TITLE
Two-factor authentication AP reset

### ISSUE THREAD

**Issue by rezia-k** [ministryofjustice/data-platform-support#318]
### Which tool do you need help with?

User and Account

### What happened?

Hello,
Please could you reset the two-factor authentication on my AP account? 
I've recently changed my phone and would like to use the authenticator app on the new phone.

**Comment by bagg3rs** [comment]
@rezia-k I have sent a reset request

**Comment by rezia-k** [comment]
Thank you, it has worked
