### ISSUE TITLE
gpc-anomalies app greying out/connection issues

### ISSUE THREAD

**Issue by jhenfrancis** [ministryofjustice/data-platform-support#320]
### Which tool do you need help with?

Application Migration Support

### What happened?

I've noticed a few issues with the app deployed on dev (we are yet to update prod) regarding re-establishing connections:

- App greys out unexpectedly after a session has started.
- Filters will reset to default values when reconnection occur which is an issue fir the data filtered using these filters and stored in reactive objects before being rendered in datatables.
- Users will be editing tables and saving changes that are sent to iceberg tables, therefore issues like this can result in edits being lost before the user saves their edits.

This is similar to some of the issues discovered in the gold-scorecard-form app.

**Comment by bagg3rs** [comment]
@jhenfrancis we have another issue which lists other apps that have this issue [here](https://github.com/ministryofjustice/data-platform/issues/1826)
Could we try testing in your development with the open-source shiny-server? and to see if that improves?

**Comment by jhenfrancis** [comment]
> @jhenfrancis we have another issue which lists other apps that have this issue [here](https://github.com/ministryofjustice/data-platform/issues/1826) Could we try testing in your development with the open-source shiny-server? and to see if that improves?

Yes please!

**Comment by bagg3rs** [comment]
Ok we need to raise a PR will that cause you any problems with your current testing?

**Comment by jhenfrancis** [comment]
Thanks @bagg3rs sorry for the delay, we had a PR in progress that we wanted to get over the line first. That's approved and merged now so I'm happy for you to raise the PR

**Comment by michaeljcollinsuk** [comment]
Hi @jhenfrancis we have now updated the user guidance to [add documentation on the different options available for apps using shiny server](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#shiny-server), which include [instructions on how to change to switch to the open-source image](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#instructions-for-switching-from-the-ap-shiny-server-to-the-open-source-server). So when you are ready, please follow the steps to create a PR to deploy to dev so you can test. Please reply here with any questions/feedback

**Comment by jhenfrancis** [comment]
Thanks @michaeljcollinsuk. I'll give it a go and then test today/tomorrow

**Comment by jhenfrancis** [comment]
@michaeljcollinsuk the app deployed successfully with the open-source image. We'll do some testing on the deployed app tomorrow to check out the reconnection/session management features.

I have a question, in [Open source shiny-server](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#open-source-shiny-server) it says that it supports `USER_EMAIL`. This is something that we want to add to the app. Based on the AP guidance it says that I can get this using `get("HTTP_USER_EMAIL", envir=session$request)`. However this doesn't give the user email, I get an error and  in the logs, the error is `Warning: Error in get: object 'HTTP_USER_EMAIL' not found`. Am I missing something? 

**Initial feedback**: 
- The guidance was very easy to follow
- There is a typo in the [AP version of shiny-server](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#ap-version-of-shiny-server) : Create a new session for each new websocket **conneciton**

**Comment by michaeljcollinsuk** [comment]
@jhenfrancis thanks for the feedback.

I've had a look into the issue with the user email header not working, is it ok for us to push some changes to attempt to debug? We will only do this on the dev environment. Thanks

**Comment by michaeljcollinsuk** [comment]
@jhenfrancis we found the issue - the user email was not available in the version of the auth proxy that your app was using. We've updated this to use the latest version ([see commit here](https://github.com/ministryofjustice/gpc-anomalies/pull/54/commits/7fec90605e5b6b741f9e1b071a5edee45683499b#)) and now the user email is displayed after login on the dev site (be sure to logout of the app and log back in when you test).

I've updated the [user guidance to reflect this](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#finding-current-users-39-email-addresses), as well as fix the typo - thanks for catching that!

Are you happy for me to close the issue now? Thanks

**Comment by jhenfrancis** [comment]
Thanks @michaeljcollinsuk  that works and the user guidance is very clear on this too - thanks for adding that in. I'm happy for you to close but I've asked a couple people to test the 'grey out' early next week so if we discover any issues with that should I re-open this issue or open a new one?

**Comment by michaeljcollinsuk** [comment]
Feel free to reopen if there are any issues, as that way I will be notified. Thanks
