### ISSUE TITLE
Add new DE to Github organisation

### ISSUE THREAD

**Issue by gustavmoller** [ministryofjustice/data-platform-support#321]
### Which tool do you need help with?

User and Account

### What happened?

Hello, 

please can @Khristiania Raihan be added to data_engineering_aws_members in https://github.com/ministryofjustice/data-platform/blob/main/terraform/github/data-platform/teams.tf.

Her Github username is `kraihanmoj`

**Comment by jacobwoffenden** [comment]
Hey @gustavmoller,

I've add @kraihanmoj to @ministryofjustice/data-engineering-aws and the teams I mentioned on [Slack](https://mojdt.slack.com/archives/CBVUV2613/p1698927664906489)
