### ISSUE TITLE
Can't preview code in Athena

### ISSUE THREAD

**Issue by jforster75** [ministryofjustice/data-platform-support#324]
### What happened?

I am trying to preview databases in Athena but am getting the following error in the Query output when I try `Unable to verify/create output bucket alpha-jf-testing`. jf-testing was an old bucket I set up ages ago as a test so I'm not sure why that is happening and the query I'm running, for completeness, is `SELECT * FROM "hocas_derived"."defendant_summary_fct" limit 10;`

### Relevant log output

```bash
`Unable to verify/create output bucket alpha-jf-testing`
```

**Comment by BrianEllwood** [comment]
Hi @jforster75  we do not support Athena please raise this with [data-engineering](https://mojdt.slack.com/archives/CBVUV2613)

**Comment by BrianEllwood** [comment]
issue for data engineering
