### ISSUE TITLE
Upgrade the Helm chart failing

### ISSUE THREAD

**Issue by glenn-christmas** [ministryofjustice/data-platform-support#325]
### Which tool do you need help with?

RStudio

### What happened?

https://github.com/ministryofjustice/ccmbpt-analytics-app/actions/runs/6748605907/job/18347461071

Hello, I have attempted to make a small innocuous change to the `ccmbpt-analytics-app` as I managed to cause a problem earlier in the afternoon by forgetting to add a package (`future`) to the `renv.lock` file when creating a PR, and whatever I've done since then (loading the package and performing `renv::snapshot()` or in this case making an innocuous change from `main` that doesn't require `future`) results in an error message saying `Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress` and the Kibana logs saying `there is no package called 'future'`.

I suspect I've managed to break this and it needs some sort of reset? Could this please be amended if so.

Also - if there are any pointers on how we can fix these issues in future, that'd be much appreciated!

Thanks,

Glenn

### Relevant log output

```bash
{"level":"info","message":"Error in library(future) : there is no package called ‘future’\nCalls: <Anonymous> ... sourceUTF8 -> eval -> eval -> ..stacktraceon.. -> library\n","service":"shiny.stderr"}
```

**Comment by murad-ali-MoJ** [comment]
Hi @glenn-christmas, your current deployment has been rolled back, and we request you to redeploy again.

**Comment by michaeljcollinsuk** [comment]
For future reference within the team, the command used to rollback the helm deploying:
```
helm rollback ccmbpt-analytics-app-dev -n data-platform-app-ccmbpt-analytics-app-dev
```
