### ISSUE TITLE
RStudio doesn't load (takes long time then grey screen)

### ISSUE THREAD

**Issue by andrewc-moj** [ministryofjustice/data-platform-support#326]
### What happened?

When trying to load RStudio I get a message "R is taking longer than usual".  Eventually this message disappears and I'm left with a grey screen.

I have tried 'reload', 'safe mode' and 'terminate r' as well as restart and deploying other installations with no luck.

**Comment by murad-ali-MoJ** [comment]
@andrewc-moj, could you please reset the home directory using the instructions [link](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/#clearing-your-rstudio-session)? This action won't result in any data loss. Thank you

**Comment by andrewc-moj** [comment]
Brilliant. I did see this but was worried about loss of local scripts.  Happy for you to close
