### ISSUE TITLE
Can't access control panel - resetting session doesn't help

### ISSUE THREAD

**Issue by fwake** [ministryofjustice/data-platform-support#329]
### What happened?

I haven't used the AP in a few months (probably since June) and I am unable to log in/access the control panel. I am trying to access RStudio, but I am being sent around in circles to the control panel log in page and error page and the usual things I would do aren't helping. I'm wondering whether my account might have migrated since I last used it?

Thanks for your help

### Relevant log output

```bash
There is a problem with your session
It might have timed out in which case you can [reset your session ](https://alpha-analytics-moj.eu.auth0.com/v2/logout?returnTo=https%3A%2F%2Fcontrolpanel.services.analytical-platform.service.justice.gov.uk%2Foidc%2Flogout%2F), and login again.

If resetting your session doesn't help, it's possible that

You may need to ensure you are in the [MoJ Analytical Services](https://github.com/moj-analytical-services) team on GitHub.
You may have migrated to a newer version of the platform, so your account on this version is no longer available.
Alternatively, please refer to our guide for [getting started on the Analytical Platform](https://user-guidance.services.alpha.mojanalytics.xyz/get-started.html) for more information.
```

**Comment by bagg3rs** [comment]
@fwake you are not in the Analytical Services GitHub Org anymore, you will need #ask-operations-engineering [here](https://mojdt.slack.com/archives/C01BUKJSZD4) to add you back
