### ISSUE TITLE
Email login error for R Shiny apps

### ISSUE THREAD

**Issue by joeprinold** [ministryofjustice/data-platform-support#335]
### Which tool do you need help with?

Application Migration Support, Auth0, User and Account

### What happened?

When users are logging into our apps (using the NOMIS Auth system) the ID that is sent to the apps seems to have changed. This means that the app no longer recognises the user and they are therefore not able to login. 

One solution is that we figure out the new IDs for each user and add those IDs to the access list that we store in s3, but that would be prohibitively time consuming for hundreds of users. The other solution would be that we re associated that email login with the user ID that it belongs to.

For example mqc90u has changed to 84d18e19-daca-4f13-9e59-110696fd6291 and ld005656 has changed to a1ce145d-ab35-4da6-a924-bf015e47c019.

**Comment by michaeljcollinsuk** [comment]
Hi @joeprinold we have done some investigating, and it appears that the user ID that is returned is different when logging in with AzureAD. Therefore there are a couple of options available to you:

1. In your app check if the `auth_source` is `azuread`, then check the user based on the `user_id`

**Comment by michaeljcollinsuk** [comment]
Hi @joeprinold how does the app retrieve these ID's? Am I correct in thinking that you are stripping the ID from the `HTTP_USER_EMAIL` header? E.g. https://github.com/ministryofjustice/prison-network-app/blob/62b21ef946b152af7edf15288242be8e5d7c432f/server.R#L20

**Comment by joeprinold** [comment]
Yes, that's where the user ID is coming from.

**Comment by michaeljcollinsuk** [comment]
Thanks for confirming. After investigating we have found that the value used in the email header will be different when a user logs in with Azure AD. There are a couple of options, for both you will need to make use of the `/userinfo` endpoint that is [documented in the user guidance here](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#finding-current-users-39-user-profiles), and use details from the response.

Option 1 - call HMPPS Api to get the users username
- An `_accessToken` is included in the response from the `/userinfo` endpoint. 
- Within your app, retrieve the access token and use it to call the HMPPS Manage Users API `/users/me` endpoint, which as per the HMPPS docs will return their username which you can then check against your access list
- Some useful links:
  - [HMPPS Manage Users API documentation](https://manage-users-api.hmpps.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/user-controller/myDetails)
  - Example of another app, that retrieves the `_accessToken` and then uses it to make a subsequent call to ahttps://github.com/ministryofjustice/safety-diagnostic-tool/blob/main/server.R#L37

Option 2 - parse the users email from the `/userinfo` response to authenticate against

- Depending on the auth source, you will need to check either the `user_id` or `username` values in the reponse
- Check the `auth_source` from the response
  - If it is `azuread`, check the `user_id` field - this will look something like `"oauth2|intel-app|example@justice.gov.uk"`. Parse the email from this string, and then use it to check against your access list that you store in S3.
  - If the `auth_source` is `nomis` then you can use the `username` value, which will be the username you expect currently when parsing the user email header e.g. `MQC90U`
