### ISSUE TITLE
access to alpha-mojap-curated-xhibit

### ISSUE THREAD

**Issue by BayleyCartmell** [ministryofjustice/data-platform-support#338]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I need access to the s3 bucket but don't know the admin to ask for permission.

### Relevant log output

```bash
Error: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: XKNFNB31KYGR24SC; S3 Extended Request ID: pXdq3Mwjukztmjk0xYRvqg2/mg5tenw/+q+pAg90CEH78i1Cc+3Pgg62t1fAo0Y/z/NXFyJOV4/W9ULxBzh1nw==; Proxy: null), S3 Extended Request ID: pXdq3Mwjukztmjk0xYRvqg2/mg5tenw/+q+pAg90CEH78i1Cc+3Pgg62t1fAo0Y/z/NXFyJOV4/W9ULxBzh1nw== (Bucket: alpha-mojap-curated-xhibit, Key: dev_v3/xhibit_der_ath/defendant_summary/defendant_summary/defendant_summary/mojap_snapshot_date=2023-10-25/)
```

**Comment by julialawrence** [comment]
Hiya, would you mind pinging this question into #ask-data-engineering? Unfortunately, we are not really able to identify a new owner but some people in that channel might have a better idea.

**Comment by BayleyCartmell** [comment]
Is that on the Slack channel?

**Comment by julialawrence** [comment]
Indeed it is.

**Comment by julialawrence** [comment]
#ask-data-engineering is the slack chanel.

**Comment by Gary-H9** [comment]
Closing, please re-open if needed!
