### ISSUE TITLE
HLT Performance & Assurance Portal is showing a red error message on certain pages

### ISSUE THREAD

**Issue by AimeeYMellor** [ministryofjustice/data-platform-support#339]
### Which tool do you need help with?

MoJ Cloud Platform

### What happened?

The HLT Performance & Assurance Portal is showing a red error message with the following: 

**"Error: An error has occurred. Check your logs or contact the app author for clarification"** 

This is happening under certain key messages where text should show. This is happening under the Prison, Probation and YCS Key Messages. 

Link for Portal: https://hlt-portal.apps.live.cloud-platform.service.justice.gov.uk/

**Comment by Gary-H9** [comment]
Hi @AimeeYMellor, the logs are available [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/logging-an-app/access-logs.html#accessing-application-log-data). Please get in touch with the app owner in relation to application errors. It will also be helpful to them to add a screenshot of the errors for troubleshooting purposes. If you/they believe there is an issue relating to the platform itself please let us know.

**Comment by Gary-H9** [comment]
Hi @AimeeYMellor - not sure I can help with the issue given my lack of knowledge about the app but to attach a file to an issue or pull request conversation, drag and drop it into the comment box. Alternatively, you can click in the formatting bar above the comment box to browse, select, and add a file from your computer.

Additionally include all other steps which you have taken to troubleshoot your application. Please include any logs which you've looked at in this output.

**Comment by Gary-H9** [comment]
Morning, one of my colleagues looked at the logs located [here](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.namespace_name,negate:!f,params:(query:data-platform-app-hlt-portal-prod),type:phrase),query:(match_phrase:(kubernetes.namespace_name:data-platform-app-hlt-portal-prod))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.container_name,negate:!f,params:(query:webapp),type:phrase),query:(match_phrase:(kubernetes.container_name:webapp)))),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:'NOT%20log:%20%20%22%2Fhealthz%22'),sort:!())) and noted this error:

```
2023-11-16 10:34:59.180	{"level":"info","message":"Warning: Error in packageVersion: there is no package called 'markdown'\n","service":"shiny.stderr"}
	2023-11-16 10:34:58.481	{"level":"info","message":"Warning: Error in packageVersion: there is no package called 'markdown'\n  101: <Anonymous>\n  100: stop\n   99: packageVersion\n   98: includeMarkdown\n   97: renderUI [/srv/shiny-server/server.R#123]\n   96: func\n   83: renderFunc\n   82: output$osag_probation_headlines\n    1: shiny::runApp\nWarning: Error in packageVersion: there is no package called 'markdown'\n  101: <Anonymous>\n  100: stop\n   99: packageVersion\n   98: includeMarkdown\n   97: renderUI [/srv/shiny-server/server.R#138]\n   96: func\n   83: renderFunc\n   82: output$performance_probation_headlines\n    1: shiny::runApp\n","service":"shiny.stderr"}
```
Most notably I think `Error in packageVersion: there is no package called 'markdown'` a good start to working on this would be to add this package to `renv.lock`.
