### ISSUE TITLE
havent got up to date link for the platform to access the apps needed 

### ISSUE THREAD

**Issue by oqa40y** [ministryofjustice/data-platform-support#341]
### What happened?

I just need an up to date link to be able to access the intel apps  - i have been off for 1 year and everything has changed to get into things

**Comment by bagg3rs** [comment]
@oqa40y the new URL can be found [here](https://mojdt.slack.com/archives/C4PF7QAJZ/p1700131237271099?thread_ts=1700127013.184709&cid=C4PF7QAJZ)
