### ISSUE TITLE
Access to tool

### ISSUE THREAD

**Issue by sjrobertson** [ministryofjustice/data-platform-support#343]
### What happened?

Trying to access the tool, as we are designing the DPS screens for Incident Reports - and wanting to learn what parts of NOMIS Incident Reports are connected to these analytics screens

### Relevant log output

```bash
I would like access to this tool asap. My digital justice email address is: stephen.robertson@digital.justice.gov.uk
```

**Comment by bagg3rs** [comment]
@sjrobertson Do you mean the Analytical Platform and the tools on there? 
If so please see guidance [here](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html)
