### ISSUE TITLE
Can't access the Analytical Platform

### ISSUE THREAD

**Issue by mattjpalmer** [ministryofjustice/data-platform-support#344]
### Which tool do you need help with?

Control Panel

### What happened?

I was removed from the Github organisation for inactivity but now I've been re-added and am trying to access the Analytical Platform. When I go to the website for the control panel I just get the following message:

"**Sorry, there is a problem with the service**
Try again later.

Contact the Analytical Platform team if you need to make urgent changes to your webapps or data sources."

**Comment by bagg3rs** [comment]
@mattjpalmer can you try logging out here https://controlpanel.services.analytical-platform.service.justice.gov.uk/oidc/logout/

**Comment by mattjpalmer** [comment]
When I log back in again it just goes back to the same message

**Comment by bagg3rs** [comment]
@mattjpalmer Could you try accessing Control Panel with a [Private](https://support.microsoft.com/en-us/microsoft-edge/browse-inprivate-in-microsoft-edge-cd2c9a48-0bc4-b98e-5e46-ac40c84e27e2) browser session.

**Comment by mattjpalmer** [comment]
I still get the same message in a private session

**Comment by bagg3rs** [comment]
OK thank, just to check you haven't changed your github username?

**Comment by mattjpalmer** [comment]
Nope, still the same username

**Comment by bagg3rs** [comment]
@mattjpalmer Can you try logging in again now. I have cleared some settings

**Comment by mattjpalmer** [comment]
Thank you very much! It's working now
