### ISSUE TITLE
App redeployment failure and CPU Limit Low

### ISSUE THREAD

**Issue by rosskeegan** [ministryofjustice/data-platform-support#345]
### What happened?

I pushed and tried to merge the branch ltc-capabilites-app/test3. Though this has failed at the Upgrade Helm Chart Stage. I haven't much of an idea as to why, considering the differences between the main branch and the test3 branch are virtually non-existent. 

 The other issue I am facing is that the App which is currently deployed is exceptionally sluggish. In conversation with one of the members of my team with their own app they noted that my CPU Requests Limit was very low in comparison to theirs and that this might drive the sluggishness.

Any help would be appreciated

### Relevant log output

```bash
Run process_ip_range=$(echo $IP_RANGES | sed "s/,/\\\,/g")
  process_ip_range=$(echo $IP_RANGES | sed "s/,/\\\,/g")
  
  helm upgrade --install --wait --timeout 10m0s --namespace $KUBE_NAMESPACE $KUBE_NAMESPACE mojanalytics/webapp-cp \
  --set AuthProxy.Env.Auth0Domain=$AUTH0_DOMAIN \
  --set AuthProxy.Env.Auth0Passwordless=$AUTH0_PASSWORDLESS \
  --set AuthProxy.Env.Auth0TokenAlg=$AUTH0_TOKEN_ALG \
  --set AuthProxy.Env.AuthenticationRequired=$AUTHENTICATION_REQUIRED \
  --set AuthProxy.Env.IPRanges=$process_ip_range \
  --set AuthProxy.Image.Repository=$ECR_REPO_AUTH0 \
  --set AuthProxy.Image.Tag="v5.3.3" \
  --set Namespace=$KUBE_NAMESPACE \
  --set Secrets.Auth0.ClientId=$AUTH0_CLIENT_ID \
  --set Secrets.Auth0.ClientSecret=$AUTH0_CLIENT_SECRET \
  --set Secrets.Auth0.CookieSecret=$COOKIE_SECRET \
  --set ServiceAccount.RoleARN=$APP_ROLE_ARN \
  --set WebApp.Image.Repository=$ECR_REPO_WEBAPP \
  --set WebApp.Image.Tag=$NEW_TAG_V \
  --set WebApp.Name=$KUBE_NAMESPACE
  shell: /usr/bin/bash -e {0}
  env:
    AWS_DEFAULT_REGION: eu-west-2
    AWS_REGION: eu-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    APP_ROLE_ARN: ***
    AUTH0_CALLBACK_URL: https://ltc-capabilites-app-dev.apps.live.cloud-platform.service.justice.gov.uk/callback
    AUTH0_CLIENT_ID: ***
    AUTH0_CLIENT_SECRET: ***
    AUTH0_DOMAIN: alpha-analytics-moj.eu.auth0.com
    AUTH0_PASSWORDLESS: True
    AUTH0_TOKEN_ALG: 
    AUTHENTICATION_REQUIRED: True
    COOKIE_SECRET: 
    ECR_REPO_AUTH0: ***.dkr.ecr.eu-west-2.amazonaws.com/analytical-platform/ap-auth-proxy-prod-ecr
    ECR_REPO_WEBAPP: ***.dkr.ecr.eu-west-2.amazonaws.com/ltc-capabilites-app-admin-team/***-ecr
    IP_RANGES: ***
    KUBE_NAMESPACE: ***
    NEW_TAG_V: v0.0.16-dev.106
Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "ltc-capabilites-app-dev.apps.live.cloud-platform.service.justice.gov.uk" and path "/" is already defined in ingress ***/***
Error: Process completed with exit code 1.
```

**Comment by Emterry** [comment]
HI Ross Ive just been looking at the above issue, I have an idea of what the issue might be, but it will require the app to be down for the duration of redeploying the helm chart. This can vary in time usually a couple of minutes but cant guarantee that.  When would be ok to do this?

**Comment by rosskeegan** [comment]
Hey, yes happy for it to be down for a bit. Shouldn't cause too much of an issue. Thanks for your help.

**Comment by rosskeegan** [comment]
Sorry for the delay, that's it merged with main, just waiting on prod deployment finishing up

**Comment by rosskeegan** [comment]
prod deployment failed trying to build and push new image? Wasn't expecting that:


 Dockerfile:10
--------------------
   9 |     # Install python3 and essentials
  10 | >>> RUN apt-get update \
  11 | >>>   && apt-get install -y --no-install-recommends \
  12 | >>>     libglpk-dev \
  13 | >>>   && apt-get install -y \
  14 | >>>     python3 \
  15 | >>>     python3-pip \
  16 | >>>     python3-venv \
  17 | >>>     python3-dev
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update   && apt-get install -y --no-install-recommends     libglpk-dev   && apt-get install -y     python3     python3-pip     python3-venv     python3-dev" did not complete successfully: exit code: 100
Error: Process completed with exit code 1.

**Comment by rosskeegan** [comment]
dev deployment is working great though and is WAY quicker than previously. So thats a huge plus :)

**Comment by rosskeegan** [comment]
Feel free to do so whenever, I have let the users know it might go down as the issue is getting resolved so wont be an issue :) Thanks for the update, fingers crossed! haha

**Comment by Emterry** [comment]
HI Ross seems to all be working from my end let me know if any issues your side. The helm chart is now deployed in prod

**Comment by rosskeegan** [comment]
All good on my end, access worked out, everything seems to be working great! Thanks a bundle for the help, is there anything I should note for the next time I need to re-deploy that might come up?

**Comment by Emterry** [comment]
HI Ross great, there was an update to the helm chart 5 months ago - i think its just a case that it hadnt been run since this change and the ingress needed to be deleted and recreated. It shouldnt cause any future issues.
