### ISSUE TITLE
Reset 2FA

### ISSUE THREAD

**Issue by df-just** [ministryofjustice/data-platform-support#356]
### Acknowledgements

- [X] I have searched the [user guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html) and cannot find a solution.
- [X] I have searched for a similar [issue](https://github.com/ministryofjustice/data-platform-support/issues) and cannot find one.
- [X] I acknowledge that the Data Platform Apps and Tools team are not responsible for the _application code_ deployed on the Cloud Platform and this is the responsibility of the application owner. I have already contacted the application owner and they have confirmed that this is not an application issue.
- [X] I have not included sensitive information in this request.

### Which tool do you need help with?

Auth0

### What happened?

Hi, I've switched phones and need my 2FA resetting, my GitHub username is: **df-just**

### Logs

- [X] I have searched the logs which are provided below.

**Comment by ymao2** [comment]
@df-just , done

**Comment by df-just** [comment]
Thanks, that's sorted it
