### ISSUE TITLE
Add new team member on courts reoffending project

### ISSUE THREAD

**Issue by vpascamoj** [ministryofjustice/data-platform-support#358]
### Acknowledgements

- [X] I have searched the [user guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html) and cannot find a solution.
- [X] I have searched for a similar [issue](https://github.com/ministryofjustice/data-platform-support/issues) and cannot find one.
- [X] I acknowledge that the Data Platform Apps and Tools team are not responsible for the _application code_ deployed on the Cloud Platform and this is the responsibility of the application owner. I have already contacted the application owner and they have confirmed that this is not an application issue.
- [X] I have not included sensitive information in this request.

### Which tool do you need help with?

Database Access, User and Account

### What happened?

Please can 
[@richard.mccormack1](https://asdslack.slack.com/team/U01FF21CEDT)
 (github username r-mccormack) please be added to the court.reoffending teams to be able to gain access, read and write (admin) to the courts.reoffending and courts.reoffending.pipeline repos?

### Logs

- [X] I have searched the logs which are provided below.

**Comment by Gary-H9** [comment]
Hi @vpascamoj can you please ask this in [#ask-operations-engineering](https://mojdt.slack.com/archives/C01BUKJSZD4)? They are now responsible for that organisation. I'll close this ticket but if you hit any issues please re-open.
