### ISSUE TITLE
AP 2FA reset

### ISSUE THREAD

**Issue by yznlp** [ministryofjustice/data-platform-support#359]
### Acknowledgements

- [X] I have searched the [user guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html) and cannot find a solution.
- [X] I have searched for a similar [issue](https://github.com/ministryofjustice/data-platform-support/issues) and cannot find one.
- [X] I acknowledge that the Data Platform Apps and Tools team are not responsible for the _application code_ deployed on the Cloud Platform and this is the responsibility of the application owner. I have already contacted the application owner and they have confirmed that this is not an application issue.
- [X] I have not included sensitive information in this request.

### Which tool do you need help with?

Auth0

### What happened?

Hi. I got a new phone and I'd like to reset my 2FA so I can set it up on the new phone please. 

### Logs

- [X] I have searched the logs which are provided below.

**Comment by Gary-H9** [comment]
Hi @yznlp I've reset MFA for your account in Control Panel. If there's anything else needed please let me know. I'll close the ticket shortly if all is well :)
