### ISSUE TITLE
Unable to access AWS s3 - just showing white screen!

### ISSUE THREAD

**Issue by rob-mcnaughter** [ministryofjustice/data-platform-support#360]
### Acknowledgements

- [X] I have searched the [user guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html) and cannot find a solution.
- [X] I have searched for a similar [issue](https://github.com/ministryofjustice/data-platform-support/issues) and cannot find one.
- [X] I acknowledge that the Data Platform Apps and Tools team are not responsible for the _application code_ deployed on the Cloud Platform and this is the responsibility of the application owner. I have already contacted the application owner and they have confirmed that this is not an application issue.
- [X] I have not included sensitive information in this request.

### Which tool do you need help with?

Amazon Web Services

### What happened?

Hi, when I try to access s3 from the AWS Console, I sometimes get just a white screen, apart from a thin dark blue/black strip at the top containing the was logo, menu links, a search bar, and other links to things like settings.  Apart from this the whole screen is white.  I've intermittently had this problem since joining about 7 months ago, where sometimes it works fine and sometimes not.  Please see attached image (although there isn't much to see)

### Screenshot

![s3-screenshot](https://github.com/ministryofjustice/data-platform-support/assets/129972181/38628b55-6c1e-44d0-b8ae-8534817c7eff)

### Logs

- [X] I have searched the logs which are provided below.

**Comment by Gary-H9** [comment]
Hi @rob-mcnaughter - that is very odd. Not something I've seen before and not something I'm entirely sure I can help with. 

Does this occur on browsers other than Safari? I use Arc and Chrome and haven't seen this occurring. 

I would suggest some stuff but I'm sure you've already done these: 
- If you're familiar with browser developer tools, check the console for any JavaScript errors or warnings that might indicate what's going wrong.
- clear your cache and cookies.
- make sure your browser is up to date.
- worst case, try an alternate browser for a period. 

If this is really effecting your workflow then I'd suggest potentially raising a case with AWS.

Apologies this is not the most helpful response but this is outwith our control.

**Comment by Gary-H9** [comment]
User reports via Slack: "Thanks for the suggestions!  I've tried all the above with no luck, but it seems to work in google chrome.  Using chrome works for me though!"
