### ISSUE TITLE
I would like access to the Segmentation tool 

### ISSUE THREAD

**Issue by R976422** [ministryofjustice/data-platform-support#361]
### Which tool do you need help with?

GitHub

### What happened?

I have created an account and would like access to the Segmentation tool.

**Comment by Emterry** [comment]
Hi to access the segmentation tool your need to be added by an app owner who I am tagging in this support issue @lhan1825 @susanbaron who should be able to help further. Thank you

**Comment by lhan1825** [comment]
Hi,
Thank you for your request.
You can contact Segmentation-Requests@justice.gov.uk to request access to the segmentation tool.

Thank you

**Comment by jacobwoffenden** [comment]
Thanks @lhan1825!

@R976422 we'll close this issue now, but if you need any further assistance with Analytical Platform, please raise a new issue.

Thanks!
