### ISSUE TITLE
Local app not running

### ISSUE THREAD

**Issue by w-wood** [ministryofjustice/data-platform-support#51]
### Which tool do you need help with?

Control Panel, JupyterLab

### What happened?

Hi, I'm trying to run a python dash app locally on the AP but when I try to launch the app on the terminal it produces no error messages but just drops back to the waiting prompt.  I tried using both JupyterLab versions that have Tunnel installed but both do the same thing.  We've made no recent code changes, so could this be an AP issue or has there been a change in the way the tunnel work?  Thanks.

**Comment by bagg3rs** [comment]
Thanks for raising the first issue (by a user) @w-wood 🎊 🥇  this was resolved in https://github.com/ministryofjustice/data-platform-support/issues/52 see slack message [here](https://mojdt.slack.com/archives/C4PF7QAJZ/p1683206143410319?thread_ts=1683187227.723339&cid=C4PF7QAJZ)
