### ISSUE TITLE
Problem running a python dash app locally

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/data-platform-support#52]
Hi, I'm trying to run a python dash app locally on the AP but when I try to launch the app on the terminal it produces no error messages but just drops back to the waiting prompt.  I tried using both JupyterLab versions that have Tunnel installed but both do the same thing.  We've made no recent code changes, so could this be an AP issue or has there been a change in the way the tunnel work?  Thanks.

[Slack Message](https://mojdt.slack.com/archives/C4PF7QAJZ/p1683187227723339)

**Comment by ymao2** [comment]
https://mojdt.slack.com/archives/C4PF7QAJZ/p1683187227723339

**Comment by tom-webber** [comment]
User resolved their issue: the documentation was wrong on their end, resulting in them attempting to start the app from wrong entry point.
