### ISSUE TITLE
Bucket access

### ISSUE THREAD

**Issue by fkhamkar** [ministryofjustice/data-platform-support#56]
### What happened?

Please could i have read/write access to this bucket "alpha-cbf-logit". It's for an ad-hoc project that I am currently working on.

**Comment by bagg3rs** [comment]
[slack thread](https://mojdt.slack.com/archives/C4PF7QAJZ/p1683282707691009)

**Comment by BrianEllwood** [comment]
offered advice on where to find the name of the bucket admin ie “Warehouse data” tab in Control Panel 

Unfortunately the admin is out of the office which is why the user contacted us

Seeking advice on the process
