### ISSUE TITLE
Redeploy app - probation-staffing-model-dash-app

### ISSUE THREAD

**Issue by w-wood** [ministryofjustice/data-platform-support#61]
### What happened?

We've updated this app and it now needs to be redeployed so the changes are on the live dashboard.  This app has NOT been migrated yet.  GitHub URL is: https://github.com/moj-analytical-services/probation-staffing-model-dash-app

**Comment by bagg3rs** [comment]
I just ran this past redeploy and they need a little more information 
Can you fill in this [form](https://github.com/moj-analytical-services/analytical-platform-applications/issues/new?assignees=EO510%2C+YvanMOJdigital&labels=redeploy&projects=&template=redeploy-app-request.md&title=%5BREDEPLOY%5D)

**Comment by ymao2** [comment]
Just completed the redeployment, I close this issue
