### ISSUE TITLE
Grant permissions to an S3 bucket

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/data-platform-support#63]
Hi AP support team I'm trying to grant permissions to an S3 bucket (specified folder only) and am getting an error:
I have Admin rights on the bucket.
Also attached is the Grant Access form populated as before the error.

[Slack Message](https://mojdt.slack.com/archives/C4PF7QAJZ/p1684313428200389)

**Comment by wellermatt1971** [comment]
Feel free to close the ticket as my colleague has granted access.

**Comment by michaeljcollinsuk** [comment]
I have created a ticket with details of the underlying bug to be fixed https://dsdmoj.atlassian.net/browse/ANPL-1581?atlOrigin=eyJpIjoiZDM0ZDE3MGNhODgxNDFjNDg4MDJlMTFlMjEwZTdhMGEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
