### ISSUE TITLE
Quicksight access

### ISSUE THREAD

**Issue by opmoj** [ministryofjustice/data-platform-support#74]
### Which tool do you need help with?

Amazon Web Services

### What happened?

I am a data engineer in the Calculate Release Date team. I am trying to connect Athena to Quicksight to be able to create dashboards in Quicksight. The security team have signed this off from a security perspective. However I do need a sign off from an AP perspective and would require permissions to access Quicskight for this. I'm only here for 2 weeks to get this done so would appreciate a quick response on this.

**Comment by bagg3rs** [comment]
Quicksight access was given access to Athena handled by DE team. 
Additional issues raised [here](https://github.com/ministryofjustice/data-platform-support/issues/90)
