### ISSUE TITLE
R script fails to pull latest raw files from AWS

### ISSUE THREAD

**Issue by violettada** [ministryofjustice/data-platform-support#80]
### Which tool do you need help with?

R

### What happened?

We have a script for automating a dashboard, however whenever I run it my output only goes till the latest date someone ELSE has already run the script. Otherwise, it fails to pull the latest files on its own. The only error I get is the following: 

```
Error in botor::s3_download_file(s3_path, tempfile(fileext = file_ext), :
Python `ClientError`: An error occurred (404) when calling the HeadObject operation: Not Found
```
The code which creates the error is:

```
write_df_to_csv_in_s3(
    am_caseload_final, 
    paste(
        bucket, "/", output_dir_intermediate_part2_am, "AM_Caseload_int_part2_", filedate_am, ".csv", 
        sep=""
    ), 
    row.names = FALSE, 
    overwrite=TRUE
)
write_df_to_csv_in_s3(
    em_caseload_final, 
    paste(
        bucket, "/", output_dir_em_clean, "EM_Caseload_clean_", filedate_em, ".csv", 
        sep=""
    ), 
    row.names = FALSE, 
    overwrite=TRUE
)
}
```

Any help is appreciated!

**Comment by tom-webber** [comment]
Hi @violettada, this looks like it's one for the [ASD Slack #r](https://asdslack.slack.com/archives/C1PUCG719) channel, or potentially the #python channel as it's piping through a `boto3` error.

With that said, the error _may_ indicate that the required folder structure doesn't already exist (see [a discussion here](https://github.com/boto/boto3/issues/2452)) where you're trying to add the files. This might explain why it only works with pre-existing dates. Do some of those variables you name in the `paste` output path contain `/`s?

If this is the case, the solution would be to create the output folder structure in an earlier step before trying to write the file.

**Comment by jacobwoffenden** [comment]
Hi @violettada

As there hasn't been a response for 2 weeks I will close this issue.

If you need further assistance, feel free to reopen.

Thanks!
