### ISSUE TITLE
AP access for contractor

### ISSUE THREAD

**Issue by paulasoares1** [ministryofjustice/data-platform-support#81]
### Which tool do you need help with?

Database Access, User and Account

### What happened?

Hello,

We will have an external data science contractor join our team soon, for a period of 6 weeks. Will they be allowed to access data on the AP if they have an MoJ laptop and security clearance? They will need to run code that loads in data from S3 buckets, which we can give them access to. 

Thank you in advance!

**Comment by paulasoares1** [comment]
Great, thank you for clarifying 👍  Should I close the issue now? Sorry just learning how the new process works!

**Comment by bagg3rs** [comment]
👋 @paulasoares1 yes you can close issue yourself if it been completed. I will close this for you now.
