### ISSUE TITLE
[AP RStudio Loading Issue] - Unable to load RStudio up on the AP

### ISSUE THREAD

**Issue by parminder-thindal-moj** [ministryofjustice/data-platform-support#84]
### Which tool do you need help with?

RStudio

### What happened?

Afternoon, I am having trouble accessing my RStudio on the AP. I was previously getting 502 errors, but now RStudio is stuck perpetually trying to load a session.

So far I have tried restarting my browser, restarting my RStudio via the control panel.

I'm not having issues in accessing Jupyter or S3. My internet is stable as other pages are loading fine.

GH Username - `parminder-thindal-moj`
Could anyone please help advise? 

Thanks

**Comment by bogdan-mania-moj** [comment]
Hello, could you please try resetting your home directory? There should be an option on the analytical tools page.

**Comment by parminder-thindal-moj** [comment]
Hi, I've tried resetting my home directory a few times, and still get the same issue in RStudio.

**Comment by parminder-thindal-moj** [comment]
Hi - it seems to have resolved itself now. I can get back into RStudio. Thanks
