### ISSUE TITLE
Issue installing renv package

### ISSUE THREAD

**Issue by carolinekidd** [ministryofjustice/data-platform-support#85]
### Which tool do you need help with?

RStudio

### What happened?

I'm working on a new project in RStudio, and am having trouble installing the renv package i.e. running the following line of code:
if(!"renv" %in% installed.packages()[, "Package"]) install.packages("renv")

I've tried to reset my home directory and also tried running the code in the console but neither has worked. The error message I get is pasted in the box below. Grateful for any assistance.

### Relevant log output

```bash
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
Warning in install.packages :
  installation of package ‘renv’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp746t3U/downloaded_packages’
```

**Comment by ThomasHepworth** [comment]
Slack won't let me combine my accounts, but this issue is already logged in the platform docs [here](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/package-management.html#renv-tips-and-tricks).

If any of you see:
```r
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
```

just point them to that link.

**Comment by carolinekidd** [comment]
Thank you. I've done as suggested in the guidance and have attempted to re-run the code:

if(!"renv" %in% installed.packages()[, "Package"]) install.packages("renv")
renv::init(bare = TRUE)
renv::use_python(python='/usr/bin/python3')
renv::install('reticulate')
reticulate::py_install('boto3')
renv::install('botor')


It seems to have worked although I did get the following message - is this something I should be concerned about?

The project is currently out-of-sync.

**Comment by ThomasHepworth** [comment]
`renv::snapshot()` to sync up the project, I believe.

It's been over a year since I last did a project in R though, so I may be wrong.

**Comment by bagg3rs** [comment]
Any further R issues please see [#r](https://mojdt.slack.com/archives/C1PUCG719) also
