### ISSUE TITLE
User guide sometimes fails to load

### ISSUE THREAD

**Issue by katharinebreeze** [ministryofjustice/data-platform-support#86]
### Which tool do you need help with?

User guidance

### What happened?

I've noticed the last few times I tried to user the user guidance (https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#1-github-account) it's been slow to load, or failed to load at all, which has made it difficult to find the guidance I need/want to share with someone else.

For example:

![image](https://github.com/ministryofjustice/data-platform-support/assets/36629221/c508185e-8a39-40dc-9b2a-4511f23d671f)

**Comment by bagg3rs** [comment]
This maybe due to VPN / provider issues. We will close the issue now but can revisit if it comes up again
