### ISSUE TITLE
2 factor authentication for analytical platform - how to log back into account? 

### ISSUE THREAD

**Issue by shireen-dhada** [ministryofjustice/data-platform-support#87]
### Which tool do you need help with?

User and Account

### What happened?

I have set up 2FA via an app for access to the AP and GitHub. I had to factory reset my phone. I have managed to regain access to the 2FA for Github but not able to get access to the AP. Please can I have some help in accessing account via my 2FA for AP.

**Comment by jhackett-ap** [comment]
Hi Shireen! I've sent you a link so you can reset your MFA for the control panel. Let me know if you have any trouble: I'll close this request at the end of the day if I don't hear back.

**Comment by shireen-dhada** [comment]
Hello, really sorry but I may have clicked on the link twice by accident as it states the link has already been used. Can it be reset and I will be vigilant this time! Sorry!

**Comment by jhackett-ap** [comment]
No worries at all, I've sent another.

**Comment by shireen-dhada** [comment]
Thank you, I have clicked on the link and seem to be stuck on the following screen: 
<img width="1280" alt="image" src="https://github.com/ministryofjustice/data-platform-support/assets/99402398/588798a4-8d87-4ec1-8f48-64d2f3ba6278">

**Comment by jhackett-ap** [comment]
Hi Shireen,

I've double checked and realised that I hadn't done all the steps for this - please try to log in (to the control panel first) and it should let you reset your MFA there. Give me a shout if that doesn't work and I'll look more closely.

Cheers
John

**Comment by shireen-dhada** [comment]
I am in! thank you :)
