### ISSUE TITLE
access to the moj-analytical-services GitHub platform

### ISSUE THREAD

**Issue by simonytta** [ministryofjustice/data-platform-support#88]
### Which tool do you need help with?

Amazon Web Services

### What happened?

Hello, I have had inactive account for some time, and now need to use it again, however due to inactivity it was disabled. My username is simonytta, hope you can assists. Thanks!

**Comment by jacobwoffenden** [comment]
Hey @simonytta,

You need to request an invite to https://github.com/moj-analytical-services via [`#ask-operations-engineering`](https://mojdt.slack.com/archives/C01BUKJSZD4)
