### ISSUE TITLE
JupyterLab continually disconnects and has issues saving in the afternoon every day for the past 3 days

### ISSUE THREAD

**Issue by rogerbrownmoj** [ministryofjustice/data-platform-support#92]
### Which tool do you need help with?

JupyterLab

### What happened?

Jupyter Lab continually in the afternoon has severe server issues and continually disconnects and won't save the notebook. This has happened the last 3 days. I restarted my notebook in case that was the cause but it's made no impact

**Comment by michaeljcollinsuk** [comment]
Hi @rogerbrownmoj I tried to look into the connection issues you have reported but nothing has jumped out at me as a cause. I did also check the logs for your container, and have found the following warning when trying to save a notebook:
```
[I 2023-05-26 14:33:57.133 ServerApp] Saving file at /airflow-prison-visitor-app/visitor_splink/Initial_data_prep_sample-Copy1.ipynb
[W 2023-05-26 14:33:57.503 ServerApp] Notebook airflow-prison-visitor-app/visitor_splink/Initial_data_prep_sample-Copy1.ipynb is not trusted
```

Is this the notebook that you are trying to save? [You could try the this suggestion to mark the notebook as trusted](https://jupyter-notebook.readthedocs.io/en/latest/notebook.html#trusting-notebooks) (open a terminal shell to run the command) and try saving again

**Comment by michaeljcollinsuk** [comment]
Which commands did you try in the terminal? For clarity, I would open a new terminal (by clicking File > New > Terminal) and then entering:
```
jupyter trust /path/to/notebook.ipynb
```

Are you using a DOM1 device? I've spoken with the team and we are wondering if it could be VPN related, as we have not had reports of this issue from other users, and there is nothing we are aware of set to restart around 14:55. I am going to do some extra monitoring around that time though to see if I can spot anything unusual.

**Comment by rogerbrownmoj** [comment]
Hi Michael. I had not run the command from the root folder put doing it from the root folder and including the full path that has now worked, although yesterday when I was working on it it had no problems saving. 
I'm using a MacBook rather than a DOM1. I was working on a different project yesterday so didn't see the issues but I'll check today and advise of anything unusual

**Comment by jacobwoffenden** [comment]
Hi @rogerbrownmoj,

Just checking in to see if you're still experiencing your issue with JupyterLab

Thanks!

**Comment by michaeljcollinsuk** [comment]
Hi @rogerbrownmoj. Took another look at the monitoring of your pod this afternoon, and have noticed some CPU spikes.

There was a CPU spike at around 3:02pm today (note the timestamps in the screenshots use UTC with is an hour behind BST) which exceeds the CPU limit. There are then further spikes in the afternoon.
<img width="1840" alt="Screenshot 2023-06-06 at 16 11 53" src="https://github.com/ministryofjustice/data-platform-support/assets/15347726/604454b2-fe8b-4910-a242-56208326e147">

Zooming out a bit there were also CPU spikes in the morning:
<img width="1840" alt="Screenshot 2023-06-06 at 16 14 48" src="https://github.com/ministryofjustice/data-platform-support/assets/15347726/25a90a5a-0f4a-443a-9832-48b833a788ca">

Memory usage over this period is steady, somewhat high but well within the limit:
<img width="1840" alt="Screenshot 2023-06-06 at 16 15 43" src="https://github.com/ministryofjustice/data-platform-support/assets/15347726/6d84b9ab-03c4-4645-8125-778a73cc63a2">

Were you running any particularly intensive code at these times that could cause the CPU to spike?

**Comment by rogerbrownmoj** [comment]
At the moment I am wrangling with a dataset that is 6.7 million rows and then applying Splink to try and manipulate it less, which may be the cause of the spike

**Comment by rogerbrownmoj** [comment]
Morning Michael, I no longer have that issue where I was unable to shut down old kernels. I'll be mindful of multiple kernels running, how many should I have running? It's usually related notebooks where I run code based on the output of another and testing the impact of tuning the code.
Please note that after today I'm on annual leave so if I don't respond until after 20th June, I'm not ignoring you :-)

**Comment by michaeljcollinsuk** [comment]
It's not so much that there is a limit to the number of kernels you should have running, it depends on what they are doing and how much resource they are using. So its just worth bearing in mind, but glad you are no longer having the issue with closing them down - as such I have now increased your memory resources/limit, lets see if that helps.

I am due to be on paternity leave myself from the 20th June, so given that you are away until then, I think its best to close this issue for now, and if it is still a problem when you are back please open a new issue (referencing this one). That way it will make sure that someone else in the team picks it up and responds, rather than comments here being missed until I am back. Although hopefully increasing your memory will have helped :-)
