### ISSUE TITLE
Unable to add ministryofjustice organisation member read access to a repo

### ISSUE THREAD

**Issue by glenn-christmas** [ministryofjustice/data-platform-support#97]
### Which tool do you need help with?

GitHub

### What happened?

I'd like to be able to provide a member of the `ministryofjustice `organisation on GitHub read access to a repo. However because they are not in `moj-analytical-services`  I'm not able to. Is there a way around this? (It's a Justice Digital person that wants to take a look at a repo of ours.)

If it's easier to do this yourself, please could @polsonby be given read access to the gold-scorecard-form repo. Thanks.

**Comment by jacobwoffenden** [comment]
Hey @glenn-christmas!

You can request that @Polsonby be added to https://github.com/moj-analytical-services by posting into [`#ask-operations-engineering`](https://mojdt.slack.com/archives/C01BUKJSZD4)

**Comment by bagg3rs** [comment]
Ian is in the AP Org now, you can add him to the read group on the repo.
