### ISSUE TITLE
How do I add two external collaborators from CPS to an internal repo?

### ISSUE THREAD

**Issue by katharinebreeze** [ministryofjustice/data-platform-support#98]
### Which tool do you need help with?

User and Account

### What happened?

Please can you give two external users from the CPS read access to this repo: https://github.com/moj-analytical-services/cjs-scorecard

Their usernames are `DaveAllanCPS` and `SophieYoung11`, I have asked them to setup two factor authentication.

**Comment by AntonyBishop** [comment]
Hi @katharinebreeze please can you raise an Issue or PR against the outside collaborators repo - templates [here](https://github.com/moj-analytical-services/github-outside-collaborators/issues/new/choose). You'll need to provide some additional as per the template. Any queries please reply to this thread.

**Comment by AntonyBishop** [comment]
PR raised to add collaborators - https://github.com/moj-analytical-services/github-outside-collaborators/pull/63

**Comment by AntonyBishop** [comment]
Just running apply to trigger the invites.

**Comment by AntonyBishop** [comment]
Invites issued.
